import { sql } from 'drizzle-orm';
import { bigint, check, foreignKey, index, integer, pgTable, primaryKey, real, serial, text, uniqueIndex } from 'drizzle-orm/pg-core';
import { agentMessages, agentRuns, apiTokens, auditEvents, authSessions, contactSubmissions, deviceCodes, permissions, rolePermissions, roles, runtimeEnvelopes, serviceCredentials, subscribers, teamMemberships, teamRoleBindings, teams, userEmailAddresses, userIdentities, userRoleBindings, users, webSessions } from './subscribers.ts';
import { commonsDecisions, commonsDelegations, commonsGovernanceEvents, commonsParticipants, commonsProposalBackings, commonsProposalVotes, commonsProposals, commonsQuestions, commonsWeightSnapshots, governanceProposalVersions, governanceProposals, projectGovernancePolicies, teamGovernancePolicies } from './commons-participants.ts';
import { entitlements, governanceDecisions, governanceDelegations, governanceElectorateSnapshots, governanceEvents, governanceProposalVotes, governanceVoteEvents, knowledgePacks, projectCapabilityGrants, projectConnections, projects, remoteJobEvents, remoteJobs, teamApiKeys, teamStorageLocators } from './governance-electorate-snapshots.ts';
import { catalogArtifactVersions, catalogItemCollaborators, catalogItems, commerceContributions, commerceGovernancePolicies, commerceOwnershipRecords, commerceOwnershipTransfers, commerceProducts, commerceStewardshipAssignments, commerceVendors } from './catalog-items.ts';
import { commerceCartItems, commerceCarts, commerceCheckouts, commerceGovernanceEvents, commerceOffers, commerceOrderItems, commerceOrders, commercePaymentGroups, commercePrices, commerceProductVersions } from './commerce-product-versions.ts';
import { commerceBuyerStripeCustomers, commerceEntitlements, commerceFulfillmentEvents, commerceRefunds, commerceServiceContracts, commerceServiceEvents, commerceServiceQuotes, commerceServiceRequests, commerceSubscriptions } from './commerce-subscriptions.ts';
import { betterAuthSession, betterAuthUser, commerceCapacityListingInquiries, commerceCapacityListings, commerceWebhookEvents, projectDeploymentEvents, projectDeployments, projectEnvironments, projectHosting, projectInfrastructureResources, projectSummarySnapshots, teamInboxItems } from './commerce-capacity-listings.ts';
import { betterAuthAccount, betterAuthVerification, capacityExecutionProviders, capacityProviderLanes, capacityProviderRegistrationRequests, capacityProviderTeamMemberships, capacityProviders, teamCapacityRegistrationKeys, teamInvites, teamWebHosts } from './better-auth-account.ts';
import { capacityAdmissionCounters, capacityAuditEvents, capacityGrants, capacityOperationReceipts, capacityProviderAccessTokens, capacityProviderProofNonces, capacityProviderRegistrationRateLimits, capacityProviderTeamCredentials, capacityReservationCounterClaims, capacityReservations } from './capacity-provider-team-credentials.ts';
import { capacityAllocationSets, capacityLedgerEntries, capacityProviderAssignments, capacityUsageActuals, projectAgentClasses, providerAvailabilitySessions } from './capacity-ledger-entries.ts';
import { approvalRequests, githubRepositoryGrants, hubContentSources, hubRepositories, repositoryHosts, treeDxCredentialIssuanceRecords, treeDxInstances, workflowDispatchRecords, workflowOperationRecords } from './github-repository-grants.ts';
import { authProviderStates, authReauthenticationGrants, hubLaunchEvents, hubLaunches, hubWorkspaceLinks, projectUpdatePlans, providerCredentialSessions, treeDxDeployments, treeDxMirrors, treeDxProjectLibraries, treeDxShares, userNotificationGlobalContentTypes, userNotificationPreferences, userNotificationProjectContentTypes, userNotificationProjectOverrides, userPersonalThemes, userPreferences } from './tree-dx-project-libraries.ts';
import { agentCapacityPlans, capacityWorkdayEvents, clientEncryptedEscrowRecords, secretMetadataRecords, treeDxProxyHandles, workdayCapacityEnvelopes } from './capacity-workday-events.ts';
import { creditConversionProfiles, cursorState, leaseState, marketAuthCredentials, marketAuthPasswordResets, marketOperationRunners, messageQueue, notificationEmailDeliveries, notificationEvents, platformOperationEvents, platformOperations, platformRepositoryClaims, runtimeRecords, seedRuns, userNotifications } from './notification-events.ts';
import { agentFallbackOutputs, agentModeRuns, capacityWorkdayRuns, decisionAssignmentGraphs, decisionExecutionInputs, decisionPlanningStatuses, deliverableContracts, deliverableManifests, planningInputRequests, structuredAgentEstimates } from './agent-mode-runs.ts';

export const treeseedMarketSchema = {
	subscribers,
	agentRuns,
	agentMessages,
	contactSubmissions,
	runtimeEnvelopes,
	users,
	userIdentities,
	userEmailAddresses,
	roles,
	permissions,
	rolePermissions,
	userRoleBindings,
	apiTokens,
	serviceCredentials,
	authSessions,
	auditEvents,
	deviceCodes,
	teams,
	teamMemberships,
	teamRoleBindings,
	webSessions,
	commonsParticipants,
	commonsQuestions,
	commonsProposals,
	commonsWeightSnapshots,
	commonsProposalBackings,
	commonsProposalVotes,
	commonsDelegations,
	commonsDecisions,
	commonsGovernanceEvents,
	teamGovernancePolicies,
	projectGovernancePolicies,
	governanceProposals,
	governanceProposalVersions,
	governanceElectorateSnapshots,
	governanceProposalVotes,
	governanceVoteEvents,
	governanceDelegations,
	governanceDecisions,
	governanceEvents,
	projects,
	projectConnections,
	projectCapabilityGrants,
	teamApiKeys,
	entitlements,
	remoteJobs,
	remoteJobEvents,
	knowledgePacks,
	teamStorageLocators,
	catalogItems,
	catalogArtifactVersions,
	catalogItemCollaborators,
	commerceVendors,
	commerceProducts,
	commerceOwnershipRecords,
	commerceStewardshipAssignments,
	commerceContributions,
	commerceGovernancePolicies,
	commerceOwnershipTransfers,
	commerceProductVersions,
	commerceOffers,
	commercePrices,
	commerceGovernanceEvents,
	commerceCarts,
	commerceCartItems,
	commerceCheckouts,
	commerceOrders,
	commerceOrderItems,
	commercePaymentGroups,
	commerceSubscriptions,
	commerceEntitlements,
	commerceBuyerStripeCustomers,
	commerceRefunds,
	commerceFulfillmentEvents,
	commerceServiceRequests,
	commerceServiceQuotes,
	commerceServiceContracts,
	commerceServiceEvents,
	commerceCapacityListings,
	commerceCapacityListingInquiries,
	commerceWebhookEvents,
	projectHosting,
	projectEnvironments,
	projectInfrastructureResources,
	projectDeployments,
	projectDeploymentEvents,
	projectSummarySnapshots,
	teamInboxItems,
	betterAuthUser,
	betterAuthSession,
	betterAuthAccount,
	betterAuthVerification,
	teamWebHosts,
	teamInvites,
	capacityProviders,
	capacityExecutionProviders,
	capacityProviderLanes,
	teamCapacityRegistrationKeys,
	capacityProviderRegistrationRequests,
	capacityProviderTeamMemberships,
	capacityProviderTeamCredentials,
	capacityProviderAccessTokens,
	capacityProviderProofNonces,
	capacityProviderRegistrationRateLimits,
	capacityAuditEvents,
	capacityOperationReceipts,
	capacityGrants,
	capacityReservations,
	capacityAdmissionCounters,
	capacityReservationCounterClaims,
	capacityLedgerEntries,
	capacityUsageActuals,
	approvalRequests,
	repositoryHosts,
	hubRepositories,
	hubContentSources,
	treeDxInstances,
	treeDxProjectLibraries,
	treeDxMirrors,
	treeDxShares,
	treeDxDeployments,
	secretMetadataRecords,
	clientEncryptedEscrowRecords,
	githubRepositoryGrants,
	workflowOperationRecords,
	workflowDispatchRecords,
	treeDxCredentialIssuanceRecords,
	hubLaunches,
	hubLaunchEvents,
	hubWorkspaceLinks,
	projectUpdatePlans,
	providerCredentialSessions,
	userPreferences,
	authProviderStates,
	authReauthenticationGrants,
	userPersonalThemes,
	userNotificationPreferences,
	userNotificationGlobalContentTypes,
	userNotificationProjectOverrides,
	userNotificationProjectContentTypes,
	notificationEvents,
	userNotifications,
	notificationEmailDeliveries,
	creditConversionProfiles,
	seedRuns,
	runtimeRecords,
	cursorState,
	leaseState,
	messageQueue,
	capacityAllocationSets,
	projectAgentClasses,
	providerAvailabilitySessions,
	decisionPlanningStatuses,
	planningInputRequests,
	decisionExecutionInputs,
	structuredAgentEstimates,
	decisionAssignmentGraphs,
	deliverableContracts,
	deliverableManifests,
	capacityWorkdayRuns,
	capacityWorkdayEvents,
	workdayCapacityEnvelopes,
	capacityProviderAssignments,
	agentModeRuns,
	agentFallbackOutputs,
	agentCapacityPlans,
	treeDxProxyHandles,
	platformOperations,
	platformOperationEvents,
	marketOperationRunners,
	platformRepositoryClaims,
	marketAuthCredentials,
	marketAuthPasswordResets,
};

export type TreeseedMarketDrizzleSchema = typeof treeseedMarketSchema;
