import type { MarketClient } from '../market-client.ts';
import { requestMethod } from './request.ts';
import { localAuthPathsMethod } from './local-auth-paths.ts';
import { requestFirstMethod } from './request-first.ts';
import { startDeviceLoginMethod } from './start-device-login.ts';
import { pollDeviceLoginMethod } from './poll-device-login.ts';
import { refreshTokenMethod } from './refresh-token.ts';
import { logoutMethod } from './logout.ts';
import { webSignUpMethod } from './web-sign-up.ts';
import { webSignInMethod } from './web-sign-in.ts';
import { confirmWebEmailMethod } from './confirm-web-email.ts';
import { checkWebUsernameMethod } from './check-web-username.ts';
import { checkWebEmailMethod } from './check-web-email.ts';
import { authProvidersMethod } from './auth-providers.ts';
import { accountIdentityMethod } from './account-identity.ts';
import { webEmailsMethod } from './web-emails.ts';
import { addWebEmailMethod } from './add-web-email.ts';
import { verifyWebEmailMethod } from './verify-web-email.ts';
import { setPrimaryWebEmailMethod } from './set-primary-web-email.ts';
import { deleteWebEmailMethod } from './delete-web-email.ts';
import { webSessionsMethod } from './web-sessions.ts';
import { revokeWebSessionMethod } from './revoke-web-session.ts';
import { updateWebProfileMethod } from './update-web-profile.ts';
import { webAppearanceMethod } from './web-appearance.ts';
import { updateWebAppearanceMethod } from './update-web-appearance.ts';
import { updateWebPasswordMethod } from './update-web-password.ts';
import { requestWebPasswordResetMethod } from './request-web-password-reset.ts';
import { completeWebPasswordResetMethod } from './complete-web-password-reset.ts';
import { accountDeletionBlockersMethod } from './account-deletion-blockers.ts';
import { deleteAccountMethod } from './delete-account.ts';
import { webNotificationPreferencesMethod } from './web-notification-preferences.ts';
import { updateWebNotificationPreferencesMethod } from './update-web-notification-preferences.ts';
import { webNotificationsMethod } from './web-notifications.ts';
import { markWebNotificationReadMethod } from './mark-web-notification-read.ts';
import { personalThemesMethod } from './personal-themes.ts';
import { createPersonalThemeMethod } from './create-personal-theme.ts';
import { updatePersonalThemeMethod } from './update-personal-theme.ts';
import { deletePersonalThemeMethod } from './delete-personal-theme.ts';
import { meMethod } from './me.ts';
import { marketsMethod } from './markets.ts';
import { currentMarketMethod } from './current-market.ts';
import { teamsMethod } from './teams.ts';
import { createTeamMethod } from './create-team.ts';
import { deleteTeamMethod } from './delete-team.ts';
import { teamDeletionBlockersMethod } from './team-deletion-blockers.ts';
import { teamMembersMethod } from './team-members.ts';
import { teamPermissionsMethod } from './team-permissions.ts';
import { projectsMethod } from './projects.ts';
import { createProjectMethod } from './create-project.ts';
import { deleteProjectMethod } from './delete-project.ts';
import { projectDeletionBlockersMethod } from './project-deletion-blockers.ts';
import { projectAccessMethod } from './project-access.ts';
import { upsertProjectConnectionMethod } from './upsert-project-connection.ts';
import { projectHostsMethod } from './project-hosts.ts';
import { projectSecretEscrowRecordsMethod } from './project-secret-escrow-records.ts';
import { createProjectSecretEscrowMethod } from './create-project-secret-escrow.ts';
import { projectSecretEscrowMethod } from './project-secret-escrow.ts';
import { updateProjectSecretEscrowMethod } from './update-project-secret-escrow.ts';
import { migrateProjectSecretEscrowMethod } from './migrate-project-secret-escrow.ts';
import { tombstoneProjectSecretEscrowMethod } from './tombstone-project-secret-escrow.ts';
import { projectGitHubActionsSecretPublicKeyMethod } from './project-git-hub-actions-secret-public-key.ts';
import { deployProjectGitHubActionsSecretMethod } from './deploy-project-git-hub-actions-secret.ts';
import { dispatchProjectWorkflowOperationMethod } from './dispatch-project-workflow-operation.ts';
import { teamTreeDxMethod } from './team-tree-dx.ts';
import { updateTeamTreeDxMethod } from './update-team-tree-dx.ts';
import { provisionTeamTreeDxMethod } from './provision-team-tree-dx.ts';
import { treeDxMirrorsMethod } from './tree-dx-mirrors.ts';
import { createTreeDxMirrorMethod } from './create-tree-dx-mirror.ts';
import { syncTreeDxMirrorMethod } from './sync-tree-dx-mirror.ts';
import { treeDxSharesMethod } from './tree-dx-shares.ts';
import { createTreeDxShareMethod } from './create-tree-dx-share.ts';
import { projectTreeDxLibraryMethod } from './project-tree-dx-library.ts';
import { upsertProjectTreeDxLibraryMethod } from './upsert-project-tree-dx-library.ts';
import { projectRepositoryTopologyMethod } from './project-repository-topology.ts';
import { projectTreeDxProxyAuditMethod } from './project-tree-dx-proxy-audit.ts';
import { projectAgentFallbackOutputsMethod } from './project-agent-fallback-outputs.ts';
import { treeDxBuildContextMethod } from './tree-dx-build-context.ts';
import { treeDxReadRepositoryFilesMethod } from './tree-dx-read-repository-files.ts';
import { createTreeDxWorkspaceMethod } from './create-tree-dx-workspace.ts';
import { updateProjectRepositoryTopologyMethod } from './update-project-repository-topology.ts';
import { initializeProjectRepositoryMethod } from './initialize-project-repository.ts';
import { importProjectRepositoryMethod } from './import-project-repository.ts';
import { auditProjectHostsMethod } from './audit-project-hosts.ts';
import { replaceProjectHostMethod } from './replace-project-host.ts';
import { resyncProjectHostMethod } from './resync-project-host.ts';
import { rotateProjectHostMethod } from './rotate-project-host.ts';
import { projectDeploymentStateMethod } from './project-deployment-state.ts';
import { projectDeploymentsMethod } from './project-deployments.ts';
import { projectDeploymentMethod } from './project-deployment.ts';
import { projectDeploymentByIdMethod } from './project-deployment-by-id.ts';
import { projectDeploymentEventsMethod } from './project-deployment-events.ts';
import { createProjectWebDeploymentMethod } from './create-project-web-deployment.ts';
import { retryProjectDeploymentMethod } from './retry-project-deployment.ts';
import { resumeProjectDeploymentMethod } from './resume-project-deployment.ts';
import { cancelProjectDeploymentMethod } from './cancel-project-deployment.ts';
import { teamCapacityRegistrationKeyMethod } from './team-capacity-registration-key.ts';
import { revealTeamCapacityRegistrationKeyMethod } from './reveal-team-capacity-registration-key.ts';
import { rotateTeamCapacityRegistrationKeyMethod } from './rotate-team-capacity-registration-key.ts';
import { enableTeamCapacityRegistrationKeyMethod } from './enable-team-capacity-registration-key.ts';
import { disableTeamCapacityRegistrationKeyMethod } from './disable-team-capacity-registration-key.ts';
import { updateTeamCapacityRegistrationKeyStatusMethod } from './update-team-capacity-registration-key-status.ts';
import { capacityProviderRegistrationRequestsMethod } from './capacity-provider-registration-requests.ts';
import { capacityProviderRegistrationRequestMethod } from './capacity-provider-registration-request.ts';
import { reviewCapacityProviderRegistrationMethod } from './review-capacity-provider-registration.ts';
import { capacityProviderMembershipsMethod } from './capacity-provider-memberships.ts';
import { capacityProviderMembershipMethod } from './capacity-provider-membership.ts';
import { capacityAuditEventsMethod } from './capacity-audit-events.ts';
import { capacityProviderCredentialsMethod } from './capacity-provider-credentials.ts';
import { authorizeCapacityProviderCredentialRotationMethod } from './authorize-capacity-provider-credential-rotation.ts';
import { revokeCapacityProviderCredentialMethod } from './revoke-capacity-provider-credential.ts';
import { suspendCapacityProviderMembershipMethod } from './suspend-capacity-provider-membership.ts';
import { resumeCapacityProviderMembershipMethod } from './resume-capacity-provider-membership.ts';
import { revokeCapacityProviderMembershipMethod } from './revoke-capacity-provider-membership.ts';
import { updateCapacityProviderMembershipStatusMethod } from './update-capacity-provider-membership-status.ts';
import { capacityGrantsMethod } from './capacity-grants.ts';
import { capacityGrantMethod } from './capacity-grant.ts';
import { planCapacityGrantMethod } from './plan-capacity-grant.ts';
import { createCapacityGrantMethod } from './create-capacity-grant.ts';
import { transitionCapacityGrantMethod } from './transition-capacity-grant.ts';
import { capacityAllocationSetsMethod } from './capacity-allocation-sets.ts';
import { createCapacityAllocationSetMethod } from './create-capacity-allocation-set.ts';
import { planCapacityAllocationSetMethod } from './plan-capacity-allocation-set.ts';
import { capacityAllocationSetMethod } from './capacity-allocation-set.ts';
import { activateCapacityAllocationSetMethod } from './activate-capacity-allocation-set.ts';
import { supersedeCapacityAllocationSetMethod } from './supersede-capacity-allocation-set.ts';
import { archiveCapacityAllocationSetMethod } from './archive-capacity-allocation-set.ts';
import { explainCapacityAllocationSetMethod } from './explain-capacity-allocation-set.ts';
import { providerAvailabilitySessionsMethod } from './provider-availability-sessions.ts';
import { capacityProviderAssignmentsMethod } from './capacity-provider-assignments.ts';
import { executionRunsMethod } from './execution-runs.ts';
import { admitCapacityAssignmentMethod } from './admit-capacity-assignment.ts';
import { providerAssignmentExplanationMethod } from './provider-assignment-explanation.ts';
import { capacityProviderAssignmentMethod } from './capacity-provider-assignment.ts';
import { capacityReservationsMethod } from './capacity-reservations.ts';
import { capacityReservationExplanationMethod } from './capacity-reservation-explanation.ts';
import { capacityUsageMethod } from './capacity-usage.ts';
import { capacityLedgerMethod } from './capacity-ledger.ts';
import { capacityEvidencePageMethod } from './capacity-evidence-page.ts';
import { projectCapacityDiagnosticsMethod } from './project-capacity-diagnostics.ts';
import { projectAgentClassesMethod } from './project-agent-classes.ts';
import { createProjectAgentClassMethod } from './create-project-agent-class.ts';
import { projectAgentClassMethod } from './project-agent-class.ts';
import { updateProjectAgentClassMethod } from './update-project-agent-class.ts';
import { projectAgentModeRunsMethod } from './project-agent-mode-runs.ts';
import { projectCapacityRuntimeDiagnosticsMethod } from './project-capacity-runtime-diagnostics.ts';
import { decisionPlanningStatusMethod } from './decision-planning-status.ts';
import { createPlanningInputRequestMethod } from './create-planning-input-request.ts';
import { decisionStructuredEstimatesMethod } from './decision-structured-estimates.ts';
import { createStructuredAgentEstimateMethod } from './create-structured-agent-estimate.ts';
import { acceptStructuredAgentEstimateMethod } from './accept-structured-agent-estimate.ts';
import { decisionExecutionInputsMethod } from './decision-execution-inputs.ts';
import { createDecisionExecutionInputMethod } from './create-decision-execution-input.ts';
import { acceptDecisionExecutionInputMethod } from './accept-decision-execution-input.ts';
import { requestDecisionExecutionInputRevisionMethod } from './request-decision-execution-input-revision.ts';
import { decisionAssignmentGraphsMethod } from './decision-assignment-graphs.ts';
import { decisionAssignmentGraphMethod } from './decision-assignment-graph.ts';
import { deliverableManifestMethod } from './deliverable-manifest.ts';
import { decisionCapacityPlansMethod } from './decision-capacity-plans.ts';
import { createDecisionCapacityPlanMethod } from './create-decision-capacity-plan.ts';
import { capacityPlanMethod } from './capacity-plan.ts';
import { acceptCapacityPlanMethod } from './accept-capacity-plan.ts';
import { requestCapacityPlanRevisionMethod } from './request-capacity-plan-revision.ts';
import { scheduleCapacityPlanMethod } from './schedule-capacity-plan.ts';
import { supersedeCapacityPlanMethod } from './supersede-capacity-plan.ts';
import { createWorkdayMethod } from './create-workday.ts';
import { workdayMethod } from './workday.ts';
import { startWorkdayMethod } from './start-workday.ts';
import { pauseWorkdayMethod } from './pause-workday.ts';
import { resumeWorkdayMethod } from './resume-workday.ts';
import { cancelWorkdayMethod } from './cancel-workday.ts';
import { completeWorkdayMethod } from './complete-workday.ts';
import { workdaySummaryMethod } from './workday-summary.ts';
import { workdayRunsMethod } from './workday-runs.ts';
import { createWorkdayRunMethod } from './create-workday-run.ts';
import { workdayRunMethod } from './workday-run.ts';
import { updateWorkdayRunMethod } from './update-workday-run.ts';
import { tickWorkdayRunMethod } from './tick-workday-run.ts';
import { createResearchWorkflowMethod } from './create-research-workflow.ts';
import { researchWorkflowMethod } from './research-workflow.ts';
import { cancelCapacityAssignmentMethod } from './cancel-capacity-assignment.ts';
import { requeueCapacityAssignmentMethod } from './requeue-capacity-assignment.ts';
import { decideCapacityOverrunMethod } from './decide-capacity-overrun.ts';
import { workdayEventsMethod } from './workday-events.ts';
import { createWorkdayEventMethod } from './create-workday-event.ts';
import { planSeedMethod } from './plan-seed.ts';
import { applySeedMethod } from './apply-seed.ts';
import { listSeedRunsMethod } from './list-seed-runs.ts';
import { exportSeedMethod } from './export-seed.ts';
import { catalogMethod } from './catalog.ts';
import { artifactDownloadMethod } from './artifact-download.ts';

export function installMarketClientMethods(prototype: MarketClient) {
	prototype.request = requestMethod;
	prototype.localAuthPaths = localAuthPathsMethod;
	prototype.requestFirst = requestFirstMethod;
	prototype.startDeviceLogin = startDeviceLoginMethod;
	prototype.pollDeviceLogin = pollDeviceLoginMethod;
	prototype.refreshToken = refreshTokenMethod;
	prototype.logout = logoutMethod;
	prototype.webSignUp = webSignUpMethod;
	prototype.webSignIn = webSignInMethod;
	prototype.confirmWebEmail = confirmWebEmailMethod;
	prototype.checkWebUsername = checkWebUsernameMethod;
	prototype.checkWebEmail = checkWebEmailMethod;
	prototype.authProviders = authProvidersMethod;
	prototype.accountIdentity = accountIdentityMethod;
	prototype.webEmails = webEmailsMethod;
	prototype.addWebEmail = addWebEmailMethod;
	prototype.verifyWebEmail = verifyWebEmailMethod;
	prototype.setPrimaryWebEmail = setPrimaryWebEmailMethod;
	prototype.deleteWebEmail = deleteWebEmailMethod;
	prototype.webSessions = webSessionsMethod;
	prototype.revokeWebSession = revokeWebSessionMethod;
	prototype.updateWebProfile = updateWebProfileMethod;
	prototype.webAppearance = webAppearanceMethod;
	prototype.updateWebAppearance = updateWebAppearanceMethod;
	prototype.updateWebPassword = updateWebPasswordMethod;
	prototype.requestWebPasswordReset = requestWebPasswordResetMethod;
	prototype.completeWebPasswordReset = completeWebPasswordResetMethod;
	prototype.accountDeletionBlockers = accountDeletionBlockersMethod;
	prototype.deleteAccount = deleteAccountMethod;
	prototype.webNotificationPreferences = webNotificationPreferencesMethod;
	prototype.updateWebNotificationPreferences = updateWebNotificationPreferencesMethod;
	prototype.webNotifications = webNotificationsMethod;
	prototype.markWebNotificationRead = markWebNotificationReadMethod;
	prototype.personalThemes = personalThemesMethod;
	prototype.createPersonalTheme = createPersonalThemeMethod;
	prototype.updatePersonalTheme = updatePersonalThemeMethod;
	prototype.deletePersonalTheme = deletePersonalThemeMethod;
	prototype.me = meMethod;
	prototype.markets = marketsMethod;
	prototype.currentMarket = currentMarketMethod;
	prototype.teams = teamsMethod;
	prototype.createTeam = createTeamMethod;
	prototype.deleteTeam = deleteTeamMethod;
	prototype.teamDeletionBlockers = teamDeletionBlockersMethod;
	prototype.teamMembers = teamMembersMethod;
	prototype.teamPermissions = teamPermissionsMethod;
	prototype.projects = projectsMethod;
	prototype.createProject = createProjectMethod;
	prototype.deleteProject = deleteProjectMethod;
	prototype.projectDeletionBlockers = projectDeletionBlockersMethod;
	prototype.projectAccess = projectAccessMethod;
	prototype.upsertProjectConnection = upsertProjectConnectionMethod;
	prototype.projectHosts = projectHostsMethod;
	prototype.projectSecretEscrowRecords = projectSecretEscrowRecordsMethod;
	prototype.createProjectSecretEscrow = createProjectSecretEscrowMethod;
	prototype.projectSecretEscrow = projectSecretEscrowMethod;
	prototype.updateProjectSecretEscrow = updateProjectSecretEscrowMethod;
	prototype.migrateProjectSecretEscrow = migrateProjectSecretEscrowMethod;
	prototype.tombstoneProjectSecretEscrow = tombstoneProjectSecretEscrowMethod;
	prototype.projectGitHubActionsSecretPublicKey = projectGitHubActionsSecretPublicKeyMethod;
	prototype.deployProjectGitHubActionsSecret = deployProjectGitHubActionsSecretMethod;
	prototype.dispatchProjectWorkflowOperation = dispatchProjectWorkflowOperationMethod;
	prototype.teamTreeDx = teamTreeDxMethod;
	prototype.updateTeamTreeDx = updateTeamTreeDxMethod;
	prototype.provisionTeamTreeDx = provisionTeamTreeDxMethod;
	prototype.treeDxMirrors = treeDxMirrorsMethod;
	prototype.createTreeDxMirror = createTreeDxMirrorMethod;
	prototype.syncTreeDxMirror = syncTreeDxMirrorMethod;
	prototype.treeDxShares = treeDxSharesMethod;
	prototype.createTreeDxShare = createTreeDxShareMethod;
	prototype.projectTreeDxLibrary = projectTreeDxLibraryMethod;
	prototype.upsertProjectTreeDxLibrary = upsertProjectTreeDxLibraryMethod;
	prototype.projectRepositoryTopology = projectRepositoryTopologyMethod;
	prototype.projectTreeDxProxyAudit = projectTreeDxProxyAuditMethod;
	prototype.projectAgentFallbackOutputs = projectAgentFallbackOutputsMethod;
	prototype.treeDxBuildContext = treeDxBuildContextMethod;
	prototype.treeDxReadRepositoryFiles = treeDxReadRepositoryFilesMethod;
	prototype.createTreeDxWorkspace = createTreeDxWorkspaceMethod;
	prototype.updateProjectRepositoryTopology = updateProjectRepositoryTopologyMethod;
	prototype.initializeProjectRepository = initializeProjectRepositoryMethod;
	prototype.importProjectRepository = importProjectRepositoryMethod;
	prototype.auditProjectHosts = auditProjectHostsMethod;
	prototype.replaceProjectHost = replaceProjectHostMethod;
	prototype.resyncProjectHost = resyncProjectHostMethod;
	prototype.rotateProjectHost = rotateProjectHostMethod;
	prototype.projectDeploymentState = projectDeploymentStateMethod;
	prototype.projectDeployments = projectDeploymentsMethod;
	prototype.projectDeployment = projectDeploymentMethod;
	prototype.projectDeploymentById = projectDeploymentByIdMethod;
	prototype.projectDeploymentEvents = projectDeploymentEventsMethod;
	prototype.createProjectWebDeployment = createProjectWebDeploymentMethod;
	prototype.retryProjectDeployment = retryProjectDeploymentMethod;
	prototype.resumeProjectDeployment = resumeProjectDeploymentMethod;
	prototype.cancelProjectDeployment = cancelProjectDeploymentMethod;
	prototype.teamCapacityRegistrationKey = teamCapacityRegistrationKeyMethod;
	prototype.revealTeamCapacityRegistrationKey = revealTeamCapacityRegistrationKeyMethod;
	prototype.rotateTeamCapacityRegistrationKey = rotateTeamCapacityRegistrationKeyMethod;
	prototype.enableTeamCapacityRegistrationKey = enableTeamCapacityRegistrationKeyMethod;
	prototype.disableTeamCapacityRegistrationKey = disableTeamCapacityRegistrationKeyMethod;
	prototype.updateTeamCapacityRegistrationKeyStatus = updateTeamCapacityRegistrationKeyStatusMethod;
	prototype.capacityProviderRegistrationRequests = capacityProviderRegistrationRequestsMethod;
	prototype.capacityProviderRegistrationRequest = capacityProviderRegistrationRequestMethod;
	prototype.reviewCapacityProviderRegistration = reviewCapacityProviderRegistrationMethod;
	prototype.capacityProviderMemberships = capacityProviderMembershipsMethod;
	prototype.capacityProviderMembership = capacityProviderMembershipMethod;
	prototype.capacityAuditEvents = capacityAuditEventsMethod;
	prototype.capacityProviderCredentials = capacityProviderCredentialsMethod;
	prototype.authorizeCapacityProviderCredentialRotation = authorizeCapacityProviderCredentialRotationMethod;
	prototype.revokeCapacityProviderCredential = revokeCapacityProviderCredentialMethod;
	prototype.suspendCapacityProviderMembership = suspendCapacityProviderMembershipMethod;
	prototype.resumeCapacityProviderMembership = resumeCapacityProviderMembershipMethod;
	prototype.revokeCapacityProviderMembership = revokeCapacityProviderMembershipMethod;
	prototype.updateCapacityProviderMembershipStatus = updateCapacityProviderMembershipStatusMethod;
	prototype.capacityGrants = capacityGrantsMethod;
	prototype.capacityGrant = capacityGrantMethod;
	prototype.planCapacityGrant = planCapacityGrantMethod;
	prototype.createCapacityGrant = createCapacityGrantMethod;
	prototype.transitionCapacityGrant = transitionCapacityGrantMethod;
	prototype.capacityAllocationSets = capacityAllocationSetsMethod;
	prototype.createCapacityAllocationSet = createCapacityAllocationSetMethod;
	prototype.planCapacityAllocationSet = planCapacityAllocationSetMethod;
	prototype.capacityAllocationSet = capacityAllocationSetMethod;
	prototype.activateCapacityAllocationSet = activateCapacityAllocationSetMethod;
	prototype.supersedeCapacityAllocationSet = supersedeCapacityAllocationSetMethod;
	prototype.archiveCapacityAllocationSet = archiveCapacityAllocationSetMethod;
	prototype.explainCapacityAllocationSet = explainCapacityAllocationSetMethod;
	prototype.providerAvailabilitySessions = providerAvailabilitySessionsMethod;
	prototype.capacityProviderAssignments = capacityProviderAssignmentsMethod;
	prototype.executionRuns = executionRunsMethod;
	prototype.admitCapacityAssignment = admitCapacityAssignmentMethod;
	prototype.providerAssignmentExplanation = providerAssignmentExplanationMethod;
	prototype.capacityProviderAssignment = capacityProviderAssignmentMethod;
	prototype.capacityReservations = capacityReservationsMethod;
	prototype.capacityReservationExplanation = capacityReservationExplanationMethod;
	prototype.capacityUsage = capacityUsageMethod;
	prototype.capacityLedger = capacityLedgerMethod;
	prototype.capacityEvidencePage = capacityEvidencePageMethod;
	prototype.projectCapacityDiagnostics = projectCapacityDiagnosticsMethod;
	prototype.projectAgentClasses = projectAgentClassesMethod;
	prototype.createProjectAgentClass = createProjectAgentClassMethod;
	prototype.projectAgentClass = projectAgentClassMethod;
	prototype.updateProjectAgentClass = updateProjectAgentClassMethod;
	prototype.projectAgentModeRuns = projectAgentModeRunsMethod;
	prototype.projectCapacityRuntimeDiagnostics = projectCapacityRuntimeDiagnosticsMethod;
	prototype.decisionPlanningStatus = decisionPlanningStatusMethod;
	prototype.createPlanningInputRequest = createPlanningInputRequestMethod;
	prototype.decisionStructuredEstimates = decisionStructuredEstimatesMethod;
	prototype.createStructuredAgentEstimate = createStructuredAgentEstimateMethod;
	prototype.acceptStructuredAgentEstimate = acceptStructuredAgentEstimateMethod;
	prototype.decisionExecutionInputs = decisionExecutionInputsMethod;
	prototype.createDecisionExecutionInput = createDecisionExecutionInputMethod;
	prototype.acceptDecisionExecutionInput = acceptDecisionExecutionInputMethod;
	prototype.requestDecisionExecutionInputRevision = requestDecisionExecutionInputRevisionMethod;
	prototype.decisionAssignmentGraphs = decisionAssignmentGraphsMethod;
	prototype.decisionAssignmentGraph = decisionAssignmentGraphMethod;
	prototype.deliverableManifest = deliverableManifestMethod;
	prototype.decisionCapacityPlans = decisionCapacityPlansMethod;
	prototype.createDecisionCapacityPlan = createDecisionCapacityPlanMethod;
	prototype.capacityPlan = capacityPlanMethod;
	prototype.acceptCapacityPlan = acceptCapacityPlanMethod;
	prototype.requestCapacityPlanRevision = requestCapacityPlanRevisionMethod;
	prototype.scheduleCapacityPlan = scheduleCapacityPlanMethod;
	prototype.supersedeCapacityPlan = supersedeCapacityPlanMethod;
	prototype.createWorkday = createWorkdayMethod;
	prototype.workday = workdayMethod;
	prototype.startWorkday = startWorkdayMethod;
	prototype.pauseWorkday = pauseWorkdayMethod;
	prototype.resumeWorkday = resumeWorkdayMethod;
	prototype.cancelWorkday = cancelWorkdayMethod;
	prototype.completeWorkday = completeWorkdayMethod;
	prototype.workdaySummary = workdaySummaryMethod;
	prototype.workdayRuns = workdayRunsMethod;
	prototype.createWorkdayRun = createWorkdayRunMethod;
	prototype.workdayRun = workdayRunMethod;
	prototype.updateWorkdayRun = updateWorkdayRunMethod;
	prototype.tickWorkdayRun = tickWorkdayRunMethod;
	prototype.createResearchWorkflow = createResearchWorkflowMethod;
	prototype.researchWorkflow = researchWorkflowMethod;
	prototype.cancelCapacityAssignment = cancelCapacityAssignmentMethod;
	prototype.requeueCapacityAssignment = requeueCapacityAssignmentMethod;
	prototype.decideCapacityOverrun = decideCapacityOverrunMethod;
	prototype.workdayEvents = workdayEventsMethod;
	prototype.createWorkdayEvent = createWorkdayEventMethod;
	prototype.planSeed = planSeedMethod;
	prototype.applySeed = applySeedMethod;
	prototype.listSeedRuns = listSeedRunsMethod;
	prototype.exportSeed = exportSeedMethod;
	prototype.catalog = catalogMethod;
	prototype.artifactDownload = artifactDownloadMethod;
}
