import type { MarketClient } from '../entrypoints/clients/market-client.ts';
import { requestMethod } from './support/preferences/request.ts';
import { localAuthPathsMethod } from './accounts/contracts/local-auth-paths.ts';
import { requestFirstMethod } from './support/creation/request-first.ts';
import { startDeviceLoginMethod } from './accounts/creation/start-device-login.ts';
import { pollDeviceLoginMethod } from './accounts/contracts/poll-device-login.ts';
import { refreshTokenMethod } from './accounts/updates/refresh-token.ts';
import { logoutMethod } from './accounts/contracts/logout.ts';
import { webSignUpMethod } from './support/identity/web-sign-up.ts';
import { webSignInMethod } from './support/identity/web-sign-in.ts';
import { confirmWebEmailMethod } from './accounts/lifecycle/confirm-web-email.ts';
import { checkWebUsernameMethod } from './accounts/queries/check-web-username.ts';
import { checkWebEmailMethod } from './accounts/queries/check-web-email.ts';
import { authProvidersMethod } from './capacity/providers/contracts/auth-providers.ts';
import { accountIdentityMethod } from './accounts/contracts/account-identity.ts';
import { webEmailsMethod } from './accounts/contracts/web-emails.ts';
import { addWebEmailMethod } from './accounts/creation/add-web-email.ts';
import { verifyWebEmailMethod } from './accounts/lifecycle/verify-web-email.ts';
import { setPrimaryWebEmailMethod } from './accounts/updates/set-primary-web-email.ts';
import { deleteWebEmailMethod } from './accounts/retirement/delete-web-email.ts';
import { webSessionsMethod } from './accounts/contracts/web-sessions.ts';
import { revokeWebSessionMethod } from './accounts/retirement/revoke-web-session.ts';
import { updateWebProfileMethod } from './support/updates/update-web-profile.ts';
import { webAppearanceMethod } from './accounts/contracts/web-appearance.ts';
import { updateWebAppearanceMethod } from './accounts/updates/update-web-appearance.ts';
import { updateWebPasswordMethod } from './accounts/updates/update-web-password.ts';
import { requestWebPasswordResetMethod } from './accounts/creation/request-web-password-reset.ts';
import { completeWebPasswordResetMethod } from './accounts/lifecycle/complete-web-password-reset.ts';
import { accountDeletionBlockersMethod } from './accounts/contracts/account-deletion-blockers.ts';
import { deleteAccountMethod } from './accounts/retirement/delete-account.ts';
import { webNotificationPreferencesMethod } from './accounts/contracts/web-notification-preferences.ts';
import { updateWebNotificationPreferencesMethod } from './accounts/updates/update-web-notification-preferences.ts';
import { webNotificationsMethod } from './accounts/contracts/web-notifications.ts';
import { markWebNotificationReadMethod } from './accounts/updates/mark-web-notification-read.ts';
import { personalThemesMethod } from './support/identity/personal-themes.ts';
import { createPersonalThemeMethod } from './support/creation/create-personal-theme.ts';
import { updatePersonalThemeMethod } from './support/updates/update-personal-theme.ts';
import { deletePersonalThemeMethod } from './support/retirement/delete-personal-theme.ts';
import { meMethod } from './support/identity/me.ts';
import { marketsMethod } from './support/identity/markets.ts';
import { currentMarketMethod } from './support/queries/current-market.ts';
import { teamsMethod } from './teams/contracts/teams.ts';
import { createTeamMethod } from './teams/creation/create-team.ts';
import { deleteTeamMethod } from './teams/retirement/delete-team.ts';
import { teamDeletionBlockersMethod } from './teams/contracts/team-deletion-blockers.ts';
import { teamMembersMethod } from './teams/contracts/team-members.ts';
import { teamPermissionsMethod } from './teams/contracts/team-permissions.ts';
import { projectsMethod } from './projects/projects-core/contracts/projects.ts';
import { createProjectMethod } from './projects/projects-core/creation/create-project.ts';
import { deleteProjectMethod } from './projects/projects-core/retirement/delete-project.ts';
import { projectDeletionBlockersMethod } from './projects/projects-core/contracts/project-deletion-blockers.ts';
import { projectAccessMethod } from './projects/access/contracts/project-access.ts';
import { upsertProjectConnectionMethod } from './projects/projects-core/creation/upsert-project-connection.ts';
import { projectHostsMethod } from './projects/hosting/contracts/project-hosts.ts';
import { projectSecretEscrowRecordsMethod } from './projects/secrets/contracts/project-secret-escrow-records.ts';
import { createProjectSecretEscrowMethod } from './projects/secrets/creation/create-project-secret-escrow.ts';
import { projectSecretEscrowMethod } from './projects/secrets/contracts/project-secret-escrow.ts';
import { updateProjectSecretEscrowMethod } from './projects/secrets/updates/update-project-secret-escrow.ts';
import { migrateProjectSecretEscrowMethod } from './projects/secrets/updates/migrate-project-secret-escrow.ts';
import { tombstoneProjectSecretEscrowMethod } from './projects/secrets/retirement/tombstone-project-secret-escrow.ts';
import { projectGitHubActionsSecretPublicKeyMethod } from './projects/secrets/contracts/project-git-hub-actions-secret-public-key.ts';
import { deployProjectGitHubActionsSecretMethod } from './projects/secrets/contracts/deploy-project-git-hub-actions-secret.ts';
import { dispatchProjectWorkflowOperationMethod } from './projects/projects-core/contracts/dispatch-project-workflow-operation.ts';
import { teamTreeDxMethod } from './treedx/repositories/contracts/team-tree-dx.ts';
import { updateTeamTreeDxMethod } from './treedx/repositories/updates/update-team-tree-dx.ts';
import { provisionTeamTreeDxMethod } from './treedx/repositories/creation/provision-team-tree-dx.ts';
import { treeDxMirrorsMethod } from './treedx/repositories/contracts/tree-dx-mirrors.ts';
import { createTreeDxMirrorMethod } from './treedx/repositories/creation/create-tree-dx-mirror.ts';
import { syncTreeDxMirrorMethod } from './treedx/repositories/updates/sync-tree-dx-mirror.ts';
import { treeDxSharesMethod } from './treedx/repositories/contracts/tree-dx-shares.ts';
import { createTreeDxShareMethod } from './treedx/repositories/creation/create-tree-dx-share.ts';
import { projectTreeDxLibraryMethod } from './projects/knowledge/contracts/project-tree-dx-library.ts';
import { upsertProjectTreeDxLibraryMethod } from './projects/knowledge/creation/upsert-project-tree-dx-library.ts';
import { projectRepositoryTopologyMethod } from './projects/repositories/contracts/project-repository-topology.ts';
import { projectTreeDxProxyAuditMethod } from './projects/knowledge/contracts/project-tree-dx-proxy-audit.ts';
import { projectAgentFallbackOutputsMethod } from './projects/agents/contracts/project-agent-fallback-outputs.ts';
import { treeDxBuildContextMethod } from './treedx/graph/contracts/tree-dx-build-context.ts';
import { treeDxReadRepositoryFilesMethod } from './treedx/repositories/contracts/tree-dx-read-repository-files.ts';
import { createTreeDxWorkspaceMethod } from './treedx/repositories/creation/create-tree-dx-workspace.ts';
import { updateProjectRepositoryTopologyMethod } from './projects/repositories/updates/update-project-repository-topology.ts';
import { initializeProjectRepositoryMethod } from './projects/repositories/creation/initialize-project-repository.ts';
import { importProjectRepositoryMethod } from './projects/repositories/creation/import-project-repository.ts';
import { auditProjectHostsMethod } from './projects/hosting/queries/audit-project-hosts.ts';
import { replaceProjectHostMethod } from './projects/hosting/updates/replace-project-host.ts';
import { resyncProjectHostMethod } from './projects/hosting/contracts/resync-project-host.ts';
import { rotateProjectHostMethod } from './projects/hosting/updates/rotate-project-host.ts';
import { projectDeploymentStateMethod } from './projects/deployments/contracts/project-deployment-state.ts';
import { projectDeploymentsMethod } from './projects/deployments/contracts/project-deployments.ts';
import { projectDeploymentMethod } from './projects/deployments/contracts/project-deployment.ts';
import { projectDeploymentByIdMethod } from './projects/deployments/contracts/project-deployment-by-id.ts';
import { projectDeploymentEventsMethod } from './projects/deployments/contracts/project-deployment-events.ts';
import { createProjectWebDeploymentMethod } from './projects/deployments/creation/create-project-web-deployment.ts';
import { retryProjectDeploymentMethod } from './projects/deployments/lifecycle/retry-project-deployment.ts';
import { resumeProjectDeploymentMethod } from './projects/deployments/lifecycle/resume-project-deployment.ts';
import { cancelProjectDeploymentMethod } from './projects/deployments/retirement/cancel-project-deployment.ts';
import { teamCapacityRegistrationKeyMethod } from './capacity/admission/contracts/team-capacity-registration-key.ts';
import { revealTeamCapacityRegistrationKeyMethod } from './capacity/admission/lifecycle/reveal-team-capacity-registration-key.ts';
import { rotateTeamCapacityRegistrationKeyMethod } from './capacity/admission/updates/rotate-team-capacity-registration-key.ts';
import { enableTeamCapacityRegistrationKeyMethod } from './capacity/admission/lifecycle/enable-team-capacity-registration-key.ts';
import { disableTeamCapacityRegistrationKeyMethod } from './capacity/admission/retirement/disable-team-capacity-registration-key.ts';
import { updateTeamCapacityRegistrationKeyStatusMethod } from './capacity/admission/updates/update-team-capacity-registration-key-status.ts';
import { capacityProviderRegistrationRequestsMethod } from './capacity/providers/contracts/capacity-provider-registration-requests.ts';
import { capacityProviderRegistrationRequestMethod } from './capacity/providers/contracts/capacity-provider-registration-request.ts';
import { reviewCapacityProviderRegistrationMethod } from './capacity/providers/lifecycle/review-capacity-provider-registration.ts';
import { capacityProviderMembershipsMethod } from './capacity/providers/contracts/capacity-provider-memberships.ts';
import { capacityProviderMembershipMethod } from './capacity/providers/contracts/capacity-provider-membership.ts';
import { capacityAuditEventsMethod } from './capacity/capacity-core/contracts/capacity-audit-events.ts';
import { capacityProviderCredentialsMethod } from './capacity/providers/contracts/capacity-provider-credentials.ts';
import { authorizeCapacityProviderCredentialRotationMethod } from './capacity/providers/lifecycle/authorize-capacity-provider-credential-rotation.ts';
import { revokeCapacityProviderCredentialMethod } from './capacity/providers/retirement/revoke-capacity-provider-credential.ts';
import { suspendCapacityProviderMembershipMethod } from './capacity/providers/retirement/suspend-capacity-provider-membership.ts';
import { resumeCapacityProviderMembershipMethod } from './capacity/providers/lifecycle/resume-capacity-provider-membership.ts';
import { revokeCapacityProviderMembershipMethod } from './capacity/providers/retirement/revoke-capacity-provider-membership.ts';
import { updateCapacityProviderMembershipStatusMethod } from './capacity/providers/updates/update-capacity-provider-membership-status.ts';
import { capacityGrantsMethod } from './capacity/allocations/contracts/capacity-grants.ts';
import { capacityGrantMethod } from './capacity/allocations/contracts/capacity-grant.ts';
import { planCapacityGrantMethod } from './capacity/allocations/creation/plan-capacity-grant.ts';
import { createCapacityGrantMethod } from './capacity/allocations/creation/create-capacity-grant.ts';
import { transitionCapacityGrantMethod } from './capacity/allocations/updates/transition-capacity-grant.ts';
import { capacityAllocationSetsMethod } from './capacity/allocations/contracts/capacity-allocation-sets.ts';
import { createCapacityAllocationSetMethod } from './capacity/allocations/creation/create-capacity-allocation-set.ts';
import { planCapacityAllocationSetMethod } from './capacity/allocations/creation/plan-capacity-allocation-set.ts';
import { capacityAllocationSetMethod } from './capacity/allocations/contracts/capacity-allocation-set.ts';
import { activateCapacityAllocationSetMethod } from './capacity/allocations/lifecycle/activate-capacity-allocation-set.ts';
import { supersedeCapacityAllocationSetMethod } from './capacity/allocations/updates/supersede-capacity-allocation-set.ts';
import { archiveCapacityAllocationSetMethod } from './capacity/allocations/retirement/archive-capacity-allocation-set.ts';
import { explainCapacityAllocationSetMethod } from './capacity/allocations/queries/explain-capacity-allocation-set.ts';
import { providerAvailabilitySessionsMethod } from './capacity/providers/contracts/provider-availability-sessions.ts';
import { capacityProviderAssignmentsMethod } from './capacity/assignments/contracts/capacity-provider-assignments.ts';
import { executionRunsMethod } from './support/planning/execution-runs.ts';
import { admitCapacityAssignmentMethod } from './capacity/assignments/lifecycle/admit-capacity-assignment.ts';
import { providerAssignmentExplanationMethod } from './capacity/assignments/contracts/provider-assignment-explanation.ts';
import { capacityProviderAssignmentMethod } from './capacity/assignments/contracts/capacity-provider-assignment.ts';
import { capacityReservationsMethod } from './capacity/accounting/contracts/capacity-reservations.ts';
import { capacityReservationExplanationMethod } from './capacity/accounting/contracts/capacity-reservation-explanation.ts';
import { capacityUsageMethod } from './capacity/accounting/contracts/capacity-usage.ts';
import { capacityLedgerMethod } from './capacity/accounting/contracts/capacity-ledger.ts';
import { capacityEvidencePageMethod } from './capacity/observability/contracts/capacity-evidence-page.ts';
import { projectCapacityDiagnosticsMethod } from './capacity/observability/contracts/project-capacity-diagnostics.ts';
import { projectAgentClassesMethod } from './projects/agents/contracts/project-agent-classes.ts';
import { createProjectAgentClassMethod } from './projects/agents/creation/create-project-agent-class.ts';
import { projectAgentClassMethod } from './projects/agents/contracts/project-agent-class.ts';
import { updateProjectAgentClassMethod } from './projects/agents/updates/update-project-agent-class.ts';
import { projectAgentModeRunsMethod } from './projects/agents/contracts/project-agent-mode-runs.ts';
import { projectCapacityRuntimeDiagnosticsMethod } from './capacity/observability/contracts/project-capacity-runtime-diagnostics.ts';
import { decisionPlanningStatusMethod } from './support/planning/decision-planning-status.ts';
import { createPlanningInputRequestMethod } from './support/creation/create-planning-input-request.ts';
import { decisionStructuredEstimatesMethod } from './support/planning/decision-structured-estimates.ts';
import { createStructuredAgentEstimateMethod } from './agents/creation/create-structured-agent-estimate.ts';
import { acceptStructuredAgentEstimateMethod } from './agents/lifecycle/accept-structured-agent-estimate.ts';
import { decisionExecutionInputsMethod } from './support/planning/decision-execution-inputs.ts';
import { createDecisionExecutionInputMethod } from './support/creation/create-decision-execution-input.ts';
import { acceptDecisionExecutionInputMethod } from './support/lifecycle/accept-decision-execution-input.ts';
import { requestDecisionExecutionInputRevisionMethod } from './support/creation/request-decision-execution-input-revision.ts';
import { decisionAssignmentGraphsMethod } from './capacity/assignments/contracts/decision-assignment-graphs.ts';
import { decisionAssignmentGraphMethod } from './capacity/assignments/contracts/decision-assignment-graph.ts';
import { deliverableManifestMethod } from './support/delivery/deliverable-manifest.ts';
import { decisionCapacityPlansMethod } from './capacity/planning/contracts/decision-capacity-plans.ts';
import { createDecisionCapacityPlanMethod } from './capacity/planning/creation/create-decision-capacity-plan.ts';
import { capacityPlanMethod } from './capacity/planning/contracts/capacity-plan.ts';
import { acceptCapacityPlanMethod } from './capacity/planning/lifecycle/accept-capacity-plan.ts';
import { requestCapacityPlanRevisionMethod } from './capacity/planning/creation/request-capacity-plan-revision.ts';
import { scheduleCapacityPlanMethod } from './capacity/planning/lifecycle/schedule-capacity-plan.ts';
import { supersedeCapacityPlanMethod } from './capacity/planning/updates/supersede-capacity-plan.ts';
import { createWorkdayMethod } from './capacity/workdays/creation/create-workday.ts';
import { workdayMethod } from './capacity/workdays/contracts/workday.ts';
import { startWorkdayMethod } from './capacity/workdays/creation/start-workday.ts';
import { pauseWorkdayMethod } from './capacity/workdays/lifecycle/pause-workday.ts';
import { resumeWorkdayMethod } from './capacity/workdays/lifecycle/resume-workday.ts';
import { cancelWorkdayMethod } from './capacity/workdays/retirement/cancel-workday.ts';
import { completeWorkdayMethod } from './capacity/workdays/lifecycle/complete-workday.ts';
import { workdaySummaryMethod } from './capacity/workdays/contracts/workday-summary.ts';
import { workdayRunsMethod } from './capacity/workdays/contracts/workday-runs.ts';
import { createWorkdayRunMethod } from './capacity/workdays/creation/create-workday-run.ts';
import { workdayRunMethod } from './capacity/workdays/contracts/workday-run.ts';
import { updateWorkdayRunMethod } from './capacity/workdays/updates/update-workday-run.ts';
import { tickWorkdayRunMethod } from './capacity/workdays/lifecycle/tick-workday-run.ts';
import { createResearchWorkflowMethod } from './operations/creation/create-research-workflow.ts';
import { researchWorkflowMethod } from './operations/contracts/research-workflow.ts';
import { cancelCapacityAssignmentMethod } from './capacity/assignments/retirement/cancel-capacity-assignment.ts';
import { requeueCapacityAssignmentMethod } from './capacity/assignments/lifecycle/requeue-capacity-assignment.ts';
import { decideCapacityOverrunMethod } from './capacity/accounting/lifecycle/decide-capacity-overrun.ts';
import { workdayEventsMethod } from './capacity/workdays/contracts/workday-events.ts';
import { createWorkdayEventMethod } from './capacity/workdays/creation/create-workday-event.ts';
import { planSeedMethod } from './seeds/creation/plan-seed.ts';
import { applySeedMethod } from './seeds/creation/apply-seed.ts';
import { listSeedRunsMethod } from './seeds/queries/list-seed-runs.ts';
import { exportSeedMethod } from './seeds/creation/export-seed.ts';
import { catalogMethod } from './commerce/catalog/contracts/catalog.ts';
import { artifactDownloadMethod } from './support/delivery/artifact-download.ts';

export function installMarketClientMethods(prototype: MarketClient) {
	prototype.request = requestMethod;
	prototype.localAuthPaths = localAuthPathsMethod;
	prototype.requestFirst = requestFirstMethod;
	prototype.startDeviceLogin = startDeviceLoginMethod;
	prototype.pollDeviceLogin = pollDeviceLoginMethod;
	prototype.refreshToken = refreshTokenMethod;
	prototype.logout = logoutMethod;
	prototype.webSignUp = webSignUpMethod;
	prototype.webSignIn = webSignInMethod;
	prototype.confirmWebEmail = confirmWebEmailMethod;
	prototype.checkWebUsername = checkWebUsernameMethod;
	prototype.checkWebEmail = checkWebEmailMethod;
	prototype.authProviders = authProvidersMethod;
	prototype.accountIdentity = accountIdentityMethod;
	prototype.webEmails = webEmailsMethod;
	prototype.addWebEmail = addWebEmailMethod;
	prototype.verifyWebEmail = verifyWebEmailMethod;
	prototype.setPrimaryWebEmail = setPrimaryWebEmailMethod;
	prototype.deleteWebEmail = deleteWebEmailMethod;
	prototype.webSessions = webSessionsMethod;
	prototype.revokeWebSession = revokeWebSessionMethod;
	prototype.updateWebProfile = updateWebProfileMethod;
	prototype.webAppearance = webAppearanceMethod;
	prototype.updateWebAppearance = updateWebAppearanceMethod;
	prototype.updateWebPassword = updateWebPasswordMethod;
	prototype.requestWebPasswordReset = requestWebPasswordResetMethod;
	prototype.completeWebPasswordReset = completeWebPasswordResetMethod;
	prototype.accountDeletionBlockers = accountDeletionBlockersMethod;
	prototype.deleteAccount = deleteAccountMethod;
	prototype.webNotificationPreferences = webNotificationPreferencesMethod;
	prototype.updateWebNotificationPreferences = updateWebNotificationPreferencesMethod;
	prototype.webNotifications = webNotificationsMethod;
	prototype.markWebNotificationRead = markWebNotificationReadMethod;
	prototype.personalThemes = personalThemesMethod;
	prototype.createPersonalTheme = createPersonalThemeMethod;
	prototype.updatePersonalTheme = updatePersonalThemeMethod;
	prototype.deletePersonalTheme = deletePersonalThemeMethod;
	prototype.me = meMethod;
	prototype.markets = marketsMethod;
	prototype.currentMarket = currentMarketMethod;
	prototype.teams = teamsMethod;
	prototype.createTeam = createTeamMethod;
	prototype.deleteTeam = deleteTeamMethod;
	prototype.teamDeletionBlockers = teamDeletionBlockersMethod;
	prototype.teamMembers = teamMembersMethod;
	prototype.teamPermissions = teamPermissionsMethod;
	prototype.projects = projectsMethod;
	prototype.createProject = createProjectMethod;
	prototype.deleteProject = deleteProjectMethod;
	prototype.projectDeletionBlockers = projectDeletionBlockersMethod;
	prototype.projectAccess = projectAccessMethod;
	prototype.upsertProjectConnection = upsertProjectConnectionMethod;
	prototype.projectHosts = projectHostsMethod;
	prototype.projectSecretEscrowRecords = projectSecretEscrowRecordsMethod;
	prototype.createProjectSecretEscrow = createProjectSecretEscrowMethod;
	prototype.projectSecretEscrow = projectSecretEscrowMethod;
	prototype.updateProjectSecretEscrow = updateProjectSecretEscrowMethod;
	prototype.migrateProjectSecretEscrow = migrateProjectSecretEscrowMethod;
	prototype.tombstoneProjectSecretEscrow = tombstoneProjectSecretEscrowMethod;
	prototype.projectGitHubActionsSecretPublicKey = projectGitHubActionsSecretPublicKeyMethod;
	prototype.deployProjectGitHubActionsSecret = deployProjectGitHubActionsSecretMethod;
	prototype.dispatchProjectWorkflowOperation = dispatchProjectWorkflowOperationMethod;
	prototype.teamTreeDx = teamTreeDxMethod;
	prototype.updateTeamTreeDx = updateTeamTreeDxMethod;
	prototype.provisionTeamTreeDx = provisionTeamTreeDxMethod;
	prototype.treeDxMirrors = treeDxMirrorsMethod;
	prototype.createTreeDxMirror = createTreeDxMirrorMethod;
	prototype.syncTreeDxMirror = syncTreeDxMirrorMethod;
	prototype.treeDxShares = treeDxSharesMethod;
	prototype.createTreeDxShare = createTreeDxShareMethod;
	prototype.projectTreeDxLibrary = projectTreeDxLibraryMethod;
	prototype.upsertProjectTreeDxLibrary = upsertProjectTreeDxLibraryMethod;
	prototype.projectRepositoryTopology = projectRepositoryTopologyMethod;
	prototype.projectTreeDxProxyAudit = projectTreeDxProxyAuditMethod;
	prototype.projectAgentFallbackOutputs = projectAgentFallbackOutputsMethod;
	prototype.treeDxBuildContext = treeDxBuildContextMethod;
	prototype.treeDxReadRepositoryFiles = treeDxReadRepositoryFilesMethod;
	prototype.createTreeDxWorkspace = createTreeDxWorkspaceMethod;
	prototype.updateProjectRepositoryTopology = updateProjectRepositoryTopologyMethod;
	prototype.initializeProjectRepository = initializeProjectRepositoryMethod;
	prototype.importProjectRepository = importProjectRepositoryMethod;
	prototype.auditProjectHosts = auditProjectHostsMethod;
	prototype.replaceProjectHost = replaceProjectHostMethod;
	prototype.resyncProjectHost = resyncProjectHostMethod;
	prototype.rotateProjectHost = rotateProjectHostMethod;
	prototype.projectDeploymentState = projectDeploymentStateMethod;
	prototype.projectDeployments = projectDeploymentsMethod;
	prototype.projectDeployment = projectDeploymentMethod;
	prototype.projectDeploymentById = projectDeploymentByIdMethod;
	prototype.projectDeploymentEvents = projectDeploymentEventsMethod;
	prototype.createProjectWebDeployment = createProjectWebDeploymentMethod;
	prototype.retryProjectDeployment = retryProjectDeploymentMethod;
	prototype.resumeProjectDeployment = resumeProjectDeploymentMethod;
	prototype.cancelProjectDeployment = cancelProjectDeploymentMethod;
	prototype.teamCapacityRegistrationKey = teamCapacityRegistrationKeyMethod;
	prototype.revealTeamCapacityRegistrationKey = revealTeamCapacityRegistrationKeyMethod;
	prototype.rotateTeamCapacityRegistrationKey = rotateTeamCapacityRegistrationKeyMethod;
	prototype.enableTeamCapacityRegistrationKey = enableTeamCapacityRegistrationKeyMethod;
	prototype.disableTeamCapacityRegistrationKey = disableTeamCapacityRegistrationKeyMethod;
	prototype.updateTeamCapacityRegistrationKeyStatus = updateTeamCapacityRegistrationKeyStatusMethod;
	prototype.capacityProviderRegistrationRequests = capacityProviderRegistrationRequestsMethod;
	prototype.capacityProviderRegistrationRequest = capacityProviderRegistrationRequestMethod;
	prototype.reviewCapacityProviderRegistration = reviewCapacityProviderRegistrationMethod;
	prototype.capacityProviderMemberships = capacityProviderMembershipsMethod;
	prototype.capacityProviderMembership = capacityProviderMembershipMethod;
	prototype.capacityAuditEvents = capacityAuditEventsMethod;
	prototype.capacityProviderCredentials = capacityProviderCredentialsMethod;
	prototype.authorizeCapacityProviderCredentialRotation = authorizeCapacityProviderCredentialRotationMethod;
	prototype.revokeCapacityProviderCredential = revokeCapacityProviderCredentialMethod;
	prototype.suspendCapacityProviderMembership = suspendCapacityProviderMembershipMethod;
	prototype.resumeCapacityProviderMembership = resumeCapacityProviderMembershipMethod;
	prototype.revokeCapacityProviderMembership = revokeCapacityProviderMembershipMethod;
	prototype.updateCapacityProviderMembershipStatus = updateCapacityProviderMembershipStatusMethod;
	prototype.capacityGrants = capacityGrantsMethod;
	prototype.capacityGrant = capacityGrantMethod;
	prototype.planCapacityGrant = planCapacityGrantMethod;
	prototype.createCapacityGrant = createCapacityGrantMethod;
	prototype.transitionCapacityGrant = transitionCapacityGrantMethod;
	prototype.capacityAllocationSets = capacityAllocationSetsMethod;
	prototype.createCapacityAllocationSet = createCapacityAllocationSetMethod;
	prototype.planCapacityAllocationSet = planCapacityAllocationSetMethod;
	prototype.capacityAllocationSet = capacityAllocationSetMethod;
	prototype.activateCapacityAllocationSet = activateCapacityAllocationSetMethod;
	prototype.supersedeCapacityAllocationSet = supersedeCapacityAllocationSetMethod;
	prototype.archiveCapacityAllocationSet = archiveCapacityAllocationSetMethod;
	prototype.explainCapacityAllocationSet = explainCapacityAllocationSetMethod;
	prototype.providerAvailabilitySessions = providerAvailabilitySessionsMethod;
	prototype.capacityProviderAssignments = capacityProviderAssignmentsMethod;
	prototype.executionRuns = executionRunsMethod;
	prototype.admitCapacityAssignment = admitCapacityAssignmentMethod;
	prototype.providerAssignmentExplanation = providerAssignmentExplanationMethod;
	prototype.capacityProviderAssignment = capacityProviderAssignmentMethod;
	prototype.capacityReservations = capacityReservationsMethod;
	prototype.capacityReservationExplanation = capacityReservationExplanationMethod;
	prototype.capacityUsage = capacityUsageMethod;
	prototype.capacityLedger = capacityLedgerMethod;
	prototype.capacityEvidencePage = capacityEvidencePageMethod;
	prototype.projectCapacityDiagnostics = projectCapacityDiagnosticsMethod;
	prototype.projectAgentClasses = projectAgentClassesMethod;
	prototype.createProjectAgentClass = createProjectAgentClassMethod;
	prototype.projectAgentClass = projectAgentClassMethod;
	prototype.updateProjectAgentClass = updateProjectAgentClassMethod;
	prototype.projectAgentModeRuns = projectAgentModeRunsMethod;
	prototype.projectCapacityRuntimeDiagnostics = projectCapacityRuntimeDiagnosticsMethod;
	prototype.decisionPlanningStatus = decisionPlanningStatusMethod;
	prototype.createPlanningInputRequest = createPlanningInputRequestMethod;
	prototype.decisionStructuredEstimates = decisionStructuredEstimatesMethod;
	prototype.createStructuredAgentEstimate = createStructuredAgentEstimateMethod;
	prototype.acceptStructuredAgentEstimate = acceptStructuredAgentEstimateMethod;
	prototype.decisionExecutionInputs = decisionExecutionInputsMethod;
	prototype.createDecisionExecutionInput = createDecisionExecutionInputMethod;
	prototype.acceptDecisionExecutionInput = acceptDecisionExecutionInputMethod;
	prototype.requestDecisionExecutionInputRevision = requestDecisionExecutionInputRevisionMethod;
	prototype.decisionAssignmentGraphs = decisionAssignmentGraphsMethod;
	prototype.decisionAssignmentGraph = decisionAssignmentGraphMethod;
	prototype.deliverableManifest = deliverableManifestMethod;
	prototype.decisionCapacityPlans = decisionCapacityPlansMethod;
	prototype.createDecisionCapacityPlan = createDecisionCapacityPlanMethod;
	prototype.capacityPlan = capacityPlanMethod;
	prototype.acceptCapacityPlan = acceptCapacityPlanMethod;
	prototype.requestCapacityPlanRevision = requestCapacityPlanRevisionMethod;
	prototype.scheduleCapacityPlan = scheduleCapacityPlanMethod;
	prototype.supersedeCapacityPlan = supersedeCapacityPlanMethod;
	prototype.createWorkday = createWorkdayMethod;
	prototype.workday = workdayMethod;
	prototype.startWorkday = startWorkdayMethod;
	prototype.pauseWorkday = pauseWorkdayMethod;
	prototype.resumeWorkday = resumeWorkdayMethod;
	prototype.cancelWorkday = cancelWorkdayMethod;
	prototype.completeWorkday = completeWorkdayMethod;
	prototype.workdaySummary = workdaySummaryMethod;
	prototype.workdayRuns = workdayRunsMethod;
	prototype.createWorkdayRun = createWorkdayRunMethod;
	prototype.workdayRun = workdayRunMethod;
	prototype.updateWorkdayRun = updateWorkdayRunMethod;
	prototype.tickWorkdayRun = tickWorkdayRunMethod;
	prototype.createResearchWorkflow = createResearchWorkflowMethod;
	prototype.researchWorkflow = researchWorkflowMethod;
	prototype.cancelCapacityAssignment = cancelCapacityAssignmentMethod;
	prototype.requeueCapacityAssignment = requeueCapacityAssignmentMethod;
	prototype.decideCapacityOverrun = decideCapacityOverrunMethod;
	prototype.workdayEvents = workdayEventsMethod;
	prototype.createWorkdayEvent = createWorkdayEventMethod;
	prototype.planSeed = planSeedMethod;
	prototype.applySeed = applySeedMethod;
	prototype.listSeedRuns = listSeedRunsMethod;
	prototype.exportSeed = exportSeedMethod;
	prototype.catalog = catalogMethod;
	prototype.artifactDownload = artifactDownloadMethod;
}
