import type { AgentSdk } from '../entrypoints/models/sdk.ts';
import { resolveDispatchTokenMethod } from './accounts/resolve-dispatch-token.ts';
import { executeDispatchLocallyMethod } from './runtime/execute-dispatch-locally.ts';
import { dispatchMethod } from './support/messages/dispatch.ts';
import { envelopeMethod } from './support/messages/envelope.ts';
import { getMethod } from './support/get.ts';
import { readMethod } from './support/read.ts';
import { searchMethod } from './support/search/search.ts';
import { followMethod } from './support/graph/follow.ts';
import { pickMethod } from './support/pick.ts';
import { createMethod } from './support/create.ts';
import { updateMethod } from './support/update.ts';
import { claimMessageMethod } from './support/messages/claim-message.ts';
import { ackMessageMethod } from './support/messages/ack-message.ts';
import { createMessageMethod } from './support/messages/create-message.ts';
import { recordRunMethod } from './support/execution/record-run.ts';
import { getCursorMethod } from './support/cursors/get-cursor.ts';
import { upsertCursorMethod } from './support/cursors/upsert-cursor.ts';
import { releaseLeaseMethod } from './packages/release-lease.ts';
import { releaseAllLeasesMethod } from './packages/release-all-leases.ts';
import { createApprovalRequestMethod } from './support/approvals/create-approval-request.ts';
import { listApprovalRequestsMethod } from './support/approvals/list-approval-requests.ts';
import { decideApprovalRequestMethod } from './support/approvals/decide-approval-request.ts';
import { upsertTeamInboxItemMethod } from './teams/upsert-team-inbox-item.ts';
import { listWorkstreamsMethod } from './support/workstreams/list-workstreams.ts';
import { getWorkstreamMethod } from './support/workstreams/get-workstream.ts';
import { upsertWorkstreamMethod } from './support/workstreams/upsert-workstream.ts';
import { appendWorkstreamEventMethod } from './support/workstreams/append-workstream-event.ts';
import { listReleasesMethod } from './packages/list-releases.ts';
import { getReleaseMethod } from './packages/get-release.ts';
import { upsertReleaseMethod } from './packages/upsert-release.ts';
import { listSharePackagesMethod } from './packages/list-share-packages.ts';
import { getSharePackageMethod } from './packages/get-share-package.ts';
import { upsertSharePackageMethod } from './packages/upsert-share-package.ts';
import { listAgentSpecsMethod } from './agents/list-agent-specs.ts';
import { listRawAgentSpecsMethod } from './agents/list-raw-agent-specs.ts';
import { scopeForAgentMethod } from './agents/scope-for-agent.ts';
import { refreshGraphMethod } from './treedx/graph/refresh-graph.ts';
import { searchFilesMethod } from './support/search/search-files.ts';
import { searchSectionsMethod } from './support/search/search-sections.ts';
import { searchEntitiesMethod } from './support/search/search-entities.ts';
import { getGraphNodeMethod } from './treedx/graph/get-graph-node.ts';
import { getNeighborsMethod } from './support/graph/get-neighbors.ts';
import { followReferencesMethod } from './support/graph/follow-references.ts';
import { getBacklinksMethod } from './support/graph/get-backlinks.ts';
import { getRelatedMethod } from './support/graph/get-related.ts';
import { getSubgraphMethod } from './treedx/graph/get-subgraph.ts';
import { resolveSeedsMethod } from './seeds/resolve-seeds.ts';
import { queryGraphMethod } from './treedx/graph/query-graph.ts';
import { buildContextPackMethod } from './build/build-context-pack.ts';
import { parseGraphDslMethod } from './treedx/graph/parse-graph-dsl.ts';
import { resolveReferenceMethod } from './support/graph/resolve-reference.ts';
import { explainReferenceChainMethod } from './support/graph/explain-reference-chain.ts';

export function installAgentSdkMethods(prototype: AgentSdk) {
	prototype.resolveDispatchToken = resolveDispatchTokenMethod;
	prototype.executeDispatchLocally = executeDispatchLocallyMethod;
	prototype.dispatch = dispatchMethod;
	prototype.envelope = envelopeMethod;
	prototype.get = getMethod;
	prototype.read = readMethod;
	prototype.search = searchMethod;
	prototype.follow = followMethod;
	prototype.pick = pickMethod;
	prototype.create = createMethod;
	prototype.update = updateMethod;
	prototype.claimMessage = claimMessageMethod;
	prototype.ackMessage = ackMessageMethod;
	prototype.createMessage = createMessageMethod;
	prototype.recordRun = recordRunMethod;
	prototype.getCursor = getCursorMethod;
	prototype.upsertCursor = upsertCursorMethod;
	prototype.releaseLease = releaseLeaseMethod;
	prototype.releaseAllLeases = releaseAllLeasesMethod;
	prototype.createApprovalRequest = createApprovalRequestMethod;
	prototype.listApprovalRequests = listApprovalRequestsMethod;
	prototype.decideApprovalRequest = decideApprovalRequestMethod;
	prototype.upsertTeamInboxItem = upsertTeamInboxItemMethod;
	prototype.listWorkstreams = listWorkstreamsMethod;
	prototype.getWorkstream = getWorkstreamMethod;
	prototype.upsertWorkstream = upsertWorkstreamMethod;
	prototype.appendWorkstreamEvent = appendWorkstreamEventMethod;
	prototype.listReleases = listReleasesMethod;
	prototype.getRelease = getReleaseMethod;
	prototype.upsertRelease = upsertReleaseMethod;
	prototype.listSharePackages = listSharePackagesMethod;
	prototype.getSharePackage = getSharePackageMethod;
	prototype.upsertSharePackage = upsertSharePackageMethod;
	prototype.listAgentSpecs = listAgentSpecsMethod;
	prototype.listRawAgentSpecs = listRawAgentSpecsMethod;
	prototype.scopeForAgent = scopeForAgentMethod;
	prototype.refreshGraph = refreshGraphMethod;
	prototype.searchFiles = searchFilesMethod;
	prototype.searchSections = searchSectionsMethod;
	prototype.searchEntities = searchEntitiesMethod;
	prototype.getGraphNode = getGraphNodeMethod;
	prototype.getNeighbors = getNeighborsMethod;
	prototype.followReferences = followReferencesMethod;
	prototype.getBacklinks = getBacklinksMethod;
	prototype.getRelated = getRelatedMethod;
	prototype.getSubgraph = getSubgraphMethod;
	prototype.resolveSeeds = resolveSeedsMethod;
	prototype.queryGraph = queryGraphMethod;
	prototype.buildContextPack = buildContextPackMethod;
	prototype.parseGraphDsl = parseGraphDslMethod;
	prototype.resolveReference = resolveReferenceMethod;
	prototype.explainReferenceChain = explainReferenceChainMethod;
}
