import type { AgentSdk } from '../sdk.ts';
import { resolveDispatchTokenMethod } from './resolve-dispatch-token.ts';
import { executeDispatchLocallyMethod } from './execute-dispatch-locally.ts';
import { dispatchMethod } from './dispatch.ts';
import { envelopeMethod } from './envelope.ts';
import { getMethod } from './get.ts';
import { readMethod } from './read.ts';
import { searchMethod } from './search.ts';
import { followMethod } from './follow.ts';
import { pickMethod } from './pick.ts';
import { createMethod } from './create.ts';
import { updateMethod } from './update.ts';
import { claimMessageMethod } from './claim-message.ts';
import { ackMessageMethod } from './ack-message.ts';
import { createMessageMethod } from './create-message.ts';
import { recordRunMethod } from './record-run.ts';
import { getCursorMethod } from './get-cursor.ts';
import { upsertCursorMethod } from './upsert-cursor.ts';
import { releaseLeaseMethod } from './release-lease.ts';
import { releaseAllLeasesMethod } from './release-all-leases.ts';
import { createApprovalRequestMethod } from './create-approval-request.ts';
import { listApprovalRequestsMethod } from './list-approval-requests.ts';
import { decideApprovalRequestMethod } from './decide-approval-request.ts';
import { upsertTeamInboxItemMethod } from './upsert-team-inbox-item.ts';
import { listWorkstreamsMethod } from './list-workstreams.ts';
import { getWorkstreamMethod } from './get-workstream.ts';
import { upsertWorkstreamMethod } from './upsert-workstream.ts';
import { appendWorkstreamEventMethod } from './append-workstream-event.ts';
import { listReleasesMethod } from './list-releases.ts';
import { getReleaseMethod } from './get-release.ts';
import { upsertReleaseMethod } from './upsert-release.ts';
import { listSharePackagesMethod } from './list-share-packages.ts';
import { getSharePackageMethod } from './get-share-package.ts';
import { upsertSharePackageMethod } from './upsert-share-package.ts';
import { listAgentSpecsMethod } from './list-agent-specs.ts';
import { listRawAgentSpecsMethod } from './list-raw-agent-specs.ts';
import { scopeForAgentMethod } from './scope-for-agent.ts';
import { refreshGraphMethod } from './refresh-graph.ts';
import { searchFilesMethod } from './search-files.ts';
import { searchSectionsMethod } from './search-sections.ts';
import { searchEntitiesMethod } from './search-entities.ts';
import { getGraphNodeMethod } from './get-graph-node.ts';
import { getNeighborsMethod } from './get-neighbors.ts';
import { followReferencesMethod } from './follow-references.ts';
import { getBacklinksMethod } from './get-backlinks.ts';
import { getRelatedMethod } from './get-related.ts';
import { getSubgraphMethod } from './get-subgraph.ts';
import { resolveSeedsMethod } from './resolve-seeds.ts';
import { queryGraphMethod } from './query-graph.ts';
import { buildContextPackMethod } from './build-context-pack.ts';
import { parseGraphDslMethod } from './parse-graph-dsl.ts';
import { resolveReferenceMethod } from './resolve-reference.ts';
import { explainReferenceChainMethod } from './explain-reference-chain.ts';

export function installAgentSdkMethods(prototype: AgentSdk) {
	prototype.resolveDispatchToken = resolveDispatchTokenMethod;
	prototype.executeDispatchLocally = executeDispatchLocallyMethod;
	prototype.dispatch = dispatchMethod;
	prototype.envelope = envelopeMethod;
	prototype.get = getMethod;
	prototype.read = readMethod;
	prototype.search = searchMethod;
	prototype.follow = followMethod;
	prototype.pick = pickMethod;
	prototype.create = createMethod;
	prototype.update = updateMethod;
	prototype.claimMessage = claimMessageMethod;
	prototype.ackMessage = ackMessageMethod;
	prototype.createMessage = createMessageMethod;
	prototype.recordRun = recordRunMethod;
	prototype.getCursor = getCursorMethod;
	prototype.upsertCursor = upsertCursorMethod;
	prototype.releaseLease = releaseLeaseMethod;
	prototype.releaseAllLeases = releaseAllLeasesMethod;
	prototype.createApprovalRequest = createApprovalRequestMethod;
	prototype.listApprovalRequests = listApprovalRequestsMethod;
	prototype.decideApprovalRequest = decideApprovalRequestMethod;
	prototype.upsertTeamInboxItem = upsertTeamInboxItemMethod;
	prototype.listWorkstreams = listWorkstreamsMethod;
	prototype.getWorkstream = getWorkstreamMethod;
	prototype.upsertWorkstream = upsertWorkstreamMethod;
	prototype.appendWorkstreamEvent = appendWorkstreamEventMethod;
	prototype.listReleases = listReleasesMethod;
	prototype.getRelease = getReleaseMethod;
	prototype.upsertRelease = upsertReleaseMethod;
	prototype.listSharePackages = listSharePackagesMethod;
	prototype.getSharePackage = getSharePackageMethod;
	prototype.upsertSharePackage = upsertSharePackageMethod;
	prototype.listAgentSpecs = listAgentSpecsMethod;
	prototype.listRawAgentSpecs = listRawAgentSpecsMethod;
	prototype.scopeForAgent = scopeForAgentMethod;
	prototype.refreshGraph = refreshGraphMethod;
	prototype.searchFiles = searchFilesMethod;
	prototype.searchSections = searchSectionsMethod;
	prototype.searchEntities = searchEntitiesMethod;
	prototype.getGraphNode = getGraphNodeMethod;
	prototype.getNeighbors = getNeighborsMethod;
	prototype.followReferences = followReferencesMethod;
	prototype.getBacklinks = getBacklinksMethod;
	prototype.getRelated = getRelatedMethod;
	prototype.getSubgraph = getSubgraphMethod;
	prototype.resolveSeeds = resolveSeedsMethod;
	prototype.queryGraph = queryGraphMethod;
	prototype.buildContextPack = buildContextPackMethod;
	prototype.parseGraphDsl = parseGraphDslMethod;
	prototype.resolveReference = resolveReferenceMethod;
	prototype.explainReferenceChain = explainReferenceChainMethod;
}
