import type { SceneCapability } from '../types.ts';

export const PHASE0_RUNTIME_CAPABILITIES = [
{
				id: 'scene.sdk-foundation',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'SDK-owned scene foundation types, Phase 0 report, and artifact path planning are available.',
			},
{
				id: 'scene.cli-status',
				status: 'available',
				owner: '@treeseed/cli',
				summary: 'CLI-owned scene status command can report installed Phase 0 capability without running workflows.',
			},
{
				id: 'scene.manifest-loader',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'YAML scene manifests can be loaded and parsed through the SDK scene module.',
			},
{
				id: 'scene.schema-validation',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene manifests can be validated and normalized with stable diagnostics.',
			},
{
				id: 'scene.plan-compiler',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene manifests can compile into deterministic non-mutating plan reports.',
			},
{
				id: 'scene.playwright-runner',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Playwright browser execution is available for browser-safe actions and assertions.',
			},
{
				id: 'scene.environment-integration',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene runs can prepare Treeseed readiness and managed local dev through canonical SDK services.',
			},
{
				id: 'scene.seed-integration',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene runs can plan and explicitly apply seeds through canonical Treeseed seed services.',
			},
{
				id: 'scene.auth-integration',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene runs can resolve market auth profiles and block clearly when required sessions are missing.',
			},
{
				id: 'scene.operation-polling',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene runs can wait for linked or explicit Treeseed platform operations.',
			},
{
				id: 'scene.log-collection',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene runs collect bounded managed-dev logs into run artifacts when available.',
			},
{
				id: 'scene.plugin-contract',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Formal SDK plugin contracts and static built-in plugin resolution are available.',
			},
{
				id: 'scene.internal-action-plugins',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Built-in actions execute through internal action plugin handlers.',
			},
{
				id: 'scene.internal-assertion-plugins',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Built-in assertions execute through internal assertion plugin handlers.',
			},
{
				id: 'scene.internal-environment-plugin',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Environment, auth, seed, and base URL setup are exposed through an internal environment plugin.',
			},
{
				id: 'scene.plugin-plan-diagnostics',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene plan reports include plugin summaries, enabled plugin ids, and plugin diagnostics.',
			},
{
				id: 'scene.dynamic-plugin-discovery',
				status: 'planned',
				owner: '@treeseed/sdk',
				summary: 'Dynamic package-local plugin discovery is planned after static built-in plugins.',
			},
{
				id: 'scene.remotion-renderer',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Remotion rendering is available through the SDK renderer plugin boundary.',
			},
{
				id: 'scene.long-workflow-runtime',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Chapters, segments, checkpoints, resume, inspect, progress events, pauses, and timeout hierarchy are available.',
			},
{
				id: 'scene.chapter-runtime',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene runs report chapter boundaries and chapter-local status for long workflows.',
			},
{
				id: 'scene.segment-runtime',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene runs write segment metadata for future render-from-partial-artifacts workflows.',
			},
{
				id: 'scene.checkpoints',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene runs write durable checkpoints after successful steps.',
			},
{
				id: 'scene.resume',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene runs can resume from resumable checkpoints using checkpoint replay.',
			},
{
				id: 'scene.inspect',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene run artifacts can be inspected by run id or path.',
			},
{
				id: 'scene.progress-jsonl',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Long scene runs write progress.jsonl and stream JSONL progress events from the CLI.',
			},
{
				id: 'scene.pause-action',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Timed and manual pause actions are available through the control action runtime.',
			},
{
				id: 'scene.timeout-hierarchy',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene runtime supports normalized scene, chapter, and step timeout configuration.',
			},
{
				id: 'scene.render-command',
				status: 'available',
				owner: '@treeseed/cli',
				summary: 'The CLI can render previous scene run artifacts with `trsd scene render`.',
			},
{
				id: 'scene.render-only-from-artifacts',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Rendering consumes existing scene artifacts without rerunning browser workflows.',
			},
{
				id: 'scene.remotion-composition-registry',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Built-in Remotion compositions are registered for demo, training, failure review, and diagram-only videos.',
			},
{
				id: 'scene.video-overlays',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Render input carries overlay and callout metadata anchored to scene timeline steps.',
			},
{
				id: 'scene.chapter-title-rendering',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Remotion renders chapter title context from long workflow artifacts.',
			},
{
				id: 'scene.failure-review-rendering',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Failure review videos can focus failed steps, diagnostics, and evidence artifacts.',
			},
{
				id: 'scene.screenshot-slideshow-rendering',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Render falls back to screenshot slideshow output when a run has no browser video.',
			}
] satisfies SceneCapability[];
