import { z } from 'zod';
import { defineOperation } from '../operation-builder.ts';
import { inboxActionRequestSchema, inboxDraftPurposeSchema, inboxDraftSchema, inboxDraftWriteSchema, inboxItemPageSchema,
	inboxItemSchema, inboxMutationReceiptSchema, inboxQuestionCreateSchema, inboxTimelineSchema } from '../inbox/contracts.ts';

const empty = z.object({}).strict();
const none = z.undefined();
const itemPath = z.object({ teamId: z.string().min(1), itemId: z.string().min(1) }).strict();

export function inboxOperations() {
	return {
		list: defineOperation({ operationId: 'inbox.items.list', description: 'List the active team governance inbox.', rest: { method: 'GET', path: '/v1/teams/{teamId}/inbox/items' }, parameters: 'treeseed.inbox.items.list.parameters/v1', capability: 'governance.read', authentication: 'oauth', oauthScopes: ['treeseed:read'], kind: 'read', riskClass: 'ordinary', confirmation: 'never', surfaces: ['rest', 'cli', 'mcp_tool', 'mcp_resource'], cacheScope: 'principal', pagination: 'cursor' }, {
			path: z.object({ teamId: z.string().min(1) }).strict(), query: z.object({ projectId: z.string().optional(), kind: z.enum(['proposal', 'question', 'all']).optional(), state: z.enum(['outstanding', 'all']).optional(), limit: z.coerce.number().int().min(1).max(500).optional(), cursor: z.string().optional() }).strict(), body: none, output: inboxItemPageSchema,
		}),
		show: defineOperation({ operationId: 'inbox.items.show', description: 'Read one inbox item and its thread.', rest: { method: 'GET', path: '/v1/teams/{teamId}/inbox/items/{itemId}' }, parameters: 'treeseed.inbox.items.show.parameters/v1', capability: 'governance.read', authentication: 'oauth', oauthScopes: ['treeseed:read'], kind: 'read', riskClass: 'ordinary', confirmation: 'never', surfaces: ['rest', 'cli', 'mcp_resource'], cacheScope: 'principal', pagination: 'none' }, { path: itemPath, query: empty, body: none, output: inboxItemSchema }),
		events: defineOperation({ operationId: 'inbox.events.list', description: 'Long-poll ordered inbox events.', rest: { method: 'GET', path: '/v1/teams/{teamId}/inbox/events' }, parameters: 'treeseed.inbox.events.list.parameters/v1', capability: 'governance.read', authentication: 'oauth', oauthScopes: ['treeseed:read'], kind: 'read', riskClass: 'ordinary', confirmation: 'never', surfaces: ['rest', 'cli', 'mcp_resource'], cacheScope: 'principal', pagination: 'cursor' }, { path: z.object({ teamId: z.string() }).strict(), query: z.object({ after: z.string().optional(), waitSeconds: z.coerce.number().int().min(0).max(30).optional(), limit: z.coerce.number().int().min(1).max(500).optional() }).strict(), body: none, output: inboxTimelineSchema }),
		createQuestion: defineOperation({ operationId: 'inbox.questions.create', description: 'Create and route a TreeDX-backed project question.', rest: { method: 'POST', path: '/v1/teams/{teamId}/inbox/questions' }, parameters: 'treeseed.inbox.questions.create.parameters/v1', capability: 'governance.write', authentication: 'oauth', oauthScopes: ['treeseed:knowledge:write', 'treeseed:execution'], kind: 'mutation', riskClass: 'ordinary', confirmation: 'never', surfaces: ['rest', 'cli', 'mcp_tool'], cacheScope: 'none', pagination: 'none' }, { path: z.object({ teamId: z.string() }).strict(), query: empty, body: inboxQuestionCreateSchema, output: inboxMutationReceiptSchema }),
		getDraft: defineOperation({ operationId: 'inbox.drafts.show', description: 'Read the current principal private inbox draft.', rest: { method: 'GET', path: '/v1/teams/{teamId}/inbox/items/{itemId}/drafts/{purpose}' }, parameters: 'treeseed.inbox.drafts.show.parameters/v1', capability: 'governance.read', authentication: 'oauth', oauthScopes: ['treeseed:read'], kind: 'read', riskClass: 'ordinary', confirmation: 'never', surfaces: ['rest', 'cli'], cacheScope: 'principal', pagination: 'none' }, { path: itemPath.extend({ purpose: inboxDraftPurposeSchema }), query: empty, body: none, output: inboxDraftSchema.nullable() }),
		putDraft: defineOperation({ operationId: 'inbox.drafts.put', description: 'Save a private inbox draft.', rest: { method: 'PUT', path: '/v1/teams/{teamId}/inbox/items/{itemId}/drafts/{purpose}' }, parameters: 'treeseed.inbox.drafts.put.parameters/v1', capability: 'governance.write', authentication: 'oauth', oauthScopes: ['treeseed:governance:write'], kind: 'mutation', riskClass: 'ordinary', confirmation: 'never', surfaces: ['rest', 'cli'], cacheScope: 'none', pagination: 'none', concurrencyRequired: true }, { path: itemPath.extend({ purpose: inboxDraftPurposeSchema }), query: empty, body: inboxDraftWriteSchema, output: inboxDraftSchema }),
		deleteDraft: defineOperation({ operationId: 'inbox.drafts.delete', description: 'Delete a private inbox draft.', rest: { method: 'DELETE', path: '/v1/teams/{teamId}/inbox/items/{itemId}/drafts/{purpose}' }, parameters: 'treeseed.inbox.drafts.delete.parameters/v1', capability: 'governance.write', authentication: 'oauth', oauthScopes: ['treeseed:governance:write'], kind: 'mutation', riskClass: 'ordinary', confirmation: 'never', surfaces: ['rest', 'cli'], cacheScope: 'none', pagination: 'none' }, { path: itemPath.extend({ purpose: inboxDraftPurposeSchema }), query: empty, body: empty, output: z.object({ deleted: z.boolean() }).strict() }),
		action: defineOperation({ operationId: 'inbox.items.action', description: 'Apply an exact-version inbox action.', rest: { method: 'POST', path: '/v1/teams/{teamId}/inbox/items/{itemId}/actions' }, parameters: 'treeseed.inbox.items.action.parameters/v1', capability: 'governance.write', authentication: 'oauth', oauthScopes: ['treeseed:governance:write'], kind: 'mutation', riskClass: 'ordinary', confirmation: 'never', surfaces: ['rest', 'cli', 'mcp_tool'], cacheScope: 'none', pagination: 'none', concurrencyRequired: true }, { path: itemPath, query: empty, body: inboxActionRequestSchema, output: inboxMutationReceiptSchema }),
	};
}
