import { sql } from 'drizzle-orm';
import { bigint, check, foreignKey, index, integer, pgTable, primaryKey, real, serial, text, uniqueIndex } from 'drizzle-orm/pg-core';


export const commerceSubscriptions = pgTable('commerce_subscriptions', {
	id: text('id').primaryKey(),
	orderId: text('order_id').notNull(),
	vendorId: text('vendor_id').notNull(),
	sellerTeamId: text('seller_team_id').notNull(),
	buyerTeamId: text('buyer_team_id'),
	buyerUserId: text('buyer_user_id'),
	offerId: text('offer_id').notNull(),
	priceId: text('price_id').notNull(),
	status: text('status').notNull(),
	renewalState: text('renewal_state').notNull().default('active'),
	stripeSubscriptionId: text('stripe_subscription_id').notNull(),
	stripeCustomerId: text('stripe_customer_id'),
	stripeConnectedAccountId: text('stripe_connected_account_id').notNull(),
	currentPeriodStart: text('current_period_start'),
	currentPeriodEnd: text('current_period_end'),
	cancelAtPeriodEnd: integer('cancel_at_period_end').notNull().default(0),
	canceledAt: text('canceled_at'),
	metadataJson: text('metadata_json').notNull().default('{}'),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
}, (table) => [
	uniqueIndex('idx_commerce_subscriptions_stripe').on(table.stripeSubscriptionId, table.stripeConnectedAccountId),
	index('idx_commerce_subscriptions_buyer_team_status').on(table.buyerTeamId, table.status, table.updatedAt),
	index('idx_commerce_subscriptions_vendor_status').on(table.vendorId, table.status, table.updatedAt),
	index('idx_commerce_subscriptions_offer_status').on(table.offerId, table.status)
]);

export const commerceEntitlements = pgTable('commerce_entitlements', {
	id: text('id').primaryKey(),
	buyerTeamId: text('buyer_team_id'),
	buyerUserId: text('buyer_user_id'),
	sellerTeamId: text('seller_team_id').notNull(),
	productId: text('product_id').notNull(),
	productVersionId: text('product_version_id'),
	offerId: text('offer_id').notNull(),
	orderId: text('order_id'),
	orderItemId: text('order_item_id'),
	subscriptionId: text('subscription_id'),
	status: text('status').notNull().default('pending'),
	accessScopeJson: text('access_scope_json').notNull().default('{}'),
	startsAt: text('starts_at'),
	endsAt: text('ends_at'),
	renewalState: text('renewal_state').notNull().default('none'),
	fulfillmentArtifactRefsJson: text('fulfillment_artifact_refs_json').notNull().default('[]'),
	projectId: text('project_id'),
	catalogItemId: text('catalog_item_id'),
	ownershipSnapshotJson: text('ownership_snapshot_json').notNull().default('{}'),
	metadataJson: text('metadata_json').notNull().default('{}'),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
}, (table) => [
	index('idx_commerce_entitlements_buyer_team_status').on(table.buyerTeamId, table.status, table.updatedAt),
	index('idx_commerce_entitlements_buyer_user_status').on(table.buyerUserId, table.status, table.updatedAt),
	index('idx_commerce_entitlements_product_status').on(table.productId, table.status),
	index('idx_commerce_entitlements_offer_status').on(table.offerId, table.status),
	index('idx_commerce_entitlements_order').on(table.orderId),
	index('idx_commerce_entitlements_subscription').on(table.subscriptionId),
	index('idx_commerce_entitlements_catalog_item').on(table.catalogItemId)
]);

export const commerceBuyerStripeCustomers = pgTable('commerce_buyer_stripe_customers', {
	id: text('id').primaryKey(),
	buyerTeamId: text('buyer_team_id'),
	buyerUserId: text('buyer_user_id'),
	vendorId: text('vendor_id').notNull(),
	connectedAccountId: text('connected_account_id').notNull(),
	environment: text('environment').notNull().default('test'),
	stripeCustomerId: text('stripe_customer_id').notNull(),
	metadataJson: text('metadata_json').notNull().default('{}'),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
}, (table) => [
	uniqueIndex('idx_commerce_buyer_stripe_customers_team').on(table.vendorId, table.environment, table.buyerTeamId),
	uniqueIndex('idx_commerce_buyer_stripe_customers_user').on(table.vendorId, table.environment, table.buyerUserId),
	uniqueIndex('idx_commerce_buyer_stripe_customers_stripe').on(table.connectedAccountId, table.stripeCustomerId)
]);

export const commerceRefunds = pgTable('commerce_refunds', {
	id: text('id').primaryKey(),
	orderId: text('order_id').notNull(),
	orderItemId: text('order_item_id'),
	paymentGroupId: text('payment_group_id'),
	vendorId: text('vendor_id').notNull(),
	sellerTeamId: text('seller_team_id').notNull(),
	buyerTeamId: text('buyer_team_id'),
	buyerUserId: text('buyer_user_id'),
	amount: integer('amount').notNull(),
	currency: text('currency').notNull(),
	status: text('status').notNull().default('processing'),
	reason: text('reason'),
	stripeRefundId: text('stripe_refund_id'),
	stripePaymentIntentId: text('stripe_payment_intent_id'),
	stripeConnectedAccountId: text('stripe_connected_account_id'),
	idempotencyKey: text('idempotency_key').notNull(),
	requestedByType: text('requested_by_type').notNull(),
	requestedById: text('requested_by_id').notNull(),
	failureReason: text('failure_reason'),
	metadataJson: text('metadata_json').notNull().default('{}'),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
}, (table) => [
	uniqueIndex('idx_commerce_refunds_stripe').on(table.stripeRefundId, table.stripeConnectedAccountId),
	uniqueIndex('idx_commerce_refunds_idempotency').on(table.idempotencyKey),
	index('idx_commerce_refunds_order').on(table.orderId, table.createdAt),
	index('idx_commerce_refunds_vendor_status').on(table.vendorId, table.status, table.updatedAt),
	index('idx_commerce_refunds_seller_status').on(table.sellerTeamId, table.status, table.updatedAt)
]);

export const commerceFulfillmentEvents = pgTable('commerce_fulfillment_events', {
	id: text('id').primaryKey(),
	orderId: text('order_id').notNull(),
	orderItemId: text('order_item_id'),
	entitlementId: text('entitlement_id'),
	vendorId: text('vendor_id').notNull(),
	sellerTeamId: text('seller_team_id').notNull(),
	productId: text('product_id').notNull(),
	productVersionId: text('product_version_id'),
	catalogItemId: text('catalog_item_id'),
	catalogArtifactVersionId: text('catalog_artifact_version_id'),
	eventType: text('event_type').notNull(),
	status: text('status').notNull().default('pending'),
	artifactRefsJson: text('artifact_refs_json').notNull().default('[]'),
	deliveryRefsJson: text('delivery_refs_json').notNull().default('[]'),
	message: text('message'),
	actorType: text('actor_type').notNull(),
	actorId: text('actor_id').notNull(),
	metadataJson: text('metadata_json').notNull().default('{}'),
	createdAt: text('created_at').notNull(),
}, (table) => [
	index('idx_commerce_fulfillment_events_order').on(table.orderId, table.createdAt),
	index('idx_commerce_fulfillment_events_entitlement').on(table.entitlementId, table.createdAt),
	index('idx_commerce_fulfillment_events_vendor_status').on(table.vendorId, table.status, table.createdAt),
	index('idx_commerce_fulfillment_events_product').on(table.productId, table.createdAt)
]);

export const commerceServiceRequests = pgTable('commerce_service_requests', {
	id: text('id').primaryKey(),
	buyerTeamId: text('buyer_team_id'),
	buyerUserId: text('buyer_user_id'),
	vendorId: text('vendor_id').notNull(),
	sellerTeamId: text('seller_team_id').notNull(),
	productId: text('product_id').notNull(),
	offerId: text('offer_id').notNull(),
	status: text('status').notNull().default('requested'),
	requestedScope: text('requested_scope').notNull(),
	approvedScope: text('approved_scope'),
	accessNeedsJson: text('access_needs_json').notNull().default('{}'),
	buyerVisibleSummary: text('buyer_visible_summary'),
	vendorPrivateNotes: text('vendor_private_notes'),
	activeQuoteId: text('active_quote_id'),
	approvedQuoteId: text('approved_quote_id'),
	contractId: text('contract_id'),
	relatedProjectId: text('related_project_id'),
	relatedWorkdayId: text('related_workday_id'),
	orderId: text('order_id'),
	entitlementId: text('entitlement_id'),
	ownershipSnapshotJson: text('ownership_snapshot_json').notNull().default('{}'),
	metadataJson: text('metadata_json').notNull().default('{}'),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
}, (table) => [
	index('idx_commerce_service_requests_buyer_team').on(table.buyerTeamId, table.status, table.updatedAt),
	index('idx_commerce_service_requests_buyer_user').on(table.buyerUserId, table.status, table.updatedAt),
	index('idx_commerce_service_requests_vendor').on(table.vendorId, table.status, table.updatedAt),
	index('idx_commerce_service_requests_seller').on(table.sellerTeamId, table.status, table.updatedAt),
	index('idx_commerce_service_requests_offer').on(table.offerId, table.status),
	index('idx_commerce_service_requests_project').on(table.relatedProjectId, table.status),
	index('idx_commerce_service_requests_workday').on(table.relatedWorkdayId, table.status)
]);

export const commerceServiceQuotes = pgTable('commerce_service_quotes', {
	id: text('id').primaryKey(),
	requestId: text('request_id').notNull(),
	vendorId: text('vendor_id').notNull(),
	sellerTeamId: text('seller_team_id').notNull(),
	buyerTeamId: text('buyer_team_id'),
	buyerUserId: text('buyer_user_id'),
	quoteVersion: integer('quote_version').notNull().default(1),
	status: text('status').notNull().default('draft'),
	title: text('title').notNull(),
	scopeSummary: text('scope_summary').notNull(),
	deliverablesJson: text('deliverables_json').notNull().default('[]'),
	assumptionsJson: text('assumptions_json').notNull().default('[]'),
	accessRequirementsJson: text('access_requirements_json').notNull().default('{}'),
	governanceRequirementsJson: text('governance_requirements_json').notNull().default('{}'),
	amount: integer('amount').notNull(),
	currency: text('currency').notNull(),
	expiresAt: text('expires_at'),
	buyerApprovedAt: text('buyer_approved_at'),
	vendorApprovedAt: text('vendor_approved_at'),
	acceptedAt: text('accepted_at'),
	rejectedAt: text('rejected_at'),
	metadataJson: text('metadata_json').notNull().default('{}'),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
}, (table) => [
	uniqueIndex('idx_commerce_service_quotes_request_version').on(table.requestId, table.quoteVersion),
	index('idx_commerce_service_quotes_request').on(table.requestId, table.status, table.updatedAt),
	index('idx_commerce_service_quotes_vendor').on(table.vendorId, table.status, table.updatedAt),
	index('idx_commerce_service_quotes_seller').on(table.sellerTeamId, table.status, table.updatedAt)
]);

export const commerceServiceContracts = pgTable('commerce_service_contracts', {
	id: text('id').primaryKey(),
	requestId: text('request_id').notNull(),
	quoteId: text('quote_id').notNull(),
	vendorId: text('vendor_id').notNull(),
	sellerTeamId: text('seller_team_id').notNull(),
	buyerTeamId: text('buyer_team_id'),
	buyerUserId: text('buyer_user_id'),
	productId: text('product_id').notNull(),
	offerId: text('offer_id').notNull(),
	status: text('status').notNull().default('pending_checkout'),
	amount: integer('amount').notNull(),
	currency: text('currency').notNull(),
	orderId: text('order_id'),
	orderItemId: text('order_item_id'),
	paymentGroupId: text('payment_group_id'),
	entitlementId: text('entitlement_id'),
	relatedProjectId: text('related_project_id'),
	relatedWorkdayId: text('related_workday_id'),
	ownershipSnapshotJson: text('ownership_snapshot_json').notNull().default('{}'),
	accessApprovalSnapshotJson: text('access_approval_snapshot_json').notNull().default('{}'),
	fulfillmentSummary: text('fulfillment_summary'),
	metadataJson: text('metadata_json').notNull().default('{}'),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
}, (table) => [
	uniqueIndex('idx_commerce_service_contracts_request_quote').on(table.requestId, table.quoteId),
	index('idx_commerce_service_contracts_vendor').on(table.vendorId, table.status, table.updatedAt),
	index('idx_commerce_service_contracts_seller').on(table.sellerTeamId, table.status, table.updatedAt),
	index('idx_commerce_service_contracts_buyer_team').on(table.buyerTeamId, table.status, table.updatedAt),
	index('idx_commerce_service_contracts_buyer_user').on(table.buyerUserId, table.status, table.updatedAt),
	index('idx_commerce_service_contracts_order').on(table.orderId),
	index('idx_commerce_service_contracts_entitlement').on(table.entitlementId),
	index('idx_commerce_service_contracts_project').on(table.relatedProjectId),
	index('idx_commerce_service_contracts_workday').on(table.relatedWorkdayId)
]);

export const commerceServiceEvents = pgTable('commerce_service_events', {
	id: text('id').primaryKey(),
	requestId: text('request_id').notNull(),
	quoteId: text('quote_id'),
	contractId: text('contract_id'),
	eventType: text('event_type').notNull(),
	actorType: text('actor_type').notNull(),
	actorId: text('actor_id'),
	priorState: text('prior_state'),
	nextState: text('next_state'),
	message: text('message'),
	evidenceJson: text('evidence_json').notNull().default('{}'),
	createdAt: text('created_at').notNull(),
}, (table) => [
	index('idx_commerce_service_events_request').on(table.requestId, table.createdAt),
	index('idx_commerce_service_events_quote').on(table.quoteId, table.createdAt),
	index('idx_commerce_service_events_contract').on(table.contractId, table.createdAt),
	index('idx_commerce_service_events_type').on(table.eventType, table.createdAt)
]);
