import type { SceneCapability } from '../../types.ts';

export const PHASE0_MEDIA_EVIDENCE_CAPABILITIES = [
{
				id: 'scene.diagram-system',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Typed animated diagram providers render operation, reconciliation, dev runtime, and scene timeline diagrams.',
			},
{
				id: 'scene.diagram-plugin-provider',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Built-in diagram provider plugin treeseed.scene.diagrams.remotion is available.',
			},
{
				id: 'scene.diagram-prop-validation',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene validate and plan check typed diagram component props before render.',
			},
{
				id: 'scene.diagram-render-input',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Render input includes normalized renderDiagrams from provider definitions and run artifacts.',
			},
{
				id: 'scene.diagram-remotion-rendering',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Remotion compositions render built-in diagrams through the adapter-hosted render path.',
			},
{
				id: 'scene.diagram-only-rendering',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Diagram-only rendering is available from existing run artifacts.',
			},
{
				id: 'scene.diagram-overlay-rendering',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Overlay diagrams can render alongside browser evidence in demo and training videos.',
			},
{
				id: 'scene.diagram-interstitial-rendering',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Interstitial and standalone diagrams can render as full-screen video sequences.',
			},
{
				id: 'scene.training-outputs',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Deterministic captions, transcripts, narration scripts, glossary output, and chapter clip manifests are available.',
			},
{
				id: 'scene.caption-generation',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene training outputs include deterministic VTT and SRT captions.',
			},
{
				id: 'scene.caption-rendering',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Training Remotion renders can display generated captions.',
			},
{
				id: 'scene.transcript-generation',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene training outputs include JSON and Markdown transcripts.',
			},
{
				id: 'scene.narration-scripts',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene training outputs include deterministic narration scripts without AI or TTS.',
			},
{
				id: 'scene.glossary-enrichment',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene training outputs include explicit and built-in Treeseed glossary terms.',
			},
{
				id: 'scene.chapter-clip-manifests',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene training outputs include chapter clip manifests for future export workflows.',
			},
{
				id: 'scene.training-command',
				status: 'available',
				owner: '@treeseed/cli',
				summary: 'The CLI can generate deterministic training outputs with `trsd scene training`.',
			},
{
				id: 'scene.training-artifacts',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene training artifacts are written under the existing run root training directory.',
			},
{
				id: 'scene.evidence-manifest',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene run artifacts can be summarized into deterministic local, CI, and release evidence manifests.',
			},
{
				id: 'scene.evidence-command',
				status: 'available',
				owner: '@treeseed/cli',
				summary: 'The CLI can generate downstream scene evidence with `trsd scene evidence`.',
			},
{
				id: 'scene.sanitized-evidence-bundle',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Evidence generation can copy a bounded sanitized bundle while excluding raw traces, videos, network captures, and app logs by default.',
			},
{
				id: 'scene.evidence-recommendations',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Evidence manifests include deterministic follow-up recommendations for inspect, resume, training, and render workflows.',
			},
{
				id: 'scene.ci-scene-verification',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene evidence reports expose CI-ready summaries, artifact inventory, and hashes without rerunning browser workflows.',
			},
{
				id: 'scene.release-evidence-summary',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Release-target evidence marks failed workflows as blocking recommendations while staying local until a later publish phase.',
			},
{
				id: 'scene.evidence-hashing',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Included evidence artifacts are hashed with SHA-256 for reproducible proof.',
			},
{
				id: 'scene.ai-narration-provider',
				status: 'planned',
				owner: '@treeseed/sdk',
				summary: 'Optional AI narration providers are planned after deterministic training outputs.',
			},
{
				id: 'scene.evidence-publishing',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Scene evidence can be published into local redacted bundles and local release-evidence export records.',
			},
{
				id: 'scene.redaction-policy-engine',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Deny-by-default redaction policies validate and control published scene evidence artifacts.',
			},
{
				id: 'scene.scene-publish-command',
				status: 'available',
				owner: '@treeseed/cli',
				summary: 'The CLI can publish local and release-target redacted evidence bundles with `trsd scene publish`.',
			},
{
				id: 'scene.deny-by-default-redaction',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Evidence publishing excludes artifacts unless an explicit redaction policy rule includes them.',
			},
{
				id: 'scene.local-publish-bundle',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Selected evidence artifacts are copied into a local publish bundle under the source run root.',
			},
{
				id: 'scene.release-evidence-export',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Release-target publishing writes a local release-evidence export record without mutating external providers.',
			},
{
				id: 'scene.publish-report',
				status: 'available',
				owner: '@treeseed/sdk',
				summary: 'Publish manifests and Markdown reports record redaction decisions, hashes, sizes, and bundle paths.',
			},
{
				id: 'scene.publish-plan-command',
				status: 'available',
				owner: '@treeseed/cli',
				summary: 'The CLI can produce docs, training, release-evidence, and artifact-store publication plans with `trsd scene publish-plan`.',
			},
{
				id: 'scene.publication-export-command',
				status: 'available',
				owner: '@treeseed/cli',
				summary: 'The CLI can create local publication export bundles from redacted Phase 10 publish artifacts with `trsd scene export`.',
			}
] satisfies SceneCapability[];
