import { betterAuthAccount,betterAuthVerification,capacityExecutionProviders,capacityProviderLanes,capacityProviderRegistrationRequests,capacityProviderTeamMemberships,capacityProviders,teamCapacityRegistrationKeys,teamInvites } from '../accounts/better-auth-account.ts';
import { agentLabViewState } from '../accounts/agent-lab-view-state.ts';
import { legacyCreditConversionProfiles,cursorState,leaseState,marketAuthCredentials,marketAuthPasswordResets,marketOperationRunners,messageQueue,notificationEmailDeliveries,notificationEvents,platformOperationEvents,platformOperations,runtimeRecords,seedRuns,sessionEvents,userNotifications } from '../accounts/notification-events.ts';
import { credentialEnvelopes,externalVaultBindings,secretOperationLeases,teamServiceCapabilityBindings,teamServiceConnections,teamServiceCredentialProfiles,teamVaultGrants,teamVaults,userVaultKeys } from '../accounts/team-services.ts';
import { agentFallbackOutputs,agentModeRuns,capacityWorkdayRuns,decisionAssignmentGraphs,decisionExecutionInputs,decisionPlanningStatuses,deliverableContracts,deliverableManifests,planningInputRequests,structuredAgentEstimates } from '../agents/agent-mode-runs.ts';
import { capacityAllocationSets,capacityLedgerEntries,capacityProviderAssignments,capacityUsageActuals,projectAgentClasses,providerAvailabilitySessions } from '../capacity/accounting/capacity-ledger-entries.ts';
import { approvalRequests,hubContentSources,hubRepositories,treeDxInstances } from '../projects/knowledge/project-knowledge-governance.ts';
import { projectRemoteRepositoryBindings,projectWorkflowOperations,providerConnectorAuthorizations,providerCredentialAuthorities,providerWebhookDeliveries,remoteCredentialDeliveries,remoteGitOperationGrants,workflowConfigurationDeliveries,workflowConfigurationRecords,workflowOperationRuns } from '../projects/integrations/provider-operations.ts';
import { bookCollections,knowledgeAuthoringWorkspaces,knowledgePackBuilds,knowledgePublications,knowledgeReviewComments,knowledgeReviews,knowledgeWorkspacePresence } from '../projects/knowledge/knowledge-collaboration.ts';
import { capacityAdmissionCounters,capacityAuditEvents,capacityGrants,capacityOperationReceipts,capacityProviderAccessTokens,capacityProviderProofNonces,capacityProviderRegistrationRateLimits,capacityProviderTeamCredentials,capacityReservationCounterClaims,capacityReservations } from '../capacity/providers/capacity-provider-team-credentials.ts';
import { agentCapacityPlans,capacityWorkdayEvents,capacityWorkdaySchedules,treeDxProxyHandles,workdayCapacityEnvelopes } from '../capacity/workdays/capacity-workday-events.ts';
import { betterAuthSession,betterAuthUser,commerceCapacityListingInquiries,commerceCapacityListings,commerceWebhookEvents,projectSummarySnapshots,teamInboxItems } from '../commerce/capacity/commerce-capacity-listings.ts';
import { catalogArtifactVersions,catalogItemCollaborators,catalogItems,commerceContributions,commerceGovernancePolicies,commerceOwnershipRecords,commerceOwnershipTransfers,commerceProducts,commerceStewardshipAssignments,commerceVendors } from '../commerce/catalog/catalog-items.ts';
import { commerceCartItems,commerceCarts,commerceCheckouts,commerceGovernanceEvents,commerceOffers,commerceOrderItems,commerceOrders,commercePaymentGroups,commercePrices,commerceProductVersions } from '../commerce/catalog/commerce-product-versions.ts';
import { commerceBuyerStripeCustomers,commerceEntitlements,commerceFulfillmentEvents,commerceRefunds,commerceServiceContracts,commerceServiceEvents,commerceServiceQuotes,commerceServiceRequests,commerceSubscriptions } from '../commerce/payments/commerce-subscriptions.ts';
import { commonsDecisions,commonsDelegations,commonsGovernanceEvents,commonsParticipants,commonsProposalBackings,commonsProposalVotes,commonsProposals,commonsQuestions,commonsWeightSnapshots,governanceProposalVersions,governanceProposals,projectGovernancePolicies,teamGovernancePolicies } from '../governance/commons/commons-participants.ts';
import { entitlements,governanceDecisions,governanceDelegations,governanceElectorateSnapshots,governanceEvents,governanceProposalVotes,governanceVoteEvents,projects,remoteJobEvents,remoteJobs,teamApiKeys,teamStorageLocators } from '../governance/policy/governance-electorate-snapshots.ts';
import { authProviderStates,authReauthenticationGrants,treeDxDeployments,treeDxMirrors,treeDxProjectLibraries,treeDxShares,userNotificationGlobalContentTypes,userNotificationPreferences,userNotificationProjectContentTypes,userNotificationProjectOverrides,userPersonalThemes,userPreferences } from '../projects/knowledge/tree-dx-project-libraries.ts';
import { agentMessages,agentRuns,apiTokens,auditEvents,authSessions,contactSubmissions,deviceCodes,permissions,rolePermissions,roles,runtimeEnvelopes,serviceCredentials,subscribers,teamMemberships,teamRoleBindings,teams,userEmailAddresses,userIdentities,userRoleBindings,users,webSessions } from './subscribers.ts';
import { feedbackAttachments,feedbackExportItems,feedbackExports,feedbackStatusEvents,feedbackSubmissions } from './feedback.ts';

export const MarketSchema = {
	agentLabViewState,
	subscribers,
	agentRuns,
	agentMessages,
	contactSubmissions,
	feedbackSubmissions,
	feedbackAttachments,
	feedbackStatusEvents,
	feedbackExports,
	feedbackExportItems,
	runtimeEnvelopes,
	users,
	userIdentities,
	userEmailAddresses,
	roles,
	permissions,
	rolePermissions,
	userRoleBindings,
	apiTokens,
	serviceCredentials,
	authSessions,
	auditEvents,
	deviceCodes,
	teams,
	teamMemberships,
	teamRoleBindings,
	webSessions,
	commonsParticipants,
	commonsQuestions,
	commonsProposals,
	commonsWeightSnapshots,
	commonsProposalBackings,
	commonsProposalVotes,
	commonsDelegations,
	commonsDecisions,
	commonsGovernanceEvents,
	teamGovernancePolicies,
	projectGovernancePolicies,
	governanceProposals,
	governanceProposalVersions,
	governanceElectorateSnapshots,
	governanceProposalVotes,
	governanceVoteEvents,
	governanceDelegations,
	governanceDecisions,
	governanceEvents,
	projects,
	teamApiKeys,
	entitlements,
	remoteJobs,
	remoteJobEvents,
	teamStorageLocators,
	catalogItems,
	catalogArtifactVersions,
	catalogItemCollaborators,
	commerceVendors,
	commerceProducts,
	commerceOwnershipRecords,
	commerceStewardshipAssignments,
	commerceContributions,
	commerceGovernancePolicies,
	commerceOwnershipTransfers,
	commerceProductVersions,
	commerceOffers,
	commercePrices,
	commerceGovernanceEvents,
	commerceCarts,
	commerceCartItems,
	commerceCheckouts,
	commerceOrders,
	commerceOrderItems,
	commercePaymentGroups,
	commerceSubscriptions,
	commerceEntitlements,
	commerceBuyerStripeCustomers,
	commerceRefunds,
	commerceFulfillmentEvents,
	commerceServiceRequests,
	commerceServiceQuotes,
	commerceServiceContracts,
	commerceServiceEvents,
	commerceCapacityListings,
	commerceCapacityListingInquiries,
	commerceWebhookEvents,
	projectSummarySnapshots,
	teamInboxItems,
	betterAuthUser,
	betterAuthSession,
	betterAuthAccount,
	betterAuthVerification,
	teamServiceConnections,
	teamServiceCapabilityBindings,
	teamServiceCredentialProfiles,
	teamVaults,
	userVaultKeys,
	teamVaultGrants,
	credentialEnvelopes,
	externalVaultBindings,
	secretOperationLeases,
	providerCredentialAuthorities,
	projectRemoteRepositoryBindings,
	projectWorkflowOperations,
	workflowOperationRuns,
	remoteGitOperationGrants,
	remoteCredentialDeliveries,
	providerWebhookDeliveries,
	providerConnectorAuthorizations,
	workflowConfigurationRecords,
	workflowConfigurationDeliveries,
	teamInvites,
	capacityProviders,
	capacityExecutionProviders,
	capacityProviderLanes,
	teamCapacityRegistrationKeys,
	capacityProviderRegistrationRequests,
	capacityProviderTeamMemberships,
	capacityProviderTeamCredentials,
	capacityProviderAccessTokens,
	capacityProviderProofNonces,
	capacityProviderRegistrationRateLimits,
	capacityAuditEvents,
	capacityOperationReceipts,
	capacityGrants,
	capacityReservations,
	capacityAdmissionCounters,
	capacityReservationCounterClaims,
	capacityLedgerEntries,
	capacityUsageActuals,
	approvalRequests,
	bookCollections,
	knowledgeAuthoringWorkspaces,
	knowledgePackBuilds,
	knowledgePublications,
	knowledgeReviewComments,
	knowledgeReviews,
	knowledgeWorkspacePresence,
	hubRepositories,
	hubContentSources,
	treeDxInstances,
	treeDxProjectLibraries,
	treeDxMirrors,
	treeDxShares,
	treeDxDeployments,
	userPreferences,
	authProviderStates,
	authReauthenticationGrants,
	userPersonalThemes,
	userNotificationPreferences,
	userNotificationGlobalContentTypes,
	userNotificationProjectOverrides,
	userNotificationProjectContentTypes,
	notificationEvents,
	userNotifications,
	sessionEvents,
	notificationEmailDeliveries,
	legacyCreditConversionProfiles,
	seedRuns,
	runtimeRecords,
	cursorState,
	leaseState,
	messageQueue,
	capacityAllocationSets,
	projectAgentClasses,
	providerAvailabilitySessions,
	decisionPlanningStatuses,
	planningInputRequests,
	decisionExecutionInputs,
	structuredAgentEstimates,
	decisionAssignmentGraphs,
	deliverableContracts,
	deliverableManifests,
	capacityWorkdayRuns,
	capacityWorkdayEvents,
	capacityWorkdaySchedules,
	workdayCapacityEnvelopes,
	capacityProviderAssignments,
	agentModeRuns,
	agentFallbackOutputs,
	agentCapacityPlans,
	treeDxProxyHandles,
	platformOperations,
	platformOperationEvents,
	marketOperationRunners,
	marketAuthCredentials,
	marketAuthPasswordResets,
};

export type MarketDrizzleSchema = typeof MarketSchema;
