import type { TreeseedOperationMetadata } from './operations-types.ts';

function operation(spec: TreeseedOperationMetadata): TreeseedOperationMetadata {
	return spec;
}

const workspaceCommand = (name: 'status' | 'link' | 'unlink') => `workspace${':'}${name}`;

export const TRESEED_OPERATION_SPECS: TreeseedOperationMetadata[] = [
	operation({ id: 'workspace.status', name: 'status', aliases: [], group: 'Workflow', summary: 'Show Treeseed project health and the current task state.', description: 'Report branch/task state, runtime readiness, preview/deploy state, auth readiness, and recommended next operations.', provider: 'default', related: ['tasks', 'switch', 'config'] }),
	operation({ id: 'branch.tasks', name: 'tasks', aliases: [], group: 'Workflow', summary: 'List task branches plus package branch alignment.', description: 'List task branches from market and checked-out package repos, including preview metadata and branch/pointer alignment state.', provider: 'default', related: ['status', 'switch', 'close'] }),
	operation({ id: 'branch.switch', name: 'switch', aliases: [], group: 'Workflow', summary: 'Create or resume a recursive task branch.', description: 'Create or resume the task branch in market and any checked-out package repos, with optional preview provisioning.', provider: 'default', related: ['tasks', 'dev', 'save'] }),
	operation({ id: 'branch.save', name: 'save', aliases: [], group: 'Workflow', summary: 'Recursively verify, commit, and push the current task checkpoint.', description: 'Save dirty package repos in dependency order, then verify, commit, push, and optionally refresh preview for market.', provider: 'default', related: ['switch', 'stage', 'status'] }),
	operation({ id: 'branch.close', name: 'close', aliases: [], group: 'Workflow', summary: 'Recursively archive and delete a task branch.', description: 'Auto-save if needed, clean preview resources, create deprecated tags, and remove the task branch across market and checked-out package repos.', provider: 'default', related: ['tasks', 'switch', 'stage'] }),
	operation({ id: 'branch.stage', name: 'stage', aliases: [], group: 'Workflow', summary: 'Squash a task branch into staging across market and packages.', description: 'Auto-save if needed, squash-merge package task branches into staging first, update market submodule pointers, then squash-merge market into staging and clean up the task branch.', provider: 'default', related: ['save', 'release', 'close'] }),
	operation({ id: 'workspace.resume', name: 'resume', aliases: [], group: 'Workflow', summary: 'Resume an interrupted workflow run.', description: 'Continue a failed journaled workflow run from its next incomplete step after validating current workspace preconditions.', provider: 'default', related: ['recover', 'status'] }),
	operation({ id: 'workspace.recover', name: 'recover', aliases: [], group: 'Workflow', summary: 'Inspect active workflow locks and interrupted runs.', description: 'List active workflow locks, resumable interrupted runs, and the exact commands needed to continue or recover the workspace state.', provider: 'default', related: ['resume', 'status'] }),
	operation({ id: 'workspace.links.status', name: workspaceCommand('status'), aliases: [], group: 'Utilities', summary: 'Inspect local workspace dependency links.', description: 'Inspect whether Treeseed package dependencies are linked to local package checkouts or resolved through deployment references.', provider: 'default', related: ['dev', 'save'] }),
	operation({ id: 'workspace.links.link', name: workspaceCommand('link'), aliases: [], group: 'Utilities', summary: 'Link local Treeseed workspace packages.', description: 'Create local node_modules links from internal Treeseed dependencies to checked-out package repositories for integrated development.', provider: 'default', related: ['dev', workspaceCommand('status')] }),
	operation({ id: 'workspace.links.unlink', name: workspaceCommand('unlink'), aliases: [], group: 'Utilities', summary: 'Remove managed local workspace package links.', description: 'Remove Treeseed-managed local workspace links before deployment-style installs or lockfile repair.', provider: 'default', related: ['save', workspaceCommand('status')] }),
	operation({ id: 'deploy.rollback', name: 'rollback', aliases: [], group: 'Workflow', summary: 'Roll back staging or production to a recorded deployment.', description: 'Redeploy a previously recorded staging or production commit using a temporary checkout of that revision.', provider: 'default', related: ['status', 'release'] }),
	operation({ id: 'workspace.doctor', name: 'doctor', aliases: [], group: 'Validation', summary: 'Diagnose Treeseed tooling, auth, and workflow readiness.', description: 'Collect doctor-style diagnostics for workspace readiness and optional safe repairs.', provider: 'default', related: ['status', 'config'] }),
	operation({ id: 'workspace.install', name: 'install', aliases: [], group: 'Utilities', summary: 'Install Treeseed-managed local dependencies.', description: 'Install or repair Treeseed-managed CLI dependencies including GitHub CLI, Wrangler, Railway, Copilot, and optional gh-act support.', provider: 'default', related: ['config', 'doctor'] }),
	operation({ id: 'workspace.tools', name: 'tools', aliases: [], group: 'Utilities', summary: 'Report Treeseed-managed executable locations.', description: 'Inspect Treeseed-managed executable paths, invocation commands, cache roots, and GitHub CLI authentication state without installing or mutating tools.', provider: 'default', related: ['install', 'doctor'] }),
	operation({ id: 'auth.login', name: 'auth:login', aliases: [], group: 'Validation', summary: 'Authenticate against the configured Treeseed API.', description: 'Start the device login flow against the active Treeseed API host and persist the returned session locally.', provider: 'default', related: ['auth:check', 'auth:whoami', 'auth:logout'] }),
	operation({ id: 'auth.logout', name: 'auth:logout', aliases: [], group: 'Validation', summary: 'Clear locally stored Treeseed API credentials.', description: 'Remove the persisted local device-flow session for the active Treeseed API host.', provider: 'default', related: ['auth:login', 'auth:whoami'] }),
	operation({ id: 'auth.whoami', name: 'auth:whoami', aliases: [], group: 'Validation', summary: 'Inspect the active Treeseed API identity.', description: 'Use the persisted local remote session to query the active Treeseed API principal.', provider: 'default', related: ['auth:login', 'status'] }),
	operation({ id: 'secrets.status', name: 'secrets:status', aliases: [], group: 'Validation', summary: 'Inspect the local wrapped machine-key session.', description: 'Report whether the local key agent is running, whether the wrapped machine key exists, and whether the secret session is unlocked.', provider: 'default', related: ['secrets:unlock', 'secrets:lock'] }),
	operation({ id: 'secrets.unlock', name: 'secrets:unlock', aliases: [], group: 'Validation', summary: 'Unlock the local Treeseed secret session.', description: 'Unlock the host-local Treeseed key agent from an interactive passphrase prompt or an explicit startup passphrase env var.', provider: 'default', related: ['secrets:status', 'secrets:lock', 'secrets:migrate-key'] }),
	operation({ id: 'secrets.lock', name: 'secrets:lock', aliases: [], group: 'Validation', summary: 'Lock the local Treeseed secret session.', description: 'Clear the in-memory machine key from the host-local Treeseed key agent.', provider: 'default', related: ['secrets:status', 'secrets:unlock'] }),
	operation({ id: 'secrets.migrateKey', name: 'secrets:migrate-key', aliases: [], group: 'Validation', summary: 'Wrap a legacy plaintext machine key.', description: 'Replace the legacy plaintext machine-key file with the wrapped passphrase-protected format used by the Treeseed key agent.', provider: 'default', related: ['secrets:unlock', 'secrets:rotate-passphrase'] }),
	operation({ id: 'secrets.rotatePassphrase', name: 'secrets:rotate-passphrase', aliases: [], group: 'Validation', summary: 'Rotate the wrapped machine-key passphrase.', description: 'Re-wrap the existing machine key with a newly entered passphrase without changing the underlying machine key.', provider: 'default', related: ['secrets:unlock', 'secrets:rotate-machine-key'] }),
	operation({ id: 'secrets.rotateMachineKey', name: 'secrets:rotate-machine-key', aliases: [], group: 'Validation', summary: 'Rotate the encrypted machine key itself.', description: 'Generate a new machine key, re-encrypt stored local secrets and remote auth sessions, and re-wrap the result with the configured passphrase.', provider: 'default', related: ['config', 'secrets:rotate-passphrase'] }),
	operation({ id: 'template.list', name: 'template', aliases: [], group: 'Utilities', summary: 'List, inspect, and validate templates from the Treeseed catalog.', description: 'Use remote template metadata to list templates, show one template, or validate local template artifacts.', provider: 'default', related: ['init', 'sync'] }),
	operation({ id: 'template.sync', name: 'sync', aliases: [], group: 'Validation', summary: 'Validate or reconcile the managed template surface for the current site.', description: 'Use remote template metadata plus the local scaffold artifact to check or apply updates to the managed scaffold surface.', provider: 'default', related: ['template', 'init', 'status'] }),
	operation({ id: 'project.init', name: 'init', aliases: [], group: 'Workflow', summary: 'Scaffold a new Treeseed tenant project.', description: 'Create a new Treeseed tenant directory from a remote-catalog template backed by the packaged scaffold artifact.', provider: 'default', related: ['config', 'switch', 'dev'] }),
	operation({ id: 'project.config', name: 'config', aliases: [], group: 'Workflow', summary: 'Configure and test the runtime foundation.', description: 'Apply safe repairs, collect environment values, write local machine config, initialize environments, sync providers, and run doctor-style checks.', provider: 'default', related: ['status', 'switch', 'dev'] }),
	operation({ id: 'project.export', name: 'export', aliases: [], group: 'Utilities', summary: 'Export a Markdown snapshot of the current codebase.', description: 'Generate a Markdown codebase snapshot for the selected directory using the SDK-owned repomix integration and store it under .treeseed/exports.', provider: 'default', related: ['status', 'config'] }),
	operation({ id: 'deploy.release', name: 'release', aliases: [], group: 'Workflow', summary: 'Release changed packages and market from staging to production.', description: 'Select changed packages plus dependents, validate publish workflows, release packages first, then promote market from staging to main with aligned package pointers.', provider: 'default', related: ['stage', 'status', 'rollback'] }),
	operation({ id: 'deploy.destroy', name: 'destroy', aliases: [], group: 'Workflow', summary: 'Destroy a persistent environment and its local state.', description: 'Delete the selected persistent environment resources and remove the local deploy state after confirmation.', provider: 'default', related: ['config', 'status'] }),
	operation({ id: 'local.dev', name: 'dev', aliases: [], group: 'Local Development', summary: 'Start the unified local Treeseed development environment.', description: 'Start the unified local Treeseed development environment.', provider: 'default' }),
	operation({ id: 'local.devWatch', name: 'dev:watch', aliases: [], group: 'Local Development', summary: 'Start local development with rebuild and watch mode.', description: 'Start local development with rebuild and watch mode.', provider: 'default' }),
	operation({ id: 'local.build', name: 'build', aliases: [], group: 'Local Development', summary: 'Build the tenant site and generated worker artifacts.', description: 'Build the tenant site and generated worker artifacts.', provider: 'default' }),
	operation({ id: 'local.check', name: 'check', aliases: [], group: 'Local Development', summary: 'Run the tenant check flow.', description: 'Run the tenant check flow.', provider: 'default' }),
	operation({ id: 'local.preview', name: 'preview', aliases: [], group: 'Local Development', summary: 'Preview the built tenant site locally.', description: 'Preview the built tenant site locally.', provider: 'default' }),
	operation({ id: 'local.lint', name: 'lint', aliases: [], group: 'Validation', summary: 'Run Treeseed lint checks.', description: 'Run Treeseed lint checks.', provider: 'default' }),
	operation({ id: 'local.test', name: 'test', aliases: [], group: 'Validation', summary: 'Run Treeseed tests.', description: 'Run Treeseed tests.', provider: 'default' }),
	operation({ id: 'validation.testUnit', name: 'test:unit', aliases: [], group: 'Validation', summary: 'Run workspace unit tests in dependency order.', description: 'Run workspace unit tests in dependency order.', provider: 'default' }),
	operation({ id: 'validation.preflight', name: 'preflight', aliases: [], group: 'Validation', summary: 'Check local prerequisites and authentication state.', description: 'Check local prerequisites and authentication state.', provider: 'default' }),
	operation({ id: 'validation.authCheck', name: 'auth:check', aliases: [], group: 'Validation', summary: 'Check local prerequisites and require authenticated tooling.', description: 'Check local prerequisites and require authenticated tooling.', provider: 'default' }),
	operation({ id: 'release.testE2e', name: 'test:e2e', aliases: [], group: 'Release Utilities', summary: 'Run Treeseed end-to-end command tests.', description: 'Run Treeseed end-to-end command tests.', provider: 'default' }),
	operation({ id: 'release.testE2eLocal', name: 'test:e2e:local', aliases: [], group: 'Release Utilities', summary: 'Run local-mode Treeseed end-to-end command tests.', description: 'Run local-mode Treeseed end-to-end command tests.', provider: 'default' }),
	operation({ id: 'release.testE2eStaging', name: 'test:e2e:staging', aliases: [], group: 'Release Utilities', summary: 'Run staging-mode Treeseed end-to-end command tests.', description: 'Run staging-mode Treeseed end-to-end command tests.', provider: 'default' }),
	operation({ id: 'release.testE2eFull', name: 'test:e2e:full', aliases: [], group: 'Release Utilities', summary: 'Run the full Treeseed end-to-end command suite.', description: 'Run the full Treeseed end-to-end command suite.', provider: 'default' }),
	operation({ id: 'release.testFast', name: 'test:release', aliases: [], group: 'Release Utilities', summary: 'Run the fast release verification path.', description: 'Run the fast release verification path.', provider: 'default' }),
	operation({ id: 'release.verify', name: 'test:release:full', aliases: ['release:verify'], group: 'Release Utilities', summary: 'Run the full release verification path.', description: 'Run the full release verification path.', provider: 'default' }),
	operation({ id: 'release.publishChanged', name: 'release:publish:changed', aliases: [], group: 'Release Utilities', summary: 'Publish changed Treeseed workspace packages.', description: 'Publish changed Treeseed workspace packages.', provider: 'default' }),
	operation({ id: 'tools.astro', name: 'astro', aliases: [], group: 'Passthrough', summary: 'Pass through to the packaged Astro CLI wrapper.', description: 'Pass through to the packaged Astro CLI wrapper.', provider: 'default' }),
	operation({ id: 'services.mailpitUp', name: 'mailpit:up', aliases: [], group: 'Utilities', summary: 'Start the package-managed Mailpit service.', description: 'Start the package-managed Mailpit service.', provider: 'default' }),
	operation({ id: 'services.mailpitDown', name: 'mailpit:down', aliases: [], group: 'Utilities', summary: 'Stop the package-managed Mailpit service.', description: 'Stop the package-managed Mailpit service.', provider: 'default' }),
	operation({ id: 'services.mailpitLogs', name: 'mailpit:logs', aliases: [], group: 'Utilities', summary: 'Show Mailpit logs.', description: 'Show Mailpit logs.', provider: 'default' }),
	operation({ id: 'data.d1MigrateLocal', name: 'd1:migrate:local', aliases: [], group: 'Utilities', summary: 'Apply local D1 migrations.', description: 'Apply local D1 migrations.', provider: 'default' }),
	operation({ id: 'content.cleanupMarkdown', name: 'cleanup:markdown', aliases: [], group: 'Utilities', summary: 'Normalize Markdown and MDX files.', description: 'Normalize Markdown and MDX files.', provider: 'default' }),
	operation({ id: 'content.cleanupMarkdownCheck', name: 'cleanup:markdown:check', aliases: [], group: 'Utilities', summary: 'Check Markdown and MDX formatting without rewriting files.', description: 'Check Markdown and MDX formatting without rewriting files.', provider: 'default' }),
	operation({ id: 'tools.starlightPatch', name: 'starlight:patch', aliases: [], group: 'Utilities', summary: 'Apply the Starlight content path patch.', description: 'Apply the Starlight content path patch.', provider: 'default' }),
];

export const TRESEED_OPERATION_INDEX = new Map<string, TreeseedOperationMetadata>();
for (const spec of TRESEED_OPERATION_SPECS) {
	TRESEED_OPERATION_INDEX.set(spec.name, spec);
	for (const alias of spec.aliases) {
		TRESEED_OPERATION_INDEX.set(alias, spec);
	}
}

export function findTreeseedOperation(name: string | null | undefined) {
	if (!name) return null;
	return TRESEED_OPERATION_INDEX.get(name) ?? null;
}

export function listTreeseedOperationNames() {
	return [...new Set(TRESEED_OPERATION_SPECS.map((spec) => spec.name))];
}
