import type { TreeseedOperationSpec } from './operations-types.ts';

function command(spec: TreeseedOperationSpec): TreeseedOperationSpec {
	return spec;
}

export const TRESEED_OPERATION_SPECS: TreeseedOperationSpec[] = [
	command({
		id: 'workspace.setup',
		name: 'setup',
		aliases: [],
		group: 'Workflow',
		summary: 'Bootstrap the local Treeseed workspace and environments.',
		description: 'Run safe local repairs, initialize local configuration, and prepare the selected environments for development and release work.',
		usage: 'treeseed setup [--environment <local|staging|prod>]... [--sync <none|github|cloudflare|all>] [--json]',
		options: [
			{ name: 'environment', flags: '--environment <scope>', description: 'Limit setup to local, staging, or prod.', kind: 'enum', repeatable: true, values: ['local', 'staging', 'prod'] },
			{ name: 'sync', flags: '--sync <mode>', description: 'Optionally sync GitHub or Cloudflare settings.', kind: 'enum', values: ['none', 'github', 'cloudflare', 'all'] },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed setup', 'treeseed setup --environment local --environment staging'],
		related: ['doctor', 'prepare', 'dev'],
		executionMode: 'handler',
		handlerName: 'setup',
	}),
	command({
		id: 'branch.work',
		name: 'work',
		aliases: [],
		group: 'Workflow',
		summary: 'Create or resume a feature branch from the workflow state.',
		description: 'Create a new feature branch from staging or resume an existing branch, optionally provisioning a preview deployment.',
		usage: 'treeseed work <branch-name> [--preview] [--json]',
		arguments: [{ name: 'branch-name', description: 'Feature branch to create or resume.', required: true }],
		options: [
			{ name: 'preview', flags: '--preview', description: 'Provision or refresh a branch-scoped Cloudflare preview environment.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed work feature/search-improvements', 'treeseed work feature/search-improvements --preview'],
		related: ['ship', 'publish', 'teardown'],
		executionMode: 'handler',
		handlerName: 'work',
	}),
	command({
		id: 'branch.ship',
		name: 'ship',
		aliases: [],
		group: 'Workflow',
		summary: 'Persist and publish the current branch at the intent level.',
		description: 'Commit and push the current branch, refreshing a branch preview when one is enabled.',
		usage: 'treeseed ship [--hotfix] <message> [--json]',
		arguments: [{ name: 'message', description: 'Git commit message for the ship operation.', required: true, kind: 'message_tail' }],
		options: [
			{ name: 'hotfix', flags: '--hotfix', description: 'Allow ship on main for an explicit hotfix.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed ship "feat: add search filters"'],
		related: ['work', 'publish', 'promote'],
		executionMode: 'handler',
		handlerName: 'ship',
	}),
	command({
		id: 'workspace.prepare',
		name: 'prepare',
		aliases: [],
		group: 'Workflow',
		summary: 'Prepare persistent environments for later publication.',
		description: 'Alias for persistent environment setup and validation.',
		usage: 'treeseed prepare [--environment <local|staging|prod>]... [--sync <none|github|cloudflare|all>] [--json]',
		options: [
			{ name: 'environment', flags: '--environment <scope>', description: 'Limit preparation to local, staging, or prod.', kind: 'enum', repeatable: true, values: ['local', 'staging', 'prod'] },
			{ name: 'sync', flags: '--sync <mode>', description: 'Optionally sync GitHub or Cloudflare settings.', kind: 'enum', values: ['none', 'github', 'cloudflare', 'all'] },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed prepare --environment staging --environment prod'],
		related: ['setup', 'publish', 'config'],
		executionMode: 'handler',
		handlerName: 'prepare',
	}),
	command({
		id: 'deploy.publish',
		name: 'publish',
		aliases: [],
		group: 'Workflow',
		summary: 'Publish the current site or preview target.',
		description: 'Alias for environment or branch publication using an already initialized target.',
		usage: 'treeseed publish --environment <local|staging|prod> [--dry-run] [--only <migrate|build|publish>] [--json]\n  treeseed publish --target-branch <branch> [--dry-run] [--only <migrate|build|publish>] [--json]',
		options: [
			{ name: 'environment', flags: '--environment <scope>', description: 'Publish to local, staging, or prod.', kind: 'enum', values: ['local', 'staging', 'prod'] },
			{ name: 'targetBranch', flags: '--target-branch <branch>', description: 'Publish a branch preview target.', kind: 'string' },
			{ name: 'dryRun', flags: '--dry-run', description: 'Show what would run without publishing changes.', kind: 'boolean' },
			{ name: 'only', flags: '--only <step>', description: 'Limit execution to migrate, build, or publish.', kind: 'enum', values: ['migrate', 'build', 'publish'] },
			{ name: 'name', flags: '--name <label>', description: 'Attach a friendly label to the publish run.', kind: 'string' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed publish --environment staging', 'treeseed publish --target-branch feature/search-improvements'],
		related: ['prepare', 'ship', 'rollback'],
		executionMode: 'handler',
		handlerName: 'publish',
	}),
	command({
		id: 'deploy.promote',
		name: 'promote',
		aliases: [],
		group: 'Workflow',
		summary: 'Promote staging to production with a version bump.',
		description: 'Alias for the production promotion workflow built on top of Treeseed release.',
		usage: 'treeseed promote --major|--minor|--patch [--json]',
		options: [
			{ name: 'major', flags: '--major', description: 'Bump to the next major version.', kind: 'boolean' },
			{ name: 'minor', flags: '--minor', description: 'Bump to the next minor version.', kind: 'boolean' },
			{ name: 'patch', flags: '--patch', description: 'Bump to the next patch version.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed promote --patch'],
		related: ['publish', 'rollback', 'release'],
		executionMode: 'handler',
		handlerName: 'promote',
	}),
	command({
		id: 'deploy.rollback',
		name: 'rollback',
		aliases: [],
		group: 'Workflow',
		summary: 'Roll back staging or production to a recorded deployment.',
		description: 'Redeploy a previously recorded staging or production commit using a temporary checkout of that revision.',
		usage: 'treeseed rollback <staging|prod> [--to <deploy-id|commit>] [--json]',
		arguments: [{ name: 'environment', description: 'The persistent environment to roll back.', required: true }],
		options: [
			{ name: 'to', flags: '--to <deploy-id|commit>', description: 'Explicit commit to roll back to. Defaults to the previous recorded deployment when omitted.', kind: 'string' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed rollback staging', 'treeseed rollback prod --to abc1234'],
		related: ['publish', 'promote', 'status'],
		executionMode: 'handler',
		handlerName: 'rollback',
	}),
	command({
		id: 'branch.teardown',
		name: 'teardown',
		aliases: [],
		group: 'Workflow',
		summary: 'Clean up a feature branch or destroy a persistent environment.',
		description: 'Close the current feature branch or destroy a selected persistent environment when `--environment` is provided.',
		usage: 'treeseed teardown [--environment <local|staging|prod>] [--dry-run] [--json]',
		options: [
			{ name: 'environment', flags: '--environment <scope>', description: 'Destroy a persistent environment instead of closing the current feature branch.', kind: 'enum', values: ['local', 'staging', 'prod'] },
			{ name: 'dryRun', flags: '--dry-run', description: 'Preview the teardown operation without mutating state.', kind: 'boolean' },
			{ name: 'force', flags: '--force', description: 'Force worker deletion when supported.', kind: 'boolean' },
			{ name: 'skipConfirmation', flags: '--skip-confirmation', description: 'Skip the interactive confirmation prompt for persistent destroys.', kind: 'boolean' },
			{ name: 'confirm', flags: '--confirm <slug>', description: 'Provide the expected slug confirmation non-interactively.', kind: 'string' },
			{ name: 'removeBuildArtifacts', flags: '--remove-build-artifacts', description: 'Also remove local build artifacts after destroy.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed teardown', 'treeseed teardown --environment staging --dry-run'],
		related: ['work', 'rollback', 'destroy'],
		executionMode: 'handler',
		handlerName: 'teardown',
	}),
	command({
		id: 'workspace.continue',
		name: 'continue',
		aliases: [],
		group: 'Workflow',
		summary: 'Show the safest next Treeseed step from the current state.',
		description: 'Use the workflow-state resolver to return the top recommended next action.',
		usage: 'treeseed continue [--json]',
		options: [{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' }],
		examples: ['treeseed continue'],
		related: ['status', 'next', 'doctor'],
		executionMode: 'handler',
		handlerName: 'continue',
	}),
	command({
		id: 'workspace.status',
		name: 'status',
		aliases: [],
		group: 'Workflow',
		summary: 'Show the current Treeseed workflow state.',
		description: 'Report the current branch, environment mapping, initialization state, preview state, and auth readiness.',
		usage: 'treeseed status [--json]',
		options: [{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' }],
		examples: ['treeseed status', 'treeseed status --json'],
		related: ['next', 'continue', 'doctor'],
		executionMode: 'handler',
		handlerName: 'status',
	}),
	command({
		id: 'workspace.next',
		name: 'next',
		aliases: [],
		group: 'Workflow',
		summary: 'Recommend the next Treeseed commands for the current state.',
		description: 'Inspect the current branch and environment state, then suggest the most likely next commands.',
		usage: 'treeseed next [--json]',
		options: [{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' }],
		examples: ['treeseed next', 'treeseed next --json'],
		related: ['status', 'continue', 'work'],
		executionMode: 'handler',
		handlerName: 'next',
	}),
	command({
		id: 'workspace.doctor',
		name: 'doctor',
		aliases: [],
		group: 'Validation',
		summary: 'Diagnose Treeseed tooling, auth, and workflow readiness.',
		description: 'Validate local prerequisites, auth state, repository shape, and generated Treeseed files needed for development and release work.',
		usage: 'treeseed doctor [--fix] [--json]',
		options: [
			{ name: 'fix', flags: '--fix', description: 'Apply safe local repairs before rerunning diagnostics.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed doctor', 'treeseed doctor --fix --json'],
		related: ['status', 'next', 'setup'],
		executionMode: 'handler',
		handlerName: 'doctor',
	}),
	command({
		id: 'template.list',
		name: 'template',
		aliases: [],
		group: 'Utilities',
		summary: 'List, inspect, and validate templates from the remote Treeseed catalog.',
		description: 'Use the configured Treeseed template API to list templates, show details for one template, or validate locally shipped template artifacts against the remote catalog.',
		usage: 'treeseed template [list|show|validate] [id]',
		arguments: [
			{ name: 'action', description: 'Template action: list, show, or validate.', required: false },
			{ name: 'id', description: 'Template id for show or validate.', required: false },
		],
		examples: ['treeseed template', 'treeseed template list', 'treeseed template show starter-basic', 'treeseed template validate'],
		related: ['init', 'sync'],
		executionMode: 'handler',
		handlerName: 'template',
	}),
	command({
		id: 'template.sync',
		name: 'sync',
		aliases: [],
		group: 'Validation',
		summary: 'Validate or reconcile the managed template surface for the current site.',
		description: 'Use remote template metadata plus the local CLI template artifact to check or apply updates to the narrow core-managed scaffold surface.',
		usage: 'treeseed sync [--check]',
		options: [{ name: 'check', flags: '--check', description: 'Report managed-surface drift without changing files.', kind: 'boolean' }],
		examples: ['treeseed sync --check', 'treeseed sync'],
		related: ['template', 'init', 'doctor'],
		executionMode: 'handler',
		handlerName: 'sync',
	}),
	command({
		id: 'project.init',
		name: 'init',
		aliases: [],
		group: 'Workflow',
		summary: 'Scaffold a new Treeseed tenant project.',
		description: 'Create a new Treeseed tenant directory from a remote-catalog template backed by the local CLI scaffold artifact and print recommended next steps.',
		usage: 'treeseed init <directory> [--template <starter-id>] [--name <site-name>] [--slug <slug>] [--site-url <url>] [--contact-email <email>] [--repo <url>] [--discord <url>]',
		arguments: [{ name: 'directory', description: 'Target directory for the new tenant.', required: true }],
		options: [
			{ name: 'template', flags: '--template <starter-id>', description: 'Select the starter template id to generate. Defaults to starter-basic.', kind: 'string' },
			{ name: 'name', flags: '--name <site-name>', description: 'Override the generated site name.', kind: 'string' },
			{ name: 'slug', flags: '--slug <slug>', description: 'Override the generated package and tenant slug.', kind: 'string' },
			{ name: 'siteUrl', flags: '--site-url <url>', description: 'Set the initial public site URL.', kind: 'string' },
			{ name: 'contactEmail', flags: '--contact-email <email>', description: 'Set the site contact address.', kind: 'string' },
			{ name: 'repo', flags: '--repo <url>', description: 'Set the repository URL.', kind: 'string' },
			{ name: 'discord', flags: '--discord <url>', description: 'Set the Discord/community URL.', kind: 'string' },
		],
		examples: ['treeseed init docs-site --template starter-basic --name "Docs Site" --site-url https://docs.example.com'],
		notes: ['Runs outside an existing repo or from any branch.'],
		related: ['config', 'start', 'deploy'],
		executionMode: 'handler',
		handlerName: 'init',
	}),
	command({
		id: 'project.config',
		name: 'config',
		aliases: [],
		group: 'Workflow',
		summary: 'Validate and initialize persistent environments.',
		description: 'Collect environment values, write local machine config, generate local env files, and perform phase-1 initialization.',
		usage: 'treeseed config [--environment <local|staging|prod>]... [--sync <none|github|cloudflare|all>]',
		options: [
			{ name: 'environment', flags: '--environment <scope>', description: 'Limit configuration to local, staging, or prod.', kind: 'enum', repeatable: true, values: ['local', 'staging', 'prod'] },
			{ name: 'sync', flags: '--sync <mode>', description: 'Optionally sync GitHub or Cloudflare settings.', kind: 'enum', values: ['none', 'github', 'cloudflare', 'all'] },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed config --environment local', 'treeseed config --environment staging --environment prod', 'treeseed config --environment prod --sync all'],
		notes: ['Compatibility command. Prefer `treeseed prepare` or `treeseed setup` for the simplified workflow.', 'Does not create branch preview deployments.'],
		related: ['prepare', 'setup', 'publish'],
		executionMode: 'handler',
		handlerName: 'config',
	}),
	command({
		id: 'branch.start',
		name: 'start',
		aliases: [],
		group: 'Workflow',
		summary: 'Create a feature branch from the latest staging commit.',
		description: 'Switch to the latest staging branch, create a feature branch, and optionally provision a preview deployment.',
		usage: 'treeseed start <branch-name> [--preview]',
		arguments: [{ name: 'branch-name', description: 'Feature branch to create from staging.', required: true }],
		options: [
			{ name: 'preview', flags: '--preview', description: 'Create and publish a branch-scoped Cloudflare preview environment.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed start feature/search-improvements', 'treeseed start feature/search-improvements --preview'],
		notes: ['Compatibility command. Prefer `treeseed work` for the simplified workflow.', 'Refuses to run with a dirty worktree or if the branch already exists.'],
		related: ['work', 'ship', 'publish'],
		executionMode: 'handler',
		handlerName: 'start',
	}),
	command({
		id: 'branch.close',
		name: 'close',
		aliases: [],
		group: 'Workflow',
		summary: 'Merge the current feature branch into staging and clean it up.',
		description: 'Validate the current feature branch, merge it into staging, and remove any preview artifacts for that branch.',
		usage: 'treeseed close',
		options: [{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' }],
		examples: ['treeseed close'],
		notes: ['Compatibility command. Prefer `treeseed teardown` for the simplified workflow.', 'Only works on feature branches.', 'Refuses to run on staging or main.'],
		related: ['work', 'ship', 'teardown'],
		executionMode: 'handler',
		handlerName: 'close',
	}),
	command({
		id: 'deploy.deploy',
		name: 'deploy',
		aliases: [],
		group: 'Workflow',
		summary: 'Run phase-2 deploy for an initialized target.',
		description: 'Validate readiness, run migrations, build, and publish to an initialized persistent environment or branch preview.',
		usage: 'treeseed deploy --environment <local|staging|prod> [--dry-run] [--only <migrate|build|publish>] [--name <label>]\n  treeseed deploy --target-branch <branch> [--dry-run] [--only <migrate|build|publish>]',
		options: [
			{ name: 'environment', flags: '--environment <scope>', description: 'Deploy to local, staging, or prod.', kind: 'enum', values: ['local', 'staging', 'prod'] },
			{ name: 'targetBranch', flags: '--target-branch <branch>', description: 'Deploy a previously initialized branch preview target.', kind: 'string' },
			{ name: 'dryRun', flags: '--dry-run', description: 'Show what would run without publishing changes.', kind: 'boolean' },
			{ name: 'only', flags: '--only <step>', description: 'Limit execution to migrate, build, or publish.', kind: 'enum', values: ['migrate', 'build', 'publish'] },
			{ name: 'name', flags: '--name <label>', description: 'Attach a friendly label to the deploy run.', kind: 'string' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed deploy --environment staging', 'treeseed deploy --environment prod --dry-run', 'treeseed deploy --target-branch feature/search-improvements'],
		notes: ['Compatibility command. Prefer `treeseed publish` for the simplified workflow.', 'Persistent environments must already be initialized by treeseed config.', 'CI may infer staging from `staging` and production from `main`.'],
		related: ['publish', 'prepare', 'rollback'],
		executionMode: 'handler',
		handlerName: 'deploy',
	}),
	command({
		id: 'branch.save',
		name: 'save',
		aliases: [],
		group: 'Workflow',
		summary: 'Commit and push the current branch.',
		description: 'Run validation, create a git commit from the current branch, and push that branch without performing merges or releases.',
		usage: 'treeseed save [--hotfix] <message>',
		arguments: [{ name: 'message', description: 'Git commit message for the save operation.', required: true, kind: 'message_tail' }],
		options: [
			{ name: 'hotfix', flags: '--hotfix', description: 'Allow save on main for an explicit hotfix.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed save "feat: add search filters"', 'treeseed save --hotfix "fix: unblock production form submit"'],
		notes: ['Compatibility command. Prefer `treeseed ship` for the simplified workflow.', 'Blocked on main unless --hotfix is provided.'],
		related: ['ship', 'work', 'promote'],
		executionMode: 'handler',
		handlerName: 'save',
	}),
	command({
		id: 'deploy.release',
		name: 'release',
		aliases: [],
		group: 'Workflow',
		summary: 'Promote staging to production with a version bump.',
		description: 'Validate staging, apply exactly one version bump, merge staging into main, and rely on CI to deploy production.',
		usage: 'treeseed release --major|--minor|--patch',
		options: [
			{ name: 'major', flags: '--major', description: 'Bump to the next major version.', kind: 'boolean' },
			{ name: 'minor', flags: '--minor', description: 'Bump to the next minor version.', kind: 'boolean' },
			{ name: 'patch', flags: '--patch', description: 'Bump to the next patch version.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed release --patch', 'treeseed release --minor'],
		notes: ['Compatibility command. Prefer `treeseed promote` for the simplified workflow.', 'Requires exactly one bump flag.'],
		related: ['promote', 'publish', 'rollback'],
		executionMode: 'handler',
		handlerName: 'release',
	}),
	command({
		id: 'deploy.destroy',
		name: 'destroy',
		aliases: [],
		group: 'Workflow',
		summary: 'Destroy a persistent environment and its local state.',
		description: 'Delete the selected persistent environment resources and remove the local deploy state after confirmation.',
		usage: 'treeseed destroy --environment <local|staging|prod> [--dry-run] [--force] [--skip-confirmation] [--confirm <slug>] [--remove-build-artifacts]',
		options: [
			{ name: 'environment', flags: '--environment <scope>', description: 'Select the persistent environment to destroy.', kind: 'enum', values: ['local', 'staging', 'prod'] },
			{ name: 'dryRun', flags: '--dry-run', description: 'Preview the destroy operation.', kind: 'boolean' },
			{ name: 'force', flags: '--force', description: 'Force worker deletion when supported.', kind: 'boolean' },
			{ name: 'skipConfirmation', flags: '--skip-confirmation', description: 'Skip the interactive confirmation prompt.', kind: 'boolean' },
			{ name: 'confirm', flags: '--confirm <slug>', description: 'Provide the expected slug confirmation non-interactively.', kind: 'string' },
			{ name: 'removeBuildArtifacts', flags: '--remove-build-artifacts', description: 'Also remove local build artifacts after destroy.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed destroy --environment staging --dry-run', 'treeseed destroy --environment prod --confirm example --skip-confirmation'],
		notes: ['Compatibility command. Prefer `treeseed teardown --environment ...` for the simplified workflow.', 'Only for persistent environments. Branch cleanup belongs to treeseed close.', 'This command is destructive and requires explicit confirmation.'],
		related: ['teardown', 'prepare', 'publish'],
		executionMode: 'handler',
		handlerName: 'destroy',
	}),
	command({ id: 'local.dev', name: 'dev', aliases: [], group: 'Local Development', summary: 'Start the unified local Treeseed development environment.', description: 'Start the unified local Treeseed development environment.', examples: ['treeseed dev'], executionMode: 'adapter', adapter: { script: 'tenant-dev' } }),
	command({ id: 'local.devWatch', name: 'dev:watch', aliases: [], group: 'Local Development', summary: 'Start local development with rebuild/watch mode.', description: 'Start local development with rebuild/watch mode.', examples: ['treeseed dev:watch'], executionMode: 'adapter', adapter: { script: 'tenant-dev', rewriteArgs: (args) => ['--watch', ...args] } }),
	command({ id: 'local.build', name: 'build', aliases: [], group: 'Local Development', summary: 'Build the tenant site and generated worker artifacts.', description: 'Build the tenant site and generated worker artifacts.', examples: ['treeseed build'], executionMode: 'adapter', adapter: { script: 'tenant-build' } }),
	command({ id: 'local.check', name: 'check', aliases: [], group: 'Local Development', summary: 'Run the tenant check flow.', description: 'Run the tenant check flow.', examples: ['treeseed check'], executionMode: 'adapter', adapter: { script: 'tenant-check' } }),
	command({ id: 'local.preview', name: 'preview', aliases: [], group: 'Local Development', summary: 'Preview the built tenant site locally.', description: 'Preview the built tenant site locally.', examples: ['treeseed preview'], executionMode: 'adapter', adapter: { script: 'tenant-astro-command', passthroughArgs: true } }),
	command({ id: 'local.lint', name: 'lint', aliases: [], group: 'Validation', summary: 'Run Treeseed lint checks.', description: 'Run Treeseed lint checks.', examples: ['treeseed lint'], executionMode: 'adapter', adapter: { directScript: 'tenant-lint', workspaceScript: 'workspace-lint', script: 'tenant-lint' } }),
	command({ id: 'local.test', name: 'test', aliases: [], group: 'Validation', summary: 'Run Treeseed tests.', description: 'Run Treeseed tests.', examples: ['treeseed test'], executionMode: 'adapter', adapter: { directScript: 'tenant-test', workspaceScript: 'workspace-test', script: 'tenant-test' } }),
	command({ id: 'validation.testUnit', name: 'test:unit', aliases: [], group: 'Validation', summary: 'Run workspace unit tests in dependency order.', description: 'Run workspace unit tests in dependency order.', examples: ['treeseed test:unit'], executionMode: 'adapter', adapter: { script: 'workspace-test-unit', requireWorkspaceRoot: true } }),
	command({ id: 'validation.preflight', name: 'preflight', aliases: [], group: 'Validation', summary: 'Check local CLI prerequisites and authentication state.', description: 'Check local CLI prerequisites and authentication state.', examples: ['treeseed preflight'], executionMode: 'adapter', adapter: { script: 'workspace-preflight', requireWorkspaceRoot: true } }),
	command({ id: 'validation.authCheck', name: 'auth:check', aliases: [], group: 'Validation', summary: 'Check CLI prerequisites and require authenticated tooling.', description: 'Check CLI prerequisites and require authenticated tooling.', examples: ['treeseed auth:check'], executionMode: 'adapter', adapter: { script: 'workspace-preflight', extraArgs: ['--require-auth'], requireWorkspaceRoot: true } }),
	command({ id: 'release.testE2e', name: 'test:e2e', aliases: [], group: 'Release Utilities', summary: 'Run Treeseed end-to-end command tests.', description: 'Run Treeseed end-to-end command tests.', examples: ['treeseed test:e2e'], executionMode: 'adapter', adapter: { script: 'workspace-command-e2e', requireWorkspaceRoot: true } }),
	command({ id: 'release.testE2eLocal', name: 'test:e2e:local', aliases: [], group: 'Release Utilities', summary: 'Run local-mode Treeseed end-to-end command tests.', description: 'Run local-mode Treeseed end-to-end command tests.', examples: ['treeseed test:e2e:local'], executionMode: 'adapter', adapter: { script: 'workspace-command-e2e', extraArgs: ['--mode=local'], requireWorkspaceRoot: true } }),
	command({ id: 'release.testE2eStaging', name: 'test:e2e:staging', aliases: [], group: 'Release Utilities', summary: 'Run staging-mode Treeseed end-to-end command tests.', description: 'Run staging-mode Treeseed end-to-end command tests.', examples: ['treeseed test:e2e:staging'], executionMode: 'adapter', adapter: { script: 'workspace-command-e2e', extraArgs: ['--mode=staging'], requireWorkspaceRoot: true } }),
	command({ id: 'release.testE2eFull', name: 'test:e2e:full', aliases: [], group: 'Release Utilities', summary: 'Run the full Treeseed end-to-end command suite.', description: 'Run the full Treeseed end-to-end command suite.', examples: ['treeseed test:e2e:full'], executionMode: 'adapter', adapter: { script: 'workspace-command-e2e', extraArgs: ['--mode=full'], requireWorkspaceRoot: true } }),
	command({ id: 'release.testFast', name: 'test:release', aliases: [], group: 'Release Utilities', summary: 'Run the fast release verification path.', description: 'Run the fast release verification path.', examples: ['treeseed test:release'], executionMode: 'adapter', adapter: { script: 'workspace-release-verify', requireWorkspaceRoot: true } }),
	command({ id: 'release.verify', name: 'test:release:full', aliases: ['release:verify'], group: 'Release Utilities', summary: 'Run the full release verification path.', description: 'Run the full release verification path.', examples: ['treeseed test:release:full', 'treeseed release:verify'], executionMode: 'adapter', adapter: { script: 'workspace-release-verify', extraArgs: ['--full-smoke'], requireWorkspaceRoot: true } }),
	command({ id: 'release.publishChanged', name: 'release:publish:changed', aliases: [], group: 'Release Utilities', summary: 'Publish changed Treeseed workspace packages.', description: 'Publish changed Treeseed workspace packages.', examples: ['treeseed release:publish:changed'], executionMode: 'adapter', adapter: { script: 'workspace-publish-changed-packages', requireWorkspaceRoot: true } }),
	command({ id: 'tools.astro', name: 'astro', aliases: [], group: 'Passthrough', summary: 'Pass through to the packaged Astro CLI wrapper.', description: 'Pass through to the packaged Astro CLI wrapper.', examples: ['treeseed astro -- --help'], executionMode: 'adapter', adapter: { script: 'tenant-astro-command', passthroughArgs: true } }),
	command({ id: 'tools.syncDevvars', name: 'sync:devvars', aliases: [], group: 'Utilities', summary: 'Regenerate .dev.vars from local configuration.', description: 'Regenerate .dev.vars from local configuration.', examples: ['treeseed sync:devvars'], executionMode: 'adapter', adapter: { script: 'sync-dev-vars' } }),
	command({ id: 'services.mailpitUp', name: 'mailpit:up', aliases: [], group: 'Utilities', summary: 'Start the package-managed Mailpit service.', description: 'Start the package-managed Mailpit service.', examples: ['treeseed mailpit:up'], executionMode: 'adapter', adapter: { script: 'ensure-mailpit' } }),
	command({ id: 'services.mailpitDown', name: 'mailpit:down', aliases: [], group: 'Utilities', summary: 'Stop the package-managed Mailpit service.', description: 'Stop the package-managed Mailpit service.', examples: ['treeseed mailpit:down'], executionMode: 'adapter', adapter: { script: 'stop-mailpit' } }),
	command({ id: 'services.mailpitLogs', name: 'mailpit:logs', aliases: [], group: 'Utilities', summary: 'Show Mailpit logs.', description: 'Show Mailpit logs.', examples: ['treeseed mailpit:logs'], executionMode: 'adapter', adapter: { script: 'logs-mailpit' } }),
	command({ id: 'data.d1MigrateLocal', name: 'd1:migrate:local', aliases: [], group: 'Utilities', summary: 'Apply local D1 migrations.', description: 'Apply local D1 migrations.', examples: ['treeseed d1:migrate:local'], executionMode: 'adapter', adapter: { script: 'tenant-d1-migrate-local' } }),
	command({ id: 'content.cleanupMarkdown', name: 'cleanup:markdown', aliases: [], group: 'Utilities', summary: 'Normalize Markdown and MDX files.', description: 'Normalize Markdown and MDX files.', examples: ['treeseed cleanup:markdown docs/README.md'], executionMode: 'adapter', adapter: { script: 'cleanup-markdown', rewriteArgs: (args) => ['--write', ...args] } }),
	command({ id: 'content.cleanupMarkdownCheck', name: 'cleanup:markdown:check', aliases: [], group: 'Utilities', summary: 'Check Markdown and MDX formatting without rewriting files.', description: 'Check Markdown and MDX formatting without rewriting files.', examples: ['treeseed cleanup:markdown:check docs/README.md'], executionMode: 'adapter', adapter: { script: 'cleanup-markdown', rewriteArgs: (args) => ['--check', ...args] } }),
	command({ id: 'tools.starlightPatch', name: 'starlight:patch', aliases: [], group: 'Utilities', summary: 'Apply the Starlight content path patch.', description: 'Apply the Starlight content path patch.', examples: ['treeseed starlight:patch'], executionMode: 'adapter', adapter: { script: 'patch-starlight-content-path' } }),
];

export const TRESEED_OPERATION_INDEX = new Map<string, TreeseedOperationSpec>();
for (const spec of TRESEED_OPERATION_SPECS) {
	TRESEED_OPERATION_INDEX.set(spec.name, spec);
	for (const alias of spec.aliases) TRESEED_OPERATION_INDEX.set(alias, spec);
}

export function findTreeseedOperation(name: string | null | undefined) {
	if (!name) return null;
	return TRESEED_OPERATION_INDEX.get(name) ?? null;
}

export function listTreeseedOperationNames() {
	return [...new Set(TRESEED_OPERATION_SPECS.map((spec) => spec.name))];
}
