import { AgentToolDefinition,EMPTY_OBJECT_SCHEMA,GENERIC_CONTENT_TOOLS,GENERIC_RESULT_SCHEMA,PRESET_CONTENT_TOOLS } from './agent-tool-execution-target.ts';
import { COMMUNICATION_TOOL_DEFINITIONS } from './communication-tool-definitions.ts';

export const AGENT_TOOL_DEFINITIONS: AgentToolDefinition[] = [
	{
		id: 'treeseed.assignment_plan', title: 'Manage assignment plan',
		description: 'Read or atomically create/update the assignment operational plan on its isolated TreeDX workspace ref. The initial plan is mandatory before other mutations.',
		inputSchema: { type: 'object', properties: {
			action: { type: 'string', enum: ['read', 'write'] }, expectedStateVersion: { type: 'integer', minimum: 1 },
			objective: { type: 'string', minLength: 1, maxLength: 4000 }, status: { type: 'string', enum: ['draft', 'ready', 'active', 'completed', 'superseded'] },
			completed: { type: 'array', maxItems: 100, items: { type: 'object', properties: { id: { type: 'string', minLength: 1 }, title: { type: 'string', minLength: 1 }, description: { type: 'string', minLength: 1 } }, required: ['id', 'title', 'description'], additionalProperties: false } },
			remaining: { type: 'array', maxItems: 100, items: { type: 'object', properties: { id: { type: 'string', minLength: 1 }, title: { type: 'string', minLength: 1 }, description: { type: 'string', minLength: 1 } }, required: ['id', 'title', 'description'], additionalProperties: false } },
			risks: { type: 'array', maxItems: 100, items: { type: 'object', properties: { id: { type: 'string', minLength: 1 }, title: { type: 'string', minLength: 1 }, description: { type: 'string', minLength: 1 } }, required: ['id', 'title', 'description'], additionalProperties: false } },
			resumeState: { type: 'object', properties: { checkpoint: { type: 'string', minLength: 1 }, nextAction: { type: 'string', minLength: 1 }, contextRefs: { type: 'array', uniqueItems: true, items: { type: 'string', minLength: 1 } } }, required: ['checkpoint', 'nextAction'], additionalProperties: false },
			body: { type: 'string', maxLength: 20000 }, idempotencyKey: { type: 'string', minLength: 8, maxLength: 256 },
		}, required: ['action'], additionalProperties: false, allOf: [{ if: { properties: { action: { const: 'write' } } }, then: { required: ['objective', 'remaining', 'expectedStateVersion', 'idempotencyKey'] } }] },
		outputSchema: GENERIC_RESULT_SCHEMA, executionTarget: 'provider_runner', mutability: 'content_write', telemetryCategory: 'content', requirements: ['provider_runner_runtime', 'treedx_proxy_handle', 'treedx_writable_workspace'],
	},
	{
		id: 'treeseed.assignment_status_update', title: 'Update assignment operational status',
		description: 'Atomically record a fresh assignment status on the isolated TreeDX workspace ref after the required initial plan.',
		inputSchema: { type: 'object', properties: { expectedStateVersion: { type: 'integer', minimum: 1 }, sequence: { type: 'integer', minimum: 0 }, previousStatusRef: { type: 'object', properties: { id: { type: 'string', minLength: 1 }, revision: { type: 'integer', minimum: 1 } }, required: ['id', 'revision'], additionalProperties: false }, phase: { type: 'string', minLength: 1, maxLength: 128 }, status: { type: 'string', enum: ['pending', 'admitted', 'leased', 'running', 'waiting', 'suspended', 'completed', 'failed', 'cancelled'] }, reason: { type: 'string', maxLength: 4000 }, progress: { type: 'number', minimum: 0, maximum: 1 }, body: { type: 'string', maxLength: 20000 }, idempotencyKey: { type: 'string', minLength: 8, maxLength: 256 } }, required: ['expectedStateVersion', 'sequence', 'phase', 'status', 'idempotencyKey'], additionalProperties: false, allOf: [{ if: { properties: { sequence: { minimum: 1 } }, required: ['sequence'] }, then: { required: ['previousStatusRef'] } }] },
		outputSchema: GENERIC_RESULT_SCHEMA, executionTarget: 'provider_runner', mutability: 'content_write', telemetryCategory: 'content', requirements: ['provider_runner_runtime', 'treedx_proxy_handle', 'treedx_writable_workspace'],
	},
	{
		id: 'treeseed.assignment_summary', title: 'Read or write assignment summary',
		description: 'Read or atomically write the terminal or suspension closeout summary on the isolated TreeDX workspace ref.',
		inputSchema: { type: 'object', properties: { action: { type: 'string', enum: ['read', 'write'] }, expectedStateVersion: { type: 'integer', minimum: 1 }, status: { type: 'string', enum: ['completed', 'failed', 'cancelled', 'suspended'] }, summary: { type: 'string', minLength: 1, maxLength: 12000 }, lessons: { type: 'array', maxItems: 100, uniqueItems: true, items: { type: 'string', minLength: 1 } }, blockers: { type: 'array', maxItems: 100, uniqueItems: true, items: { type: 'string', minLength: 1 } }, performance: { type: 'object', properties: { outcome: { type: 'string', minLength: 1 }, metrics: { type: 'object', additionalProperties: { type: 'number' } } }, required: ['outcome'], additionalProperties: false }, resumeState: { type: 'object', properties: { checkpoint: { type: 'string', minLength: 1 }, nextAction: { type: 'string', minLength: 1 }, contextRefs: { type: 'array', uniqueItems: true, items: { type: 'string', minLength: 1 } } }, required: ['checkpoint', 'nextAction'], additionalProperties: false }, artifactRefs: { type: 'array', maxItems: 100, uniqueItems: true, items: { type: 'string', minLength: 1 } }, verificationRefs: { type: 'array', maxItems: 100, uniqueItems: true, items: { type: 'string', minLength: 1 } }, body: { type: 'string', maxLength: 20000 }, idempotencyKey: { type: 'string', minLength: 8, maxLength: 256 } }, required: ['action'], additionalProperties: false, allOf: [{ if: { properties: { action: { const: 'write' } } }, then: { required: ['expectedStateVersion', 'status', 'summary', 'performance', 'idempotencyKey'] } }] },
		outputSchema: GENERIC_RESULT_SCHEMA, executionTarget: 'provider_runner', mutability: 'content_write', telemetryCategory: 'content', requirements: ['provider_runner_runtime', 'treedx_proxy_handle', 'treedx_writable_workspace'],
	},
	...COMMUNICATION_TOOL_DEFINITIONS,
	{
		id: 'treeseed.publish_signal',
		title: 'Publish assignment signal',
		description: 'Request one declared semantic signal with a durable subject, evidence, and concise change summary. AgentKernel and the API validate publication after execution.',
		inputSchema: {
			type: 'object',
			properties: {
				contractId: { type: 'string', minLength: 1, maxLength: 128 },
				subjectKind: { type: 'string', minLength: 1, maxLength: 64 },
				subjectId: { type: 'string', minLength: 1, maxLength: 256 },
				subjectGroupIds: { type: 'array', items: { type: 'string', minLength: 1, maxLength: 256 }, uniqueItems: true, maxItems: 32 },
				message: { type: 'string', minLength: 8, maxLength: 2000 },
				correlationId: { type: 'string', minLength: 1, maxLength: 256 },
				idempotencyKey: { type: 'string', minLength: 1, maxLength: 256 },
				payload: { type: 'object', additionalProperties: true },
			},
			required: ['contractId', 'subjectKind', 'subjectId', 'message'],
			additionalProperties: false,
		},
		outputSchema: GENERIC_RESULT_SCHEMA,
		executionTarget: 'provider_runner',
		mutability: 'shared_state_write',
		telemetryCategory: 'capacity',
		requirements: ['provider_runner_runtime'],
	},
	{
		id: 'treeseed.repository.read_file',
		title: 'Read assignment repository file',
		description: 'Read one bounded UTF-8 source file from the provider-materialized assignment repository.',
		inputSchema: {
			type: 'object',
			properties: {
				path: { type: 'string', minLength: 1, maxLength: 1024 },
				maxBytes: { type: 'integer', minimum: 1, maximum: 262144 },
			},
			required: ['path'],
			additionalProperties: false,
		},
		outputSchema: GENERIC_RESULT_SCHEMA,
		executionTarget: 'provider_runner',
		mutability: 'read',
		telemetryCategory: 'repository',
		requirements: ['provider_runner_git'],
	},
	{
		id: 'treeseed.repository.search',
		title: 'Search assignment repository',
		description: 'Run a bounded fixed-string search over provider-materialized assignment repository paths.',
		inputSchema: {
			type: 'object',
			properties: {
				query: { type: 'string', minLength: 1, maxLength: 500 },
				paths: { type: 'array', items: { type: 'string', minLength: 1, maxLength: 1024 }, maxItems: 32 },
				maxResults: { type: 'integer', minimum: 1, maximum: 200 },
			},
			required: ['query'],
			additionalProperties: false,
		},
		outputSchema: GENERIC_RESULT_SCHEMA,
		executionTarget: 'provider_runner',
		mutability: 'read',
		telemetryCategory: 'repository',
		requirements: ['provider_runner_git'],
	},
	{
		id: 'research.search_sources',
		title: 'Search governed research sources',
		description: 'Search the provider-configured research index and return bounded source metadata for citation work.',
		inputSchema: {
			type: 'object',
			properties: {
				query: { type: 'string', minLength: 3, maxLength: 500 },
				maxResults: { type: 'integer', minimum: 1, maximum: 20 },
			},
			required: ['query'],
			additionalProperties: false,
		},
		outputSchema: GENERIC_RESULT_SCHEMA,
		executionTarget: 'provider_runner',
		mutability: 'read',
		telemetryCategory: 'research',
		requirements: ['provider_runner_runtime', 'research_source_policy'],
	},
	{
		id: 'research.fetch_source',
		title: 'Fetch governed research source',
		description: 'Fetch a public HTTPS source through bounded SSRF-resistant research egress and return citation metadata plus a content hash.',
		inputSchema: {
			type: 'object',
			properties: {
				url: { type: 'string', minLength: 8, maxLength: 2048 },
				maxBytes: { type: 'integer', minimum: 1024, maximum: 1000000 },
				title: { type: 'string', minLength: 1, maxLength: 500 },
				publisher: { type: 'string', minLength: 1, maxLength: 500 },
				claimIds: { type: 'array', items: { type: 'string', minLength: 1 }, minItems: 1, maxItems: 50 },
				confidence: { type: 'string', enum: ['low', 'medium', 'high'] },
			},
			required: ['url'],
			additionalProperties: false,
		},
		outputSchema: GENERIC_RESULT_SCHEMA,
		executionTarget: 'provider_runner',
		mutability: 'read',
		telemetryCategory: 'research',
		requirements: ['provider_runner_runtime', 'research_source_policy'],
	},
	{
		id: 'treedx.build_context',
		title: 'Build TreeDX context',
		description: 'Build assignment-scoped TreeDX repository context for a query or path set.',
		inputSchema: {
			type: 'object',
			properties: {
				repoId: { type: 'string' },
				query: { type: 'string' },
				paths: { type: 'array', items: { type: 'string' } },
				maxNodes: { type: 'integer', minimum: 1, maximum: 64 },
				maxTokens: { type: 'integer', minimum: 256, maximum: 12000 },
			},
			additionalProperties: false,
		},
		outputSchema: GENERIC_RESULT_SCHEMA,
		executionTarget: 'treedx_proxy',
		mutability: 'read',
		telemetryCategory: 'treedx',
		requirements: ['treedx_proxy_handle'],
	},
	{
		id: 'treedx.read_repository_files',
		title: 'Read TreeDX repository files',
		description: 'Read repository files through the assignment-scoped TreeDX proxy.',
		inputSchema: {
			type: 'object',
			properties: {
				repoId: { type: 'string' },
				paths: { type: 'array', items: { type: 'string' } },
				ref: { type: 'string' },
			},
			required: ['paths'],
			additionalProperties: false,
		},
		outputSchema: GENERIC_RESULT_SCHEMA,
		executionTarget: 'treedx_proxy',
		mutability: 'read',
		telemetryCategory: 'treedx',
		requirements: ['treedx_proxy_handle'],
	},
	{
		id: 'treedx.search_workspace',
		title: 'Search TreeDX workspace',
		description: 'Search the assignment-scoped TreeDX workspace.',
		inputSchema: {
			type: 'object',
			properties: {
				workspaceId: { type: 'string' },
				query: { type: 'string' },
			},
			required: ['query'],
			additionalProperties: false,
		},
		outputSchema: GENERIC_RESULT_SCHEMA,
		executionTarget: 'treedx_proxy',
		mutability: 'read',
		telemetryCategory: 'treedx',
		requirements: ['treedx_proxy_handle'],
	},
	{
		id: 'treedx.read_workspace_file',
		title: 'Read TreeDX workspace file',
		description: 'Read a file from the assignment-scoped TreeDX workspace.',
		inputSchema: {
			type: 'object',
			properties: {
				workspaceId: { type: 'string' },
				path: { type: 'string' },
			},
			required: ['path'],
			additionalProperties: false,
		},
		outputSchema: GENERIC_RESULT_SCHEMA,
		executionTarget: 'treedx_proxy',
		mutability: 'read',
		telemetryCategory: 'treedx',
		requirements: ['treedx_proxy_handle'],
	},
	{
		id: 'treedx.apply_workspace_changeset',
		title: 'Apply TreeDX workspace changeset',
		description: 'Atomically apply a validated multi-file unified diff through the assignment-scoped TreeDX workspace proxy.',
		inputSchema: {
			type: 'object',
			properties: {
				workspaceId: { type: 'string' },
				contract: { type: 'string' },
				baseCommitSha: { type: 'string' },
				baseRef: { type: 'string' },
				patch: { type: 'string' },
				patchSha256: { type: 'string' },
				idempotencyKey: { type: 'string' },
				expectedDestinationRefHead: { type: 'string' },
			},
			required: ['contract', 'baseCommitSha', 'baseRef', 'patch', 'patchSha256', 'idempotencyKey'],
			additionalProperties: false,
		},
		outputSchema: GENERIC_RESULT_SCHEMA,
		executionTarget: 'treedx_proxy',
		mutability: 'content_write',
		telemetryCategory: 'treedx',
		requirements: ['treedx_proxy_handle', 'treedx_writable_workspace'],
	},
	{
		id: 'treedx.commit_workspace',
		title: 'Commit TreeDX workspace',
		description: 'Commit pending assignment-scoped TreeDX workspace changes.',
		inputSchema: {
			type: 'object',
			properties: {
				workspaceId: { type: 'string' },
				message: { type: 'string' },
			},
			required: ['message'],
			additionalProperties: false,
		},
		outputSchema: GENERIC_RESULT_SCHEMA,
		executionTarget: 'treedx_proxy',
		mutability: 'content_write',
		telemetryCategory: 'treedx',
		requirements: ['treedx_proxy_handle', 'treedx_writable_workspace', 'content_commit'],
	},
	{
		id: 'treeseed.status',
		title: 'Assignment status and time remaining',
		description: 'Inspect authoritative assignment status, start and deadline timestamps, wall-clock time remaining, and whether mandatory closeout has begun.',
		inputSchema: EMPTY_OBJECT_SCHEMA,
		outputSchema: GENERIC_RESULT_SCHEMA,
		executionTarget: 'sdk_dispatch',
		mutability: 'read',
		telemetryCategory: 'treeseed',
		requirements: ['sdk_dispatch'],
		dispatch: {
			namespace: 'workflow',
			operation: 'status',
			preferredMode: 'prefer_local',
			assignmentPreferredMode: 'auto',
		},
	},
	{
		id: 'treeseed.assignment_activity',
		title: 'Inspect assignment activity',
		description: 'Read bounded, sanitized forensic events for only the current assignment and workday. Team-wide evidence is never exposed through this tool.',
		inputSchema: {
			type: 'object',
			properties: {
				after: { type: 'integer', minimum: -1 },
				limit: { type: 'integer', minimum: 1, maximum: 200 },
				type: { type: 'string', minLength: 1, maxLength: 500 },
				severity: { type: 'string', minLength: 1, maxLength: 200 },
			},
			additionalProperties: false,
		},
		outputSchema: GENERIC_RESULT_SCHEMA,
		executionTarget: 'provider_runner',
		mutability: 'read',
		telemetryCategory: 'capacity',
		requirements: ['provider_runner_runtime'],
	},
	{
		id: 'treeseed.dev_plan',
		title: 'TreeSeed dev plan',
		description: 'Inspect the local development plan without starting services.',
		inputSchema: {
			type: 'object',
			properties: {
				webRuntime: { type: 'string' },
				app: { type: 'string' },
			},
			additionalProperties: false,
		},
		outputSchema: GENERIC_RESULT_SCHEMA,
		executionTarget: 'sdk_dispatch',
		mutability: 'read',
		telemetryCategory: 'treeseed',
		requirements: ['sdk_dispatch'],
		dispatch: {
			namespace: 'workflow',
			operation: 'dev',
			preferredMode: 'prefer_local',
			assignmentPreferredMode: 'prefer_local',
		},
	},
	{
		id: 'treeseed.changed_paths',
		title: 'Changed paths',
		description: 'Inspect changed paths in the assignment worktree.',
		inputSchema: {
			type: 'object',
			properties: {
				includeDiffSummary: { type: 'boolean' },
			},
			additionalProperties: false,
		},
		outputSchema: GENERIC_RESULT_SCHEMA,
		executionTarget: 'provider_runner',
		mutability: 'read',
		telemetryCategory: 'repository',
		requirements: ['assignment_worktree', 'provider_runner_git'],
	},
	{
		id: 'treeseed.verify',
		title: 'TreeSeed verify',
		description: 'Run bounded assignment-scoped Node or npm verification in the assigned worktree.',
		inputSchema: {
			type: 'object',
			properties: {
				commands: {
					type: 'array',
					minItems: 1,
					maxItems: 8,
					items: {
						type: 'object',
						properties: {
							command: { type: 'string', enum: ['node', 'npm'] },
							args: { type: 'array', items: { type: 'string' }, maxItems: 32 },
							cwd: { type: 'string' },
							expectedExitCode: { type: 'integer', minimum: 0, maximum: 255 },
							timeoutSeconds: { type: 'integer', minimum: 1, maximum: 300 },
						},
						required: ['command', 'args'],
						additionalProperties: false,
					},
				},
				reason: { type: 'string' },
			},
			required: ['commands'],
			additionalProperties: false,
		},
		outputSchema: GENERIC_RESULT_SCHEMA,
		executionTarget: 'provider_runner',
		mutability: 'read',
		telemetryCategory: 'treeseed',
		requirements: ['assignment_worktree', 'provider_runner_git'],
	},
	{
		id: 'treeseed.checkpoint',
		title: 'Checkpoint assignment worktree',
		description: 'Create a path-scoped local source commit for the assignment without pushing, merging, tagging, staging, or deploying.',
		inputSchema: {
			type: 'object',
			properties: { message: { type: 'string', minLength: 1 } },
			required: ['message'],
			additionalProperties: false,
		},
		outputSchema: GENERIC_RESULT_SCHEMA,
		executionTarget: 'provider_runner',
		mutability: 'worktree_write',
		telemetryCategory: 'repository',
		requirements: ['assignment_worktree', 'provider_runner_git'],
	},
	{
		id: 'treeseed.research_claims',
		title: 'Record research claims',
		description: 'Record the bounded claim-to-citation state for governed research workflow progression.',
		inputSchema: {
			type: 'object',
			properties: {
				claims: {
					type: 'array',
					minItems: 1,
					maxItems: 50,
					items: {
						type: 'object',
						properties: {
							id: { type: 'string', minLength: 1 },
							text: { type: 'string', minLength: 1 },
							material: { type: 'boolean' },
							status: { type: 'string', enum: ['unsupported', 'supported', 'contradicted'] },
							citationIds: { type: 'array', items: { type: 'string', minLength: 1 }, maxItems: 50 },
						},
						required: ['id', 'text', 'material', 'status', 'citationIds'],
						additionalProperties: false,
					},
				},
			},
			required: ['claims'],
			additionalProperties: false,
		},
		outputSchema: GENERIC_RESULT_SCHEMA,
		executionTarget: 'provider_runner',
		mutability: 'shared_state_write',
		telemetryCategory: 'research',
		requirements: ['provider_runner_runtime'],
	},
	{
		id: 'treeseed.review_decision',
		title: 'Record review decision',
		description: 'Record the Reviewer assignment disposition as explicitly approved or rejected for governed graph progression.',
		inputSchema: {
			type: 'object',
			properties: {
				disposition: { type: 'string', enum: ['approved', 'rejected'] },
				summary: { type: 'string', minLength: 1 },
			},
			required: ['disposition', 'summary'],
			additionalProperties: false,
		},
		outputSchema: GENERIC_RESULT_SCHEMA,
		executionTarget: 'provider_runner',
		mutability: 'shared_state_write',
		telemetryCategory: 'capacity',
		requirements: ['provider_runner_runtime'],
	},
	...GENERIC_CONTENT_TOOLS,
	...PRESET_CONTENT_TOOLS,
];
