import { sql } from 'drizzle-orm';
import { bigint, check, foreignKey, index, integer, pgTable, primaryKey, real, serial, text, uniqueIndex } from 'drizzle-orm/pg-core';
import { capacityExecutionProviders, capacityProviderLanes, capacityProviderTeamMemberships, capacityProviders } from '../../accounts/better-auth-account.ts';
import { capacityReservations } from '../providers/capacity-provider-team-credentials.ts';
import { agentModeRuns } from '../../agents/agent-mode-runs.ts';
import { teams } from '../../support/subscribers.ts';
import { projects } from '../../governance/policy/governance-electorate-snapshots.ts';
import { leaseState } from '../../accounts/notification-events.ts';

export const capacityLedgerEntries = pgTable('capacity_ledger_entries', {
	id: text('id').primaryKey(),
	settlementKey: text('settlement_key').notNull(),
	membershipId: text('membership_id').notNull(),
	capacityProviderId: text('capacity_provider_id').notNull(),
	reservationId: text('reservation_id'),
	assignmentId: text('assignment_id'),
	modeRunId: text('mode_run_id'),
	mode: text('mode'),
	teamId: text('team_id').notNull(),
	projectId: text('project_id'),
	workDayId: text('work_day_id'),
	taskId: text('task_id'),
	phase: text('phase').notNull(),
	credits: real('credits').notNull(),
	providerUnits: real('provider_units'),
	usd: real('usd'),
	source: text('source').notNull(),
	metadataJson: text('metadata_json').notNull().default('{}'),
	createdAt: text('created_at').notNull(),
}, (table) => [
	foreignKey({ name: 'fk_capacity_ledger_membership', columns: [table.membershipId], foreignColumns: [capacityProviderTeamMemberships.id] }).onDelete('restrict'),
	foreignKey({ name: 'fk_capacity_ledger_provider', columns: [table.capacityProviderId], foreignColumns: [capacityProviders.id] }).onDelete('restrict'),
	foreignKey({ name: 'fk_capacity_ledger_reservation', columns: [table.reservationId], foreignColumns: [capacityReservations.id] }).onDelete('restrict'),
	foreignKey({ name: 'fk_capacity_ledger_assignment', columns: [table.assignmentId], foreignColumns: [capacityProviderAssignments.id] }).onDelete('restrict'),
	foreignKey({ name: 'fk_capacity_ledger_mode_run', columns: [table.modeRunId], foreignColumns: [agentModeRuns.id] }).onDelete('restrict'),
	foreignKey({ name: 'fk_capacity_ledger_team', columns: [table.teamId], foreignColumns: [teams.id] }).onDelete('cascade'),
	foreignKey({ name: 'fk_capacity_ledger_project', columns: [table.projectId], foreignColumns: [projects.id] }).onDelete('restrict'),
	uniqueIndex('idx_capacity_ledger_settlement_key').on(table.settlementKey),
	uniqueIndex('idx_capacity_ledger_reservation_phase').on(table.reservationId, table.phase),
	index('idx_capacity_ledger_assignment').on(table.assignmentId, table.createdAt),
	index('idx_capacity_ledger_project_workday_created').on(table.projectId, table.workDayId, table.createdAt),
	check('chk_capacity_ledger_credits', sql`${table.credits} >= 0`)
]);

export const capacityUsageActuals = pgTable('capacity_usage_actuals', {
	id: text('id').primaryKey(),
	idempotencyKey: text('idempotency_key').notNull(),
	taskId: text('task_id'),
	workDayId: text('work_day_id'),
	projectId: text('project_id').notNull(),
	taskSignature: text('task_signature').notNull(),
	assignmentId: text('assignment_id'),
	assignmentAttempt: integer('assignment_attempt').notNull(),
	usageDimension: text('usage_dimension').notNull(),
	accountingMode: text('accounting_mode').notNull(),
	modeRunId: text('mode_run_id'),
	mode: text('mode'),
	capacityProviderId: text('capacity_provider_id'),
	executionProviderId: text('execution_provider_id'),
	laneId: text('lane_id'),
	businessModel: text('business_model').notNull(),
	modelName: text('model_name'),
	inputTokens: integer('input_tokens'),
	outputTokens: integer('output_tokens'),
	cachedInputTokens: integer('cached_input_tokens'),
	quotaMinutes: real('quota_minutes'),
	wallMinutes: real('wall_minutes'),
	filesOpened: integer('files_opened'),
	filesChanged: integer('files_changed'),
	diffLinesAdded: integer('diff_lines_added'),
	diffLinesRemoved: integer('diff_lines_removed'),
	testRuns: integer('test_runs'),
	retryCount: integer('retry_count'),
	actualCredits: real('actual_credits').notNull(),
	actualUsd: real('actual_usd'),
	creditFormulaVersion: text('credit_formula_version').notNull().default('treeseed.actual-credits.v1'),
	actualCreditSource: text('actual_credit_source').notNull().default('central_calculator'),
	nativeUsageJson: text('native_usage_json').notNull().default('{}'),
	metadataJson: text('metadata_json').notNull().default('{}'),
	createdAt: text('created_at').notNull(),
	executionProfileId: text('execution_profile_id').notNull().default('standard-code-model'),
}, (table) => [
	foreignKey({ name: 'fk_capacity_usage_actuals_project', columns: [table.projectId], foreignColumns: [projects.id] }).onDelete('cascade'),
	foreignKey({ name: 'fk_capacity_usage_actuals_assignment', columns: [table.assignmentId], foreignColumns: [capacityProviderAssignments.id] }).onDelete('cascade'),
	foreignKey({ name: 'fk_capacity_usage_actuals_mode_run', columns: [table.modeRunId], foreignColumns: [agentModeRuns.id] }).onDelete('cascade'),
	foreignKey({ name: 'fk_capacity_usage_actuals_provider', columns: [table.capacityProviderId], foreignColumns: [capacityProviders.id] }).onDelete('restrict'),
	foreignKey({ name: 'fk_capacity_usage_actuals_execution_provider', columns: [table.capacityProviderId, table.executionProviderId], foreignColumns: [capacityExecutionProviders.capacityProviderId, capacityExecutionProviders.id] }).onDelete('restrict'),
	foreignKey({ name: 'fk_capacity_usage_actuals_lane', columns: [table.capacityProviderId, table.laneId], foreignColumns: [capacityProviderLanes.capacityProviderId, capacityProviderLanes.id] }).onDelete('restrict'),
	uniqueIndex('idx_capacity_usage_actuals_idempotency').on(table.idempotencyKey),
	uniqueIndex('idx_capacity_usage_actuals_attempt_dimension').on(table.assignmentId, table.assignmentAttempt, table.usageDimension),
	index('idx_capacity_usage_actuals_project_signature').on(table.projectId, table.taskSignature, table.createdAt),
	index('idx_capacity_usage_actuals_project_signature_profile').on(table.projectId, table.taskSignature, table.executionProfileId, table.createdAt),
	index('idx_capacity_usage_actuals_execution_provider').on(table.executionProviderId, table.createdAt),
	index('idx_capacity_usage_actuals_lane').on(table.laneId, table.createdAt),
	check('chk_capacity_usage_actuals_credits', sql`${table.actualCredits} >= 0`),
	check('chk_capacity_usage_actuals_assignment_attempt', sql`${table.assignmentAttempt} >= 0`),
	check('chk_capacity_usage_actuals_accounting_mode', sql`${table.accountingMode} IN ('informational', 'incremental', 'aggregate')`)
]);

export const capacityAllocationSets = pgTable('capacity_allocation_sets', {
	id: text('id').primaryKey(),
	teamId: text('team_id').notNull(),
	version: integer('version').notNull(),
	status: text('status').notNull().default('draft'),
	effectiveFrom: text('effective_from').notNull(),
	effectiveUntil: text('effective_until'),
	reservePolicyJson: text('reserve_policy_json').notNull().default('{}'),
	slicesJson: text('slices_json').notNull().default('[]'),
	borrowingRulesJson: text('borrowing_rules_json').notNull().default('[]'),
	metadataJson: text('metadata_json').notNull().default('{}'),
	createdById: text('created_by_id'),
	activatedAt: text('activated_at'),
	supersededById: text('superseded_by_id'),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
}, (table) => [
	foreignKey({ name: 'fk_capacity_allocation_sets_team', columns: [table.teamId], foreignColumns: [teams.id] }).onDelete('cascade'),
	foreignKey({ name: 'fk_capacity_allocation_sets_superseded_by', columns: [table.supersededById], foreignColumns: [table.id] }).onDelete('restrict'),
	uniqueIndex('idx_capacity_allocation_sets_team_version').on(table.teamId, table.version),
	index('idx_capacity_allocation_sets_team_status').on(table.teamId, table.status, table.effectiveFrom),
	index('idx_capacity_allocation_sets_team_created').on(table.teamId, table.createdAt),
	check('chk_capacity_allocation_sets_version', sql`${table.version} >= 1`),
	check('chk_capacity_allocation_sets_status', sql`${table.status} IN ('draft', 'validated', 'active', 'superseded', 'archived')`),
	check('chk_capacity_allocation_sets_effective_interval', sql`${table.effectiveUntil} IS NULL OR ${table.effectiveUntil} > ${table.effectiveFrom}`)
]);

export const projectAgentClasses = pgTable('project_agent_classes', {
	id: text('id').primaryKey(),
	teamId: text('team_id').notNull(),
	projectId: text('project_id').notNull(),
	slug: text('slug').notNull(),
	name: text('name').notNull(),
	status: text('status').notNull().default('active'),
	allowedModesJson: text('allowed_modes_json').notNull().default('[]'),
	requiredCapabilitiesJson: text('required_capabilities_json').notNull().default('[]'),
	kernelProfileJson: text('kernel_profile_json').notNull().default('{}'),
	kernelPolicyJson: text('kernel_policy_json').notNull().default('{}'),
	handlerRefsJson: text('handler_refs_json').notNull().default('{}'),
	outputContractsJson: text('output_contracts_json').notNull().default('{}'),
	metadataJson: text('metadata_json').notNull().default('{}'),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
}, (table) => [
	foreignKey({ name: 'fk_project_agent_classes_team', columns: [table.teamId], foreignColumns: [teams.id] }).onDelete('cascade'),
	foreignKey({ name: 'fk_project_agent_classes_project', columns: [table.projectId], foreignColumns: [projects.id] }).onDelete('cascade'),
	uniqueIndex('idx_project_agent_classes_project_slug').on(table.projectId, table.slug),
	index('idx_project_agent_classes_team_project').on(table.teamId, table.projectId, table.status),
	check('chk_project_agent_classes_status', sql`${table.status} IN ('active', 'paused', 'archived')`)
]);

export const providerAvailabilitySessions = pgTable('capacity_provider_availability_sessions', {
	id: text('id').primaryKey(),
	membershipId: text('membership_id').notNull(),
	teamId: text('team_id').notNull(),
	capacityProviderId: text('capacity_provider_id').notNull(),
	environment: text('environment'),
	status: text('status').notNull().default('open'),
	sequence: integer('sequence').notNull().default(1),
	openedAt: text('opened_at').notNull(),
	refreshedAt: text('refreshed_at').notNull(),
	expiresAt: text('expires_at').notNull(),
	availableFrom: text('available_from').notNull(),
	availableUntil: text('available_until'),
	executionProvidersJson: text('execution_providers_json').notNull().default('[]'),
	capabilitiesJson: text('capabilities_json').notNull().default('[]'),
	nativeLimitsJson: text('native_limits_json').notNull().default('{}'),
	runnerPressureJson: text('runner_pressure_json').notNull().default('{}'),
	constraintsJson: text('constraints_json').notNull().default('{}'),
	metadataJson: text('metadata_json').notNull().default('{}'),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
	closedAt: text('closed_at'),
}, (table) => [
	foreignKey({ name: 'fk_capacity_provider_availability_sessions_membership', columns: [table.membershipId], foreignColumns: [capacityProviderTeamMemberships.id] }).onDelete('cascade'),
	foreignKey({ name: 'fk_capacity_provider_availability_sessions_team', columns: [table.teamId], foreignColumns: [teams.id] }).onDelete('cascade'),
	foreignKey({ name: 'fk_capacity_provider_availability_sessions_provider', columns: [table.capacityProviderId], foreignColumns: [capacityProviders.id] }).onDelete('restrict'),
	index('idx_capacity_provider_availability_sessions_membership_status').on(table.membershipId, table.status, table.expiresAt),
	index('idx_capacity_provider_availability_sessions_provider_status').on(table.capacityProviderId, table.status, table.refreshedAt),
	index('idx_capacity_provider_availability_sessions_team_status').on(table.teamId, table.status, table.refreshedAt),
	check('chk_capacity_provider_availability_sessions_sequence', sql`${table.sequence} >= 1`),
	check('chk_capacity_provider_availability_sessions_status', sql`${table.status} IN ('open', 'draining', 'closed', 'expired')`)
]);

export const capacityProviderAssignments = pgTable('capacity_provider_assignments', {
	id: text('id').primaryKey(),
	membershipId: text('membership_id').notNull(),
	teamId: text('team_id').notNull(),
	projectId: text('project_id').notNull(),
	capacityProviderId: text('capacity_provider_id').notNull(),
	providerSessionId: text('provider_session_id'),
	executionProviderId: text('execution_provider_id'),
	laneId: text('lane_id'),
	allocationSetId: text('allocation_set_id'),
	projectAgentClassId: text('project_agent_class_id').notNull(),
	reservationId: text('reservation_id'),
	workDayId: text('work_day_id'),
	taskId: text('task_id'),
	mode: text('mode').notNull(),
	status: text('status').notNull().default('pending'),
	leaseState: text('lease_state').notNull().default('unleased'),
	leaseExpiresAt: text('lease_expires_at'),
	leaseToken: text('lease_token'),
	stateVersion: integer('state_version').notNull().default(1),
	leaseRenewedAt: text('lease_renewed_at'),
	runnerId: text('runner_id'),
	agentId: text('agent_id'),
	handlerId: text('handler_id'),
	capacityEnvelopeJson: text('capacity_envelope_json').notNull().default('{}'),
	decisionInputJson: text('decision_input_json').notNull().default('{}'),
	workspaceContextJson: text('workspace_context_json').notNull().default('{}'),
	allowedOutputsJson: text('allowed_outputs_json').notNull().default('{}'),
	explanationJson: text('explanation_json').notNull().default('{}'),
	attemptCount: integer('attempt_count').notNull().default(0),
	assignedAt: text('assigned_at'),
	claimedAt: text('claimed_at'),
	completedAt: text('completed_at'),
	returnedAt: text('returned_at'),
	failedAt: text('failed_at'),
	lifecycleReason: text('lifecycle_reason'),
	lifecycleCode: text('lifecycle_code'),
	lifecycleOutputJson: text('lifecycle_output_json').notNull().default('{}'),
	synthesizedFrom: text('synthesized_from'),
	synthesisKey: text('synthesis_key'),
	decisionId: text('decision_id'),
	proposalId: text('proposal_id'),
	fallbackOutputId: text('fallback_output_id'),
	treedxProxyHandleJson: text('treedx_proxy_handle_json').notNull().default('{}'),
	metadataJson: text('metadata_json').notNull().default('{}'),
	createdAt: text('created_at').notNull(),
	updatedAt: text('updated_at').notNull(),
}, (table) => [
	foreignKey({ name: 'fk_capacity_provider_assignments_membership', columns: [table.membershipId], foreignColumns: [capacityProviderTeamMemberships.id] }).onDelete('restrict'),
	foreignKey({ name: 'fk_capacity_provider_assignments_team', columns: [table.teamId], foreignColumns: [teams.id] }).onDelete('cascade'),
	foreignKey({ name: 'fk_capacity_provider_assignments_project', columns: [table.projectId], foreignColumns: [projects.id] }).onDelete('restrict'),
	foreignKey({ name: 'fk_capacity_provider_assignments_provider', columns: [table.capacityProviderId], foreignColumns: [capacityProviders.id] }).onDelete('restrict'),
	foreignKey({ name: 'fk_capacity_provider_assignments_session', columns: [table.providerSessionId], foreignColumns: [providerAvailabilitySessions.id] }).onDelete('set null'),
	foreignKey({ name: 'fk_capacity_provider_assignments_execution_provider', columns: [table.capacityProviderId, table.executionProviderId], foreignColumns: [capacityExecutionProviders.capacityProviderId, capacityExecutionProviders.id] }).onDelete('restrict'),
	foreignKey({ name: 'fk_capacity_provider_assignments_lane', columns: [table.capacityProviderId, table.laneId], foreignColumns: [capacityProviderLanes.capacityProviderId, capacityProviderLanes.id] }).onDelete('restrict'),
	foreignKey({ name: 'fk_capacity_provider_assignments_allocation', columns: [table.allocationSetId], foreignColumns: [capacityAllocationSets.id] }).onDelete('restrict'),
	foreignKey({ name: 'fk_capacity_provider_assignments_agent_class', columns: [table.projectAgentClassId], foreignColumns: [projectAgentClasses.id] }).onDelete('restrict'),
	foreignKey({ name: 'fk_capacity_provider_assignments_reservation', columns: [table.reservationId], foreignColumns: [capacityReservations.id] }).onDelete('restrict'),
	index('idx_capacity_provider_assignments_membership_status').on(table.membershipId, table.status, table.leaseExpiresAt),
	index('idx_capacity_provider_assignments_provider_status').on(table.capacityProviderId, table.status, table.leaseExpiresAt),
	index('idx_capacity_provider_assignments_lane_status').on(table.laneId, table.status, table.leaseExpiresAt),
	index('idx_capacity_provider_assignments_project_mode').on(table.projectId, table.mode, table.status),
	index('idx_capacity_provider_assignments_lease').on(table.capacityProviderId, table.leaseState, table.leaseExpiresAt),
	index('idx_capacity_provider_assignments_runner').on(table.runnerId, table.leaseState),
	uniqueIndex('idx_capacity_provider_assignments_synthesis_key').on(table.teamId, table.synthesisKey),
	index('idx_capacity_provider_assignments_decision').on(table.decisionId, table.status),
	index('idx_capacity_provider_assignments_team_created').on(table.teamId, table.createdAt),
	check('chk_capacity_provider_assignments_state_version', sql`${table.stateVersion} >= 1`),
	check('chk_capacity_provider_assignments_mode', sql`${table.mode} IN ('planning', 'acting')`),
	check('chk_capacity_provider_assignments_status', sql`${table.status} IN ('pending', 'leased', 'running', 'completed', 'failed', 'returned', 'expired', 'cancelled')`),
	check('chk_capacity_provider_assignments_lease_state', sql`${table.leaseState} IN ('unleased', 'leased', 'released', 'expired')`)
]);
